// Generated by GitHub Copilot
import { useMemo, useState } from 'react';
import ProductCard from '../components/ProductCard';
import useCart from '../context/useCart';
import useProducts from '../context/useProducts';

/**
 * Product administration page for admin users.
 */
export default function AdminProducts() {
  const { showToast, removeProductReferences } = useCart();
  const { products, addProduct, updateProduct, deleteProduct } = useProducts();

  const [search, setSearch] = useState('');
  const [editingProductId, setEditingProductId] = useState(null);
  const [formData, setFormData] = useState({
    name: '',
    price: '',
    image: '',
    category: '',
    description: '',
  });

  const filteredProducts = useMemo(() => {
    const value = search.trim().toLowerCase();
    if (!value) {
      return products;
    }

    return products.filter((product) => (
      product.name.toLowerCase().includes(value)
      || product.category.toLowerCase().includes(value)
      || product.description.toLowerCase().includes(value)
    ));
  }, [products, search]);

  /**
   * Handles changes for add/edit product form.
   * @param {React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>} event
   */
  const handleFormChange = (event) => {
    const { name, value } = event.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  /** Starts editing with selected product values. */
  const startEditing = (product) => {
    setEditingProductId(product.id);
    setFormData({
      name: product.name,
      price: String(product.price),
      image: product.image,
      category: product.category,
      description: product.description,
    });
  };

  /** Resets admin form to create mode. */
  const resetAdminForm = () => {
    setEditingProductId(null);
    setFormData({ name: '', price: '', image: '', category: '', description: '' });
  };

  /**
   * Submits admin form to create or update product.
   * @param {React.FormEvent<HTMLFormElement>} event
   */
  const handleAdminSubmit = (event) => {
    event.preventDefault();

    const operation = editingProductId
      ? updateProduct(editingProductId, formData)
      : addProduct(formData);

    if (!operation.ok) {
      showToast(operation.error || 'No se pudo guardar el producto.', 'error');
      return;
    }

    showToast(editingProductId ? 'Producto actualizado correctamente.' : 'Producto creado correctamente.', 'success');
    resetAdminForm();
  };

  /** Deletes selected product after user confirmation. */
  const handleDeleteProduct = (product) => {
    const isConfirmed = window.confirm(`¿Seguro que quieres borrar "${product.name}"?`);
    if (!isConfirmed) {
      return;
    }

    const result = deleteProduct(product.id);
    if (!result.ok) {
      showToast(result.error || 'No se pudo borrar el producto.', 'error');
      return;
    }

    removeProductReferences(product.id);
    showToast('Producto borrado correctamente.', 'info');

    if (editingProductId === product.id) {
      resetAdminForm();
    }
  };

  return (
    <main className="max-w-6xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">Panel de productos</h1>
      <p className="text-gray-500 mb-6">Gestiona el catálogo: crea, edita y elimina productos.</p>

      <section className="mb-8 rounded-2xl border border-indigo-200 bg-indigo-50/40 p-4" aria-label="Gestión de productos">
        <h2 className="text-lg font-semibold text-indigo-900 mb-3">
          {editingProductId ? 'Editar producto' : 'Añadir producto'}
        </h2>

        <form className="grid grid-cols-1 md:grid-cols-2 gap-3" onSubmit={handleAdminSubmit}>
          <label className="text-sm text-gray-700">
            Nombre
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleFormChange}
              required
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>
          <label className="text-sm text-gray-700">
            Precio
            <input
              type="number"
              name="price"
              value={formData.price}
              onChange={handleFormChange}
              min="0"
              step="0.01"
              required
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>
          <label className="text-sm text-gray-700">
            Categoría
            <input
              type="text"
              name="category"
              value={formData.category}
              onChange={handleFormChange}
              required
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>
          <label className="text-sm text-gray-700">
            URL de imagen
            <input
              type="url"
              name="image"
              value={formData.image}
              onChange={handleFormChange}
              placeholder="https://..."
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>
          <label className="md:col-span-2 text-sm text-gray-700">
            Descripción
            <textarea
              name="description"
              value={formData.description}
              onChange={handleFormChange}
              required
              rows={3}
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          <div className="md:col-span-2 flex gap-2">
            <button
              type="submit"
              className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >
              {editingProductId ? 'Guardar cambios' : 'Crear producto'}
            </button>
            {editingProductId && (
              <button
                type="button"
                onClick={resetAdminForm}
                className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Cancelar edición
              </button>
            )}
          </div>
        </form>
      </section>

      <section className="mb-6" aria-label="Buscar productos">
        <label>
          <span className="sr-only">Buscar productos</span>
          <input
            type="search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Buscar por nombre, categoría o descripción..."
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </label>
      </section>

      <p className="text-sm text-gray-500 mb-6" aria-live="polite">
        {filteredProducts.length} producto{filteredProducts.length !== 1 ? 's' : ''} en catálogo
      </p>

      <section
        aria-label="Lista de productos administrables"
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"
      >
        {filteredProducts.map((product) => (
          <ProductCard
            key={product.id}
            product={product}
            onEditProduct={startEditing}
            onDeleteProduct={handleDeleteProduct}
          />
        ))}
      </section>
    </main>
  );
}
