// Generated by GitHub Copilot
// Para que sirve: Panel de administracion del catalogo con edicion y acciones masivas.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import ConfirmDialog from '../components/ConfirmDialog';
import ProductCard from '../components/ProductCard';
import useAuth from '../context/useAuth';
import useCart from '../context/useCart';
import useProducts from '../context/useProducts';
import useDocumentTitle from '../hooks/useDocumentTitle';

/* Maintenance guide:
 * - List behavior is driven by searchedProducts -> filteredProducts -> paginatedProducts.
 * - Bulk actions operate on bulkTargetProducts (selected or visible scope).
 * - Shift-range selection relies on lastSelectedProductId and filteredProducts order.
 * - Ctrl/Cmd+K focuses the admin search input using searchInputRef.
 */

const ADMIN_SELECTION_STORAGE_KEY = 'tienda_react_admin_selected_products';
const ADMIN_LIST_SETTINGS_STORAGE_KEY = 'tienda_react_admin_list_settings';
const AUTH_AUDIT_STORAGE_KEY = 'tienda_react_auth_audit';
const ALLOWED_PAGE_SIZES = [12, 24, 48];

/** Reads persisted selected product ids safely. */
function getInitialSelectedProductIds() {
  try {
    const raw = localStorage.getItem(ADMIN_SELECTION_STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    if (!Array.isArray(parsed)) {
      return [];
    }
    return Array.from(new Set(
      parsed
        .map((id) => Number.parseInt(String(id), 10))
        .filter((id) => Number.isInteger(id) && id > 0)
    ));
  } catch {
    return [];
  }
}

/** Reads persisted list settings safely. */
function getInitialAdminListSettings() {
  try {
    const raw = localStorage.getItem(ADMIN_LIST_SETTINGS_STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : {};
    const parsedPageSize = Number.parseInt(String(parsed?.pageSize ?? ''), 10);

    return {
      pageSize: ALLOWED_PAGE_SIZES.includes(parsedPageSize) ? parsedPageSize : 12,
      search: typeof parsed?.search === 'string' ? parsed.search.slice(0, 100) : '',
      sortBy: typeof parsed?.sortBy === 'string' ? parsed.sortBy : 'name-asc',
      activeCategory: typeof parsed?.activeCategory === 'string' ? parsed.activeCategory : 'Todos',
    };
  } catch {
    return {
      pageSize: 12,
      search: '',
      sortBy: 'name-asc',
      activeCategory: 'Todos',
    };
  }
}

/**
 * Builds compact pagination tokens using ellipsis around the current page.
 * @param {number} totalPages
 * @param {number} currentPage
 * @returns {Array<number | string>}
 */
function buildPaginationItems(totalPages, currentPage) {
  if (totalPages <= 7) {
    return Array.from({ length: totalPages }, (_, index) => index + 1);
  }

  const pages = new Set([1, totalPages, currentPage - 1, currentPage, currentPage + 1]);
  const sortedPages = Array.from(pages)
    .filter((page) => page >= 1 && page <= totalPages)
    .sort((a, b) => a - b);

  const items = [];
  sortedPages.forEach((page, index) => {
    if (index > 0) {
      const prevPage = sortedPages[index - 1];
      if (page - prevPage === 2) {
        items.push(prevPage + 1);
      } else if (page - prevPage > 2) {
        items.push('ellipsis');
      }
    }
    items.push(page);
  });

  return items;
}

/**
 * Validates remote image URLs used in product previews.
 * @param {string} value
 * @returns {string}
 */
function getPreviewImageUrl(value) {
  const trimmed = String(value || '').trim();
  return /^https?:\/\//i.test(trimmed) ? trimmed : '';
}

/** Escapes CSV cells safely for export. */
function escapeCsvCell(value) {
  const text = String(value ?? '');
  const escaped = text.replace(/"/g, '""');
  return /[",\n;]/.test(escaped) ? `"${escaped}"` : escaped;
}

/** Downloads plain text content as a file and releases temporary resources. */
function downloadTextFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');

  link.href = url;
  link.download = fileName;
  document.body.append(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

/** Formats auth audit timestamps in a locale-friendly way. */
function formatAuditTimestamp(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return 'Fecha no disponible';
  }

  return new Intl.DateTimeFormat('es-ES', {
    dateStyle: 'short',
    timeStyle: 'medium',
  }).format(date);
}

/** Builds CSV content for auth activity audit entries. */
function buildAuthAuditCsv(entries) {
  const headers = ['id', 'timestamp_iso', 'codigo', 'tipo', 'origen', 'mensaje'];
  const rows = entries.map((entry) => [
    escapeCsvCell(entry.id),
    escapeCsvCell(entry.at),
    escapeCsvCell(entry.code),
    escapeCsvCell(entry.type),
    escapeCsvCell(entry.source),
    escapeCsvCell(entry.message),
  ].join(','));

  return [headers.join(','), ...rows].join('\n');
}

/**
 * Product administration page for admin users.
 */
export default function AdminProducts() {
  // WCAG 2.4.2: descriptive page title announced by screen readers on navigation.
  useDocumentTitle('Admin — Productos');
  const { showToast, removeProductReferences } = useCart();
  const { getAuthAuditTrail, clearAuthAuditTrail } = useAuth();
  const { products, categories, addProduct, updateProduct, deleteProduct } = useProducts();
  const initialListSettings = getInitialAdminListSettings();

  const [search, setSearch] = useState(initialListSettings.search);
  const [debouncedSearch, setDebouncedSearch] = useState(initialListSettings.search);
  const [activeCategory, setActiveCategory] = useState(initialListSettings.activeCategory);
  const [sortBy, setSortBy] = useState(initialListSettings.sortBy);
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(initialListSettings.pageSize);
  const [editingProductId, setEditingProductId] = useState(null);
  const [productPendingDelete, setProductPendingDelete] = useState(null);
  const [selectedProductIds, setSelectedProductIds] = useState(getInitialSelectedProductIds);
  const [lastSelectedProductId, setLastSelectedProductId] = useState(null);
  const [showOnlySelected, setShowOnlySelected] = useState(false);
  const [isBulkDeleteOpen, setIsBulkDeleteOpen] = useState(false);
  const [bulkScope, setBulkScope] = useState('selected');
  const [selectedCategoryForBulk, setSelectedCategoryForBulk] = useState('');
  const [bulkCategoryTarget, setBulkCategoryTarget] = useState('');
  const [bulkPriceMode, setBulkPriceMode] = useState('percent');
  const [bulkPriceValue, setBulkPriceValue] = useState('');
  const [isBulkPriceConfirmOpen, setIsBulkPriceConfirmOpen] = useState(false);
  const [lastBulkChange, setLastBulkChange] = useState(null);
  const [formData, setFormData] = useState({
    name: '',
    price: '',
    image: '',
    category: '',
    description: '',
  });
  const [fieldErrors, setFieldErrors] = useState({});
  const [touched, setTouched] = useState({});
  const [formError, setFormError] = useState('');
  const [imagePreviewBrokenUrl, setImagePreviewBrokenUrl] = useState('');
  const [authAuditEntries, setAuthAuditEntries] = useState(() => getAuthAuditTrail());
  const [showFullAudit, setShowFullAudit] = useState(false);
  const searchInputRef = useRef(null);
  const activeCategorySafe = categories.includes(activeCategory) ? activeCategory : 'Todos';
  const previewImageUrl = getPreviewImageUrl(formData.image);
  const imagePreviewBroken = previewImageUrl && imagePreviewBrokenUrl === previewImageUrl;

  const validSelectedProductIds = useMemo(
    () => selectedProductIds.filter((id) => products.some((product) => product.id === id)),
    [products, selectedProductIds]
  );

  useEffect(() => {
    try {
      localStorage.setItem(ADMIN_SELECTION_STORAGE_KEY, JSON.stringify(validSelectedProductIds));
    } catch {
      // Ignore storage failures and keep in-memory selection.
    }
  }, [validSelectedProductIds]);

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      setDebouncedSearch(search);
    }, 250);

    return () => clearTimeout(timeoutId);
  }, [search]);

  useEffect(() => {
    /** Shortcut: Ctrl/Cmd + K focuses catalog search input quickly. */
    const handleKeydown = (event) => {
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') {
        event.preventDefault();
        searchInputRef.current?.focus();
      }
    };

    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  }, []);

  useEffect(() => {
    try {
      localStorage.setItem(ADMIN_LIST_SETTINGS_STORAGE_KEY, JSON.stringify({
        search,
        sortBy,
        activeCategory,
        pageSize,
      }));
    } catch {
      // Ignore storage failures and keep in-memory settings.
    }
  }, [activeCategory, pageSize, search, sortBy]);

  const searchedProducts = useMemo(() => {
    const value = debouncedSearch.trim().toLowerCase();
    const byCat = activeCategorySafe === 'Todos'
      ? products
      : products.filter((p) => p.category === activeCategorySafe);

    const bySearch = !value
      ? byCat
      : byCat.filter((product) => (
        product.name.toLowerCase().includes(value)
        || product.category.toLowerCase().includes(value)
        || product.description.toLowerCase().includes(value)
      ));

    return [...bySearch].sort((a, b) => {
      if (sortBy === 'price-asc') return a.price - b.price;
      if (sortBy === 'price-desc') return b.price - a.price;
      if (sortBy === 'name-desc') return b.name.localeCompare(a.name);
      return a.name.localeCompare(b.name); // name-asc default
    });
  }, [activeCategorySafe, debouncedSearch, products, sortBy]);

  const filteredProducts = useMemo(() => {
    if (!showOnlySelected) {
      return searchedProducts;
    }

    return searchedProducts.filter((product) => validSelectedProductIds.includes(product.id));
  }, [searchedProducts, showOnlySelected, validSelectedProductIds]);

  const totalPages = Math.max(1, Math.ceil(filteredProducts.length / pageSize));
  const safeCurrentPage = Math.min(currentPage, totalPages);
  const paginatedProducts = filteredProducts.slice(
    (safeCurrentPage - 1) * pageSize,
    safeCurrentPage * pageSize,
  );
  const visibleProducts = paginatedProducts;

  const selectedProducts = useMemo(
    () => products.filter((product) => validSelectedProductIds.includes(product.id)),
    [products, validSelectedProductIds]
  );

  const bulkTargetProducts = useMemo(
    () => (bulkScope === 'visible' ? visibleProducts : selectedProducts),
    [bulkScope, selectedProducts, visibleProducts]
  );

  const selectedVisibleCount = visibleProducts.filter((product) => validSelectedProductIds.includes(product.id)).length;
  const selectedFilteredCount = filteredProducts.filter((product) => validSelectedProductIds.includes(product.id)).length;
  const paginationItems = useMemo(
    () => buildPaginationItems(totalPages, safeCurrentPage),
    [safeCurrentPage, totalPages]
  );

  const visibleAuditEntries = useMemo(
    () => authAuditEntries.slice(0, showFullAudit ? 24 : 8),
    [authAuditEntries, showFullAudit]
  );

  const refreshAuthAudit = useCallback(() => {
    setAuthAuditEntries(getAuthAuditTrail());
  }, [getAuthAuditTrail]);

  useEffect(() => {
    const handleStorage = (event) => {
      if (event.key === AUTH_AUDIT_STORAGE_KEY) {
        refreshAuthAudit();
      }
    };

    const handleFocus = () => {
      refreshAuthAudit();
    };

    window.addEventListener('storage', handleStorage);
    window.addEventListener('focus', handleFocus);

    return () => {
      window.removeEventListener('storage', handleStorage);
      window.removeEventListener('focus', handleFocus);
    };
  }, [refreshAuthAudit]);

  /** Clears all persisted auth audit entries from local storage. */
  const handleClearAuthAudit = () => {
    clearAuthAuditTrail();
    setAuthAuditEntries([]);
    showToast('Historial de actividad de sesion limpiado.', 'info');
  };

  /** Exports auth activity audit entries as a CSV file. */
  const handleExportAuthAuditCsv = () => {
    if (authAuditEntries.length === 0) {
      showToast('No hay actividad de sesion para exportar.', 'info');
      return;
    }

    const csv = buildAuthAuditCsv(authAuditEntries);
    const csvWithBom = `\uFEFF${csv}`;
    const date = new Date().toISOString().slice(0, 10);
    downloadTextFile(csvWithBom, `actividad-sesion-${date}.csv`, 'text/csv;charset=utf-8;');
    showToast(`CSV de actividad exportado (${authAuditEntries.length} eventos).`, 'success');
  };

  /** Exports auth activity audit entries as a JSON file. */
  const handleExportAuthAuditJson = () => {
    if (authAuditEntries.length === 0) {
      showToast('No hay actividad de sesion para exportar.', 'info');
      return;
    }

    const date = new Date().toISOString().slice(0, 10);
    const json = `${JSON.stringify(authAuditEntries, null, 2)}\n`;
    downloadTextFile(json, `actividad-sesion-${date}.json`, 'application/json;charset=utf-8;');
    showToast(`JSON de actividad exportado (${authAuditEntries.length} eventos).`, 'success');
  };

  /**
   * Validates one form field and returns an error message if needed.
   * @param {string} name
   * @param {string} value
   * @returns {string | undefined}
   */
  const validateField = (name, value) => {
    if (name === 'name') {
      if (!value.trim()) return 'El nombre es obligatorio.';
      if (value.trim().length < 2) return 'El nombre debe tener al menos 2 caracteres.';
      if (value.trim().length > 120) return 'El nombre no puede superar 120 caracteres.';
      return undefined;
    }

    if (name === 'price') {
      if (value === '' || Number.isNaN(Number(value))) return 'El precio es obligatorio.';
      if (Number(value) < 0) return 'El precio no puede ser negativo.';
      if (Number(value) > 1000000) return 'El precio es demasiado alto.';
      return undefined;
    }

    if (name === 'category') {
      if (!value.trim()) return 'La categorÃ­a es obligatoria.';
      if (value.trim().length < 2) return 'La categorÃ­a debe tener al menos 2 caracteres.';
      if (value.trim().length > 50) return 'La categorÃ­a no puede superar 50 caracteres.';
      return undefined;
    }

    if (name === 'description') {
      if (!value.trim()) return 'La descripciÃ³n es obligatoria.';
      if (value.trim().length < 5) return 'La descripciÃ³n debe tener al menos 5 caracteres.';
      if (value.trim().length > 300) return 'La descripciÃ³n no puede superar 300 caracteres.';
      return undefined;
    }

    if (name === 'image') {
      if (value.trim() && !/^https?:\/\/[^\s]+$/i.test(value.trim())) {
        return 'La imagen debe ser una URL vÃ¡lida (http/https).';
      }
      return undefined;
    }

    return undefined;
  };

  /**
   * Validates all fields and returns a field-error map.
   * @returns {{ [key: string]: string | undefined }}
   */
  const validateForm = () => ({
    name: validateField('name', formData.name),
    price: validateField('price', String(formData.price)),
    image: validateField('image', formData.image),
    category: validateField('category', formData.category),
    description: validateField('description', formData.description),
  });

  /**
   * Handles changes for add/edit product form.
   * @param {React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>} event
   */
  const handleFormChange = (event) => {
    const { name, value } = event.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    if (touched[name]) {
      setFieldErrors((prev) => ({ ...prev, [name]: validateField(name, value) }));
    }
    if (formError) {
      setFormError('');
    }
  };

  /**
   * Marks field as touched and validates it.
   * @param {React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>} event
   */
  const handleFieldBlur = (event) => {
    const { name, value } = event.target;
    setTouched((prev) => ({ ...prev, [name]: true }));
    setFieldErrors((prev) => ({ ...prev, [name]: validateField(name, value) }));
  };

  /** Starts editing with selected product values. */
  const startEditing = (product) => {
    setEditingProductId(product.id);
    setFormData({
      name: product.name,
      price: String(product.price),
      image: product.image,
      category: product.category,
      description: product.description,
    });
  };

  /** Resets admin form to create mode. */
  const resetAdminForm = () => {
    setEditingProductId(null);
    setFormData({ name: '', price: '', image: '', category: '', description: '' });
    setFieldErrors({});
    setTouched({});
    setFormError('');
  };

  /** Duplicates a product by prefilling the form with its data. */
  const handleDuplicateProduct = (product) => {
    setEditingProductId(null);
    setFormData({
      name: `${product.name} (copia)`,
      price: String(product.price),
      image: product.image,
      category: product.category,
      description: product.description,
    });
    setTouched({});
    setFieldErrors({});
    setFormError('');
    showToast(`Duplicando: ${product.name}`, 'info');
  };

  /**
   * Submits admin form to create or update product.
   * @param {React.FormEvent<HTMLFormElement>} event
   */
  const handleAdminSubmit = (event) => {
    event.preventDefault();

    const nextErrors = validateForm();
    setTouched({
      name: true,
      price: true,
      image: true,
      category: true,
      description: true,
    });
    setFieldErrors(nextErrors);
    setFormError('');

    if (Object.values(nextErrors).some(Boolean)) {
      showToast('Revisa los campos marcados en el formulario.', 'error');
      return;
    }

    const operation = editingProductId
      ? updateProduct(editingProductId, formData)
      : addProduct(formData);

    if (!operation.ok) {
      setFormError(operation.error || 'No se pudo guardar el producto.');
      showToast(operation.error || 'No se pudo guardar el producto.', 'error');
      return;
    }

    showToast(editingProductId ? 'Producto actualizado correctamente.' : 'Producto creado correctamente.', 'success');
    resetAdminForm();
  };

  /** Opens confirmation modal before deleting a product. */
  const handleDeleteProduct = (product) => {
    setProductPendingDelete(product);
  };

  /** Toggles one product selection in bulk mode. */
  const toggleProductSelection = (productId, options = {}) => {
    const { shiftKey = false } = options;

    if (shiftKey && lastSelectedProductId) {
      const orderedIds = filteredProducts.map((product) => product.id);
      const fromIndex = orderedIds.indexOf(lastSelectedProductId);
      const toIndex = orderedIds.indexOf(productId);

      if (fromIndex >= 0 && toIndex >= 0) {
        const start = Math.min(fromIndex, toIndex);
        const end = Math.max(fromIndex, toIndex);
        const rangeIds = orderedIds.slice(start, end + 1);

        setSelectedProductIds((prev) => Array.from(new Set([...prev, ...rangeIds])));
        setLastSelectedProductId(productId);
        return;
      }
    }

    setSelectedProductIds((prev) => (
      prev.includes(productId)
        ? prev.filter((id) => id !== productId)
        : [...prev, productId]
    ));
    setLastSelectedProductId(productId);
  };

  /** Selects all currently visible products in the filtered list. */
  const selectVisibleProducts = () => {
    const visibleIds = visibleProducts.map((product) => product.id);
    setSelectedProductIds((prev) => Array.from(new Set([...prev, ...visibleIds])));
  };

  /** Selects all products from the category chosen in bulk controls. */
  const selectProductsByCategory = () => {
    if (!selectedCategoryForBulk) {
      showToast('Selecciona una categorÃ­a para aplicar la acciÃ³n.', 'info');
      return;
    }

    const idsInCategory = products
      .filter((product) => product.category === selectedCategoryForBulk)
      .map((product) => product.id);

    setSelectedProductIds((prev) => Array.from(new Set([...prev, ...idsInCategory])));
    showToast(`Se aÃ±adieron ${idsInCategory.length} producto${idsInCategory.length !== 1 ? 's' : ''} de ${selectedCategoryForBulk}.`, 'success');
  };

  /** Inverts selection for currently visible products. */
  const invertVisibleSelection = () => {
    const visibleIds = visibleProducts.map((product) => product.id);
    setSelectedProductIds((prev) => {
      const next = new Set(prev);
      visibleIds.forEach((id) => {
        if (next.has(id)) {
          next.delete(id);
        } else {
          next.add(id);
        }
      });
      return Array.from(next);
    });
  };

  /** Selects every product in catalog, regardless of current search filter. */
  const selectAllCatalogProducts = () => {
    setSelectedProductIds(products.map((product) => product.id));
  };

  /** Selects every product that matches the current filters (all pages). */
  const selectFilteredProducts = () => {
    const filteredIds = filteredProducts.map((product) => product.id);
    setSelectedProductIds((prev) => Array.from(new Set([...prev, ...filteredIds])));
  };

  /** Removes current filtered products from the current selection. */
  const unselectFilteredProducts = () => {
    if (filteredProducts.length === 0) {
      return;
    }

    const filteredIdSet = new Set(filteredProducts.map((product) => product.id));
    setSelectedProductIds((prev) => prev.filter((id) => !filteredIdSet.has(id)));
  };

  /** Clears any current product selection. */
  const clearSelection = () => {
    setSelectedProductIds([]);
  };

  /** Exports selected products to CSV file. */
  const exportSelectedToCsv = () => {
    if (selectedProducts.length === 0) {
      showToast('No hay productos seleccionados para exportar.', 'info');
      return;
    }

    const headers = ['id', 'nombre', 'precio', 'categoria', 'descripcion', 'imagen_url'];
    const rows = selectedProducts.map((product) => [
      product.id,
      product.name,
      Number(product.price || 0).toFixed(2),
      product.category,
      product.description,
      product.image,
    ].map(escapeCsvCell).join(','));

    const csvContent = `\uFEFF${[headers.join(','), ...rows].join('\n')}`;
    const date = new Date().toISOString().slice(0, 10);
    downloadTextFile(csvContent, `productos-seleccionados-${date}.csv`, 'text/csv;charset=utf-8;');
    showToast(`CSV exportado con ${selectedProducts.length} producto${selectedProducts.length !== 1 ? 's' : ''}.`, 'success');
  };

  /** Exports selected products to JSON file. */
  const exportSelectedToJson = () => {
    if (selectedProducts.length === 0) {
      showToast('No hay productos seleccionados para exportar.', 'info');
      return;
    }

    const jsonContent = `${JSON.stringify(selectedProducts, null, 2)}\n`;
    const date = new Date().toISOString().slice(0, 10);
    downloadTextFile(jsonContent, `productos-seleccionados-${date}.json`, 'application/json;charset=utf-8;');
    showToast(`JSON exportado con ${selectedProducts.length} producto${selectedProducts.length !== 1 ? 's' : ''}.`, 'success');
  };

  /** Moves selected products to a destination category. */
  const moveSelectedToCategory = () => {
    if (bulkTargetProducts.length === 0) {
      showToast('No hay productos para mover con el alcance elegido.', 'info');
      return;
    }

    if (!bulkCategoryTarget) {
      showToast('Selecciona una categorÃ­a destino.', 'info');
      return;
    }

    let movedCount = 0;
    let failedCount = 0;
    const previousState = [];

    bulkTargetProducts.forEach((product) => {
      if (product.category === bulkCategoryTarget) {
        return;
      }

      const result = updateProduct(product.id, {
        name: product.name,
        price: product.price,
        image: product.image,
        category: bulkCategoryTarget,
        description: product.description,
      });

      if (result.ok) {
        previousState.push({
          id: product.id,
          name: product.name,
          price: product.price,
          image: product.image,
          category: product.category,
          description: product.description,
        });
        movedCount += 1;
      } else {
        failedCount += 1;
      }
    });

    if (movedCount > 0) {
      setLastBulkChange({
        kind: 'move-category',
        label: `Mover a ${bulkCategoryTarget}`,
        items: previousState,
      });
      showToast(`Se movieron ${movedCount} producto${movedCount !== 1 ? 's' : ''} a ${bulkCategoryTarget}.`, 'success');
    }

    if (failedCount > 0) {
      showToast(`No se pudieron mover ${failedCount} producto${failedCount !== 1 ? 's' : ''}.`, 'error');
    }

    if (movedCount === 0 && failedCount === 0) {
      showToast('Los productos seleccionados ya estÃ¡n en esa categorÃ­a.', 'info');
    }
  };

  /** Applies a bulk price adjustment to selected products. */
  const applyBulkPriceAdjustment = () => {
    if (bulkTargetProducts.length === 0) {
      showToast('No hay productos para ajustar precio con el alcance elegido.', 'info');
      return;
    }

    const parsedValue = Number.parseFloat(String(bulkPriceValue));
    if (!Number.isFinite(parsedValue)) {
      showToast('Ingresa un valor vÃ¡lido para el ajuste.', 'error');
      return;
    }

    if (bulkPriceMode === 'percent' && (parsedValue < -90 || parsedValue > 500)) {
      showToast('El porcentaje debe estar entre -90 y 500.', 'error');
      return;
    }

    if (bulkPriceMode === 'fixed' && Math.abs(parsedValue) > 1000000) {
      showToast('El ajuste fijo es demasiado grande.', 'error');
      return;
    }

    setIsBulkPriceConfirmOpen(true);
  };

  /** Applies the already validated bulk price adjustment after user confirmation. */
  const confirmBulkPriceAdjustment = () => {
    const parsedValue = Number.parseFloat(String(bulkPriceValue));
    if (!Number.isFinite(parsedValue)) {
      setIsBulkPriceConfirmOpen(false);
      showToast('Ingresa un valor vÃ¡lido para el ajuste.', 'error');
      return;
    }

    if (bulkTargetProducts.length === 0) {
      setIsBulkPriceConfirmOpen(false);
      showToast('No hay productos para ajustar precio con el alcance elegido.', 'info');
      return;
    }

    let updatedCount = 0;
    let failedCount = 0;
    const previousState = [];

    bulkTargetProducts.forEach((product) => {
      const currentPrice = Number(product.price || 0);
      const nextPriceRaw = bulkPriceMode === 'percent'
        ? currentPrice * (1 + (parsedValue / 100))
        : currentPrice + parsedValue;
      const nextPrice = Math.max(0, Number(nextPriceRaw.toFixed(2)));

      if (nextPrice === currentPrice) {
        return;
      }

      const result = updateProduct(product.id, {
        name: product.name,
        price: nextPrice,
        image: product.image,
        category: product.category,
        description: product.description,
      });

      if (result.ok) {
        previousState.push({
          id: product.id,
          name: product.name,
          price: product.price,
          image: product.image,
          category: product.category,
          description: product.description,
        });
        updatedCount += 1;
      } else {
        failedCount += 1;
      }
    });

    if (updatedCount > 0) {
      const descriptor = bulkPriceMode === 'percent'
        ? `${parsedValue > 0 ? '+' : ''}${parsedValue}%`
        : `${parsedValue > 0 ? '+' : ''}$${parsedValue}`;
      setLastBulkChange({
        kind: 'update-price',
        label: `Ajuste ${descriptor}`,
        items: previousState,
      });
      showToast(`Precio actualizado en ${updatedCount} producto${updatedCount !== 1 ? 's' : ''} (${descriptor}).`, 'success');
    }

    if (failedCount > 0) {
      showToast(`No se pudieron actualizar ${failedCount} producto${failedCount !== 1 ? 's' : ''}.`, 'error');
    }

    if (updatedCount === 0 && failedCount === 0) {
      showToast('No hubo cambios de precio para aplicar.', 'info');
    }

    setIsBulkPriceConfirmOpen(false);
  };

  /** Confirms delete action and removes selected product. */
  const confirmDeleteProduct = () => {
    if (!productPendingDelete) {
      return;
    }

    const result = deleteProduct(productPendingDelete.id);
    if (!result.ok) {
      showToast(result.error || 'No se pudo borrar el producto.', 'error');
      return;
    }

    removeProductReferences(productPendingDelete.id);
    setSelectedProductIds((prev) => prev.filter((id) => id !== productPendingDelete.id));
    showToast('Producto borrado correctamente.', 'info');

    if (editingProductId === productPendingDelete.id) {
      resetAdminForm();
    }

    setProductPendingDelete(null);
  };

  /** Confirms bulk deletion for selected products. */
  const confirmBulkDelete = () => {
    if (selectedProductIds.length === 0) {
      setIsBulkDeleteOpen(false);
      return;
    }

    let deletedCount = 0;
    selectedProductIds.forEach((productId) => {
      const result = deleteProduct(productId);
      if (result.ok) {
        removeProductReferences(productId);
        deletedCount += 1;
      }
    });

    if (deletedCount > 0) {
      if (editingProductId && selectedProductIds.includes(editingProductId)) {
        resetAdminForm();
      }
      showToast(`Se borraron ${deletedCount} producto${deletedCount !== 1 ? 's' : ''}.`, 'info');
    } else {
      showToast('No se pudieron borrar los productos seleccionados.', 'error');
    }

    setSelectedProductIds([]);
    setIsBulkDeleteOpen(false);
  };

  /** Restores product data from the last successful bulk change. */
  const undoLastBulkChange = () => {
    if (!lastBulkChange || !Array.isArray(lastBulkChange.items) || lastBulkChange.items.length === 0) {
      showToast('No hay cambios masivos para deshacer.', 'info');
      return;
    }

    let restoredCount = 0;
    let failedCount = 0;

    lastBulkChange.items.forEach((product) => {
      const result = updateProduct(product.id, {
        name: product.name,
        price: product.price,
        image: product.image,
        category: product.category,
        description: product.description,
      });

      if (result.ok) {
        restoredCount += 1;
      } else {
        failedCount += 1;
      }
    });

    if (restoredCount > 0) {
      showToast(`Se revirtieron ${restoredCount} producto${restoredCount !== 1 ? 's' : ''} del Ãºltimo cambio masivo.`, 'success');
      setLastBulkChange(null);
    }

    if (failedCount > 0) {
      showToast(`No se pudieron restaurar ${failedCount} producto${failedCount !== 1 ? 's' : ''}.`, 'error');
    }
  };

  return (
    <main className="max-w-6xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">Panel de productos</h1>
      <p className="text-gray-500 mb-3">Gestiona el catÃ¡logo: crea, edita y elimina productos.</p>

      <section className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-3" aria-label="Resumen del catÃ¡logo">
        <div className="rounded-xl border border-gray-200 bg-white px-4 py-3 text-center">
          <p className="text-xs uppercase tracking-wide text-gray-500 mb-1">Total catÃ¡logo</p>
          <p className="text-2xl font-bold text-gray-900">{products.length}</p>
        </div>
        <div className="rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-3 text-center">
          <p className="text-xs uppercase tracking-wide text-indigo-600 mb-1">Filtrados</p>
          <p className="text-2xl font-bold text-indigo-700">{filteredProducts.length}</p>
        </div>
        <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-center">
          <p className="text-xs uppercase tracking-wide text-amber-600 mb-1">Seleccionados</p>
          <p className="text-2xl font-bold text-amber-700">{validSelectedProductIds.length}</p>
        </div>
      </section>

      <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-4" aria-label="Actividad de sesiÃ³n">
        <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
          <div>
            <h2 className="text-lg font-semibold text-slate-900">Actividad de sesiÃ³n</h2>
            <p className="text-xs text-slate-500">Eventos recientes de autenticaciÃ³n y cierre de sesiÃ³n.</p>
          </div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={refreshAuthAudit}
              className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 transition hover:bg-slate-50"
            >
              Actualizar
            </button>
            <button
              type="button"
              onClick={handleExportAuthAuditCsv}
              disabled={authAuditEntries.length === 0}
              className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Exportar CSV
            </button>
            <button
              type="button"
              onClick={handleExportAuthAuditJson}
              disabled={authAuditEntries.length === 0}
              className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Exportar JSON
            </button>
            <button
              type="button"
              onClick={handleClearAuthAudit}
              className="rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 text-xs font-medium text-red-700 transition hover:bg-red-100"
            >
              Limpiar
            </button>
          </div>
        </div>

        {visibleAuditEntries.length === 0 ? (
          <p className="rounded-lg border border-dashed border-slate-300 bg-slate-50 px-3 py-3 text-sm text-slate-600">
            No hay eventos registrados por ahora.
          </p>
        ) : (
          <>
            <ul className="space-y-2" role="list">
              {visibleAuditEntries.map((entry) => {
                const badgeClass = entry.type === 'error'
                  ? 'bg-red-100 text-red-700 border-red-200'
                  : entry.type === 'success'
                    ? 'bg-emerald-100 text-emerald-700 border-emerald-200'
                    : 'bg-slate-100 text-slate-700 border-slate-200';

                return (
                  <li key={entry.id} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className={`rounded-full border px-2 py-0.5 text-xs font-semibold ${badgeClass}`}>
                        {entry.code}
                      </span>
                      <span className="text-xs text-slate-500">{formatAuditTimestamp(entry.at)}</span>
                      <span className="ml-auto text-[11px] uppercase tracking-wide text-slate-400">{entry.source}</span>
                    </div>
                    <p className="mt-1 text-sm text-slate-700">{entry.message}</p>
                  </li>
                );
              })}
            </ul>

            {authAuditEntries.length > 8 && (
              <button
                type="button"
                onClick={() => setShowFullAudit((prev) => !prev)}
                className="mt-3 text-xs font-semibold text-indigo-600 hover:text-indigo-700"
              >
                {showFullAudit ? 'Ver menos' : `Ver mÃ¡s (${Math.min(24, authAuditEntries.length)})`}
              </button>
            )}
          </>
        )}
      </section>

      <section className="mb-8 rounded-2xl border border-indigo-200 bg-indigo-50/40 p-4" aria-label="GestiÃ³n de productos">
        <h2 className="text-lg font-semibold text-indigo-900 mb-3">
          {editingProductId ? 'Editar producto' : 'Añadir producto'}
        </h2>

        <form className="grid grid-cols-1 md:grid-cols-2 gap-3" onSubmit={handleAdminSubmit}>
          {formError && (
            <p className="md:col-span-2 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">
              {formError}
            </p>
          )}

          <label className="text-sm text-gray-700">
            Nombre
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleFormChange}
              onBlur={handleFieldBlur}
              required
              aria-invalid={Boolean(touched.name && fieldErrors.name)}
              aria-describedby={touched.name && fieldErrors.name ? 'admin-name-error' : undefined}
              className={`mt-1 w-full rounded-xl bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.name && fieldErrors.name ? 'border border-red-400' : 'border border-gray-300'
              }`}
            />
            {touched.name && fieldErrors.name && (
              <span id="admin-name-error" className="mt-1 block text-xs text-red-500" role="alert">{fieldErrors.name}</span>
            )}
          </label>
          <label className="text-sm text-gray-700">
            Precio
            <input
              type="number"
              name="price"
              value={formData.price}
              onChange={handleFormChange}
              onBlur={handleFieldBlur}
              min="0"
              step="0.01"
              required
              aria-invalid={Boolean(touched.price && fieldErrors.price)}
              aria-describedby={touched.price && fieldErrors.price ? 'admin-price-error' : undefined}
              className={`mt-1 w-full rounded-xl bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.price && fieldErrors.price ? 'border border-red-400' : 'border border-gray-300'
              }`}
            />
            {touched.price && fieldErrors.price && (
              <span id="admin-price-error" className="mt-1 block text-xs text-red-500" role="alert">{fieldErrors.price}</span>
            )}
          </label>
          <label className="text-sm text-gray-700">
            CategorÃ­a
            <input
              type="text"
              name="category"
              value={formData.category}
              onChange={handleFormChange}
              onBlur={handleFieldBlur}
              required
              aria-invalid={Boolean(touched.category && fieldErrors.category)}
              aria-describedby={touched.category && fieldErrors.category ? 'admin-category-error' : undefined}
              className={`mt-1 w-full rounded-xl bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.category && fieldErrors.category ? 'border border-red-400' : 'border border-gray-300'
              }`}
            />
            {touched.category && fieldErrors.category && (
              <span id="admin-category-error" className="mt-1 block text-xs text-red-500" role="alert">{fieldErrors.category}</span>
            )}
          </label>
          <label className="text-sm text-gray-700">
            URL de imagen
            <input
              type="url"
              name="image"
              value={formData.image}
              onChange={handleFormChange}
              onBlur={handleFieldBlur}
              placeholder="https://..."
              aria-invalid={Boolean(touched.image && fieldErrors.image)}
              aria-describedby={touched.image && fieldErrors.image ? 'admin-image-error' : undefined}
              className={`mt-1 w-full rounded-xl bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.image && fieldErrors.image ? 'border border-red-400' : 'border border-gray-300'
              }`}
            />
            {touched.image && fieldErrors.image && (
              <span id="admin-image-error" className="mt-1 block text-xs text-red-500" role="alert">{fieldErrors.image}</span>
            )}
          </label>
          <label className="md:col-span-2 text-sm text-gray-700">
            DescripciÃ³n
            <textarea
              name="description"
              value={formData.description}
              onChange={handleFormChange}
              onBlur={handleFieldBlur}
              required
              rows={3}
              aria-invalid={Boolean(touched.description && fieldErrors.description)}
              aria-describedby={touched.description && fieldErrors.description ? 'admin-description-error' : undefined}
              className={`mt-1 w-full rounded-xl bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.description && fieldErrors.description ? 'border border-red-400' : 'border border-gray-300'
              }`}
            />
            {touched.description && fieldErrors.description && (
              <span id="admin-description-error" className="mt-1 block text-xs text-red-500" role="alert">{fieldErrors.description}</span>
            )}
          </label>

          <div className="md:col-span-2 rounded-xl border border-gray-200 bg-white p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-gray-500 mb-2">Vista previa de imagen</p>
            {previewImageUrl && !imagePreviewBroken && (
              <img
                src={previewImageUrl}
                alt={formData.name ? `Vista previa de ${formData.name}` : 'Vista previa de producto'}
                onError={() => setImagePreviewBrokenUrl(previewImageUrl)}
                className="h-36 w-full rounded-lg object-cover"
                loading="lazy"
              />
            )}
            {!previewImageUrl && (
              <p className="text-sm text-gray-500">Ingresa una URL de imagen vÃ¡lida (http/https) para ver la vista previa.</p>
            )}
            {previewImageUrl && imagePreviewBroken && (
              <p className="text-sm text-amber-700">No se pudo cargar la imagen con la URL proporcionada.</p>
            )}
          </div>

          <div className="md:col-span-2 flex gap-2">
            <button
              type="submit"
              className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >
              {editingProductId ? 'Guardar cambios' : 'Crear producto'}
            </button>
            {editingProductId && (
              <button
                type="button"
                onClick={resetAdminForm}
                className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >
                Cancelar ediciÃ³n
              </button>
            )}
          </div>
        </form>
      </section>

      <section className="mb-6 grid grid-cols-1 md:grid-cols-4 gap-3" aria-label="Filtros del catÃ¡logo">
        <label className="md:col-span-2">
          <span className="sr-only">Buscar productos</span>
          <input
            ref={searchInputRef}
            type="search"
            value={search}
            onChange={(e) => { setSearch(e.target.value); setCurrentPage(1); }}
            placeholder="Buscar por nombre, categorÃ­a o descripciÃ³n..."
            title="Atajo: Ctrl/Cmd + K"
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </label>
        <label>
          <span className="sr-only">Ordenar productos</span>
          <select
            value={sortBy}
            onChange={(e) => { setSortBy(e.target.value); setCurrentPage(1); }}
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="name-asc">Nombre: Aâ€“Z</option>
            <option value="name-desc">Nombre: Zâ€“A</option>
            <option value="price-asc">Precio: menor a mayor</option>
            <option value="price-desc">Precio: mayor a menor</option>
          </select>
        </label>
        <label>
          <span className="sr-only">TamaÃ±o de pÃ¡gina</span>
          <select
            value={String(pageSize)}
            onChange={(e) => {
              const nextPageSize = Number.parseInt(e.target.value, 10);
              setPageSize(ALLOWED_PAGE_SIZES.includes(nextPageSize) ? nextPageSize : 12);
              setCurrentPage(1);
            }}
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="12">12 por pÃ¡gina</option>
            <option value="24">24 por pÃ¡gina</option>
            <option value="48">48 por pÃ¡gina</option>
          </select>
        </label>
      </section>

      {/* Category chips */}
      <div className="flex flex-wrap gap-2 mb-6" role="group" aria-label="Filtrar por categorÃ­a">
        {categories.map((cat) => (
          <button
            key={cat}
            type="button"
            onClick={() => { setActiveCategory(cat); setCurrentPage(1); }}
            className={`px-3 py-1.5 rounded-full text-xs font-semibold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 ${
              activeCategorySafe === cat
                ? 'bg-indigo-600 text-white'
                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            }`}
            aria-pressed={activeCategorySafe === cat}
          >
            {cat}
          </button>
        ))}
      </div>

      <section className="mb-4 flex flex-wrap items-center justify-between gap-2" aria-label="Acciones masivas">
        <p className="text-sm text-gray-600">
          Seleccionados: {selectedProductIds.length}
          {selectedVisibleCount > 0 ? ` (${selectedVisibleCount} visibles)` : ''}
        </p>
        <div className="flex flex-wrap gap-2">
          <select
            value={bulkScope}
            onChange={(event) => setBulkScope(event.target.value)}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            aria-label="Alcance de acciones masivas"
          >
            <option value="selected">Alcance: seleccionados</option>
            <option value="visible">Alcance: visibles (pÃ¡gina)</option>
          </select>
          <button
            type="button"
            onClick={undoLastBulkChange}
            disabled={!lastBulkChange}
            className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm font-semibold text-amber-700 transition hover:bg-amber-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-600 disabled:cursor-not-allowed disabled:opacity-50"
            title={lastBulkChange ? `Deshacer: ${lastBulkChange.label}` : 'No hay cambios masivos para deshacer'}
          >
            Deshacer Ãºltimo masivo
          </button>
          <select
            value={bulkPriceMode}
            onChange={(event) => setBulkPriceMode(event.target.value)}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            aria-label="Modo de ajuste de precio para seleccionados"
          >
            <option value="percent">Ajuste %</option>
            <option value="fixed">Ajuste fijo $</option>
          </select>
          <input
            type="number"
            value={bulkPriceValue}
            onChange={(event) => setBulkPriceValue(event.target.value)}
            placeholder={bulkPriceMode === 'percent' ? 'Ej: 10 o -5' : 'Ej: 15 o -3'}
            step="0.01"
            className="w-36 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            aria-label="Valor de ajuste de precio"
          />
          <button
            type="button"
            onClick={applyBulkPriceAdjustment}
            disabled={bulkTargetProducts.length === 0 || bulkPriceValue.trim() === ''}
            className="rounded-lg border border-indigo-300 bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700 transition hover:bg-indigo-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Ajustar precio
          </button>
          <select
            value={bulkCategoryTarget}
            onChange={(event) => setBulkCategoryTarget(event.target.value)}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            aria-label="CategorÃ­a destino para productos seleccionados"
          >
            <option value="">Mover seleccionados a...</option>
            {categories.filter((category) => category !== 'Todos').map((category) => (
              <option key={`dest-${category}`} value={category}>{category}</option>
            ))}
          </select>
          <button
            type="button"
            onClick={moveSelectedToCategory}
            disabled={bulkTargetProducts.length === 0 || !bulkCategoryTarget}
            className="rounded-lg border border-indigo-300 bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700 transition hover:bg-indigo-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Mover categorÃ­a
          </button>
          <select
            value={selectedCategoryForBulk}
            onChange={(event) => setSelectedCategoryForBulk(event.target.value)}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            aria-label="Seleccionar categorÃ­a para acciÃ³n masiva"
          >
            <option value="">Seleccionar categorÃ­a...</option>
            {categories.filter((category) => category !== 'Todos').map((category) => (
              <option key={category} value={category}>{category}</option>
            ))}
          </select>
          <button
            type="button"
            onClick={selectProductsByCategory}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Seleccionar categorÃ­a
          </button>
          <button
            type="button"
            onClick={exportSelectedToCsv}
            disabled={selectedProductIds.length === 0}
            className="rounded-lg border border-emerald-300 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700 transition hover:bg-emerald-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Exportar seleccionados CSV
          </button>
          <button
            type="button"
            onClick={exportSelectedToJson}
            disabled={selectedProductIds.length === 0}
            className="rounded-lg border border-sky-300 bg-sky-50 px-3 py-2 text-sm font-semibold text-sky-700 transition hover:bg-sky-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Exportar seleccionados JSON
          </button>
          <button
            type="button"
            onClick={selectAllCatalogProducts}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Seleccionar todo catÃ¡logo
          </button>
          <button
            type="button"
            onClick={selectFilteredProducts}
            disabled={filteredProducts.length === 0}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Seleccionar filtrados
          </button>
          <button
            type="button"
            onClick={unselectFilteredProducts}
            disabled={selectedFilteredCount === 0}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Quitar filtrados
          </button>
          <button
            type="button"
            onClick={selectVisibleProducts}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Seleccionar visibles
          </button>
          <button
            type="button"
            onClick={invertVisibleSelection}
            disabled={visibleProducts.length === 0}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Invertir visibles
          </button>
          <button
            type="button"
            onClick={clearSelection}
            disabled={selectedProductIds.length === 0}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Limpiar selecciÃ³n
          </button>
          <button
            type="button"
            onClick={() => { setShowOnlySelected((prev) => !prev); setCurrentPage(1); }}
            disabled={selectedProductIds.length === 0 && !showOnlySelected}
            className={`rounded-lg border px-3 py-2 text-sm font-medium transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:cursor-not-allowed disabled:opacity-50 ${
              showOnlySelected
                ? 'border-indigo-300 bg-indigo-50 text-indigo-700 hover:bg-indigo-100'
                : 'border-gray-300 bg-white text-gray-700 hover:bg-gray-50'
            }`}
            aria-pressed={showOnlySelected}
          >
            {showOnlySelected ? 'Ver todos' : 'Solo seleccionados'}
          </button>
          <button
            type="button"
            onClick={() => setIsBulkDeleteOpen(true)}
            disabled={selectedProductIds.length === 0}
            className="rounded-lg border border-red-300 bg-red-50 px-3 py-2 text-sm font-semibold text-red-700 transition hover:bg-red-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Borrar seleccionados
          </button>
        </div>
      </section>

      <p className="mb-3 text-xs text-gray-500" role="note">
        Atajos: Ctrl/Cmd + K para buscar. Shift + clic o Shift + Espacio/Enter en "Seleccionar" para elegir un rango.
      </p>

      <p className="text-sm text-gray-500 mb-6" aria-live="polite">
        {filteredProducts.length} producto{filteredProducts.length !== 1 ? 's' : ''} Â· PÃ¡gina {safeCurrentPage} de {totalPages}
      </p>

      <section
        aria-label="Lista de productos administrables"
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"
      >
        {paginatedProducts.map((product) => (
          <ProductCard
            key={product.id}
            product={product}
            onEditProduct={startEditing}
            onDeleteProduct={handleDeleteProduct}
            onDuplicateProduct={handleDuplicateProduct}
            onToggleSelectProduct={toggleProductSelection}
            isSelected={selectedProductIds.includes(product.id)}
          />
        ))}
      </section>

      {filteredProducts.length === 0 && (
        <div className="mt-8 rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-10 text-center">
          <p className="text-lg font-semibold text-gray-800">Sin resultados</p>
          <p className="text-sm text-gray-500 mt-1">Prueba con otro tÃ©rmino de bÃºsqueda o cambia la categorÃ­a.</p>
        </div>
      )}

      {totalPages > 1 && (
        <nav className="mt-8 flex items-center justify-center gap-3" aria-label="PaginaciÃ³n de productos">
          <button
            type="button"
            onClick={() => setCurrentPage((prev) => Math.max(1, prev - 1))}
            disabled={safeCurrentPage === 1}
            className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Anterior
          </button>
          {paginationItems.map((item, index) => {
            if (item === 'ellipsis') {
              return (
                <span
                  key={`ellipsis-${index}`}
                  className="px-1 text-sm font-semibold text-gray-500"
                  aria-hidden="true"
                >
                  ...
                </span>
              );
            }

            return (
              <button
                key={item}
                type="button"
                onClick={() => setCurrentPage(item)}
                aria-current={item === safeCurrentPage ? 'page' : undefined}
                className={`rounded-lg border px-3 py-2 text-sm font-medium transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 ${
                  item === safeCurrentPage
                    ? 'border-indigo-600 bg-indigo-600 text-white'
                    : 'border-gray-300 bg-white text-gray-700 hover:bg-gray-50'
                }`}
              >
                {item}
              </button>
            );
          })}
          <button
            type="button"
            onClick={() => setCurrentPage((prev) => Math.min(totalPages, prev + 1))}
            disabled={safeCurrentPage === totalPages}
            className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Siguiente
          </button>
        </nav>
      )}

      <ConfirmDialog
        open={Boolean(productPendingDelete)}
        title="Eliminar producto"
        message={productPendingDelete ? `Â¿Seguro que quieres borrar "${productPendingDelete.name}"? Esta acciÃ³n no se puede deshacer.` : ''}
        confirmLabel="SÃ­, eliminar"
        cancelLabel="Cancelar"
        onCancel={() => setProductPendingDelete(null)}
        onConfirm={confirmDeleteProduct}
        destructive
      />

      <ConfirmDialog
        open={isBulkDeleteOpen}
        title="Borrar productos seleccionados"
        message={`Se eliminarÃ¡n ${selectedProductIds.length} producto${selectedProductIds.length !== 1 ? 's' : ''} del catÃ¡logo. Esta acciÃ³n no se puede deshacer.`}
        confirmLabel="SÃ­, borrar todo"
        cancelLabel="Cancelar"
        onCancel={() => setIsBulkDeleteOpen(false)}
        onConfirm={confirmBulkDelete}
        destructive
      />

      <ConfirmDialog
        open={isBulkPriceConfirmOpen}
        title="Confirmar ajuste de precio"
        message={`Se aplicarÃ¡ ${bulkPriceMode === 'percent' ? `${bulkPriceValue}%` : `$${bulkPriceValue}`} sobre ${bulkTargetProducts.length} producto${bulkTargetProducts.length !== 1 ? 's' : ''} (${bulkScope === 'visible' ? 'visibles' : 'seleccionados'}).`}
        confirmLabel="SÃ­, aplicar ajuste"
        cancelLabel="Cancelar"
        onCancel={() => setIsBulkPriceConfirmOpen(false)}
        onConfirm={confirmBulkPriceAdjustment}
      />
    </main>
  );
}
