// Generated by GitHub Copilot
import { useEffect, useMemo, useRef, useState } from 'react';
import ProductCard from '../components/ProductCard';
import ConfirmDialog from '../components/ConfirmDialog';
import useCart from '../context/useCart';
import useProducts from '../context/useProducts';
import useLanguage from '../context/useLanguage';
import useDocumentTitle from '../hooks/useDocumentTitle';

// Generated by GitHub Copilot
/**
 * Normalizes text for accent-insensitive and case-insensitive product search.
 * @param {string} value
 * @returns {string}
 */
function normalizeSearchText(value) {
  return String(value ?? '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
}

// Generated by GitHub Copilot
/**
 * Returns true when a keyboard event target is used for typing.
 * @param {EventTarget | null} target
 * @returns {boolean}
 */
function isTypingTarget(target) {
  if (!(target instanceof HTMLElement)) {
    return false;
  }

  const tag = target.tagName;
  return target.isContentEditable || tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT';
}

/**
 * Product administration page for admin users.
 */
export default function AdminProducts() {
  const { t } = useLanguage();
  useDocumentTitle(t('adminProducts.pageTitle'));
  const { showToast, removeProductReferences } = useCart();
  const { products, addProduct, updateProduct, deleteProduct } = useProducts();

  const [search, setSearch] = useState('');
  const [editingProductId, setEditingProductId] = useState(null);
  const searchInputRef = useRef(null);
  const [formData, setFormData] = useState({
    name: '',
    price: '',
    image: '',
    category: '',
    description: '',
  });
  const [pendingDelete, setPendingDelete] = useState(null);

  useEffect(() => {
    /**
     * Focuses admin product search with slash shortcut when the user is not typing elsewhere.
     * @param {KeyboardEvent} event
     */
    const handleSlashShortcut = (event) => {
      if (event.key !== '/' || event.altKey || event.ctrlKey || event.metaKey) {
        return;
      }
      if (isTypingTarget(event.target)) {
        return;
      }

      event.preventDefault();
      searchInputRef.current?.focus();
    };

    window.addEventListener('keydown', handleSlashShortcut);
    return () => {
      window.removeEventListener('keydown', handleSlashShortcut);
    };
  }, []);

  const filteredProducts = useMemo(() => {
    const value = normalizeSearchText(search.trim());
    if (!value) {
      return products;
    }

    return products.filter((product) => (
      normalizeSearchText(product.name).includes(value)
      || normalizeSearchText(product.category).includes(value)
      || normalizeSearchText(product.description).includes(value)
    ));
  }, [products, search]);

  /** Clears the current product search and keeps keyboard focus in the field. */
  const clearSearch = () => {
    setSearch('');
    searchInputRef.current?.focus();
  };

  /**
   * Handles changes for add/edit product form.
   * @param {React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>} event
   */
  const handleFormChange = (event) => {
    const { name, value } = event.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  /** Starts editing with selected product values. */
  const startEditing = (product) => {
    setEditingProductId(product.id);
    setFormData({
      name: product.name,
      price: String(product.price),
      image: product.image,
      category: product.category,
      description: product.description,
    });
  };

  /** Resets admin form to create mode. */
  const resetAdminForm = () => {
    setEditingProductId(null);
    setFormData({ name: '', price: '', image: '', category: '', description: '' });
  };

  /**
   * Submits admin form to create or update product.
   * @param {React.FormEvent<HTMLFormElement>} event
   */
  const handleAdminSubmit = (event) => {
    event.preventDefault();

    const operation = editingProductId
      ? updateProduct(editingProductId, formData)
      : addProduct(formData);

    if (!operation.ok) {
      showToast(operation.error || t('adminProducts.saveError'), 'error');
      return;
    }

    showToast(editingProductId ? t('adminProducts.saveSuccess') : t('adminProducts.createSuccess'), 'success');
    resetAdminForm();
  };

  /** Deletes selected product after user confirmation via ConfirmDialog. */
  const handleDeleteProduct = (product) => {
    setPendingDelete(product);
  };

  /** Executes the confirmed delete. */
  const confirmDelete = () => {
    const product = pendingDelete;
    setPendingDelete(null);
    if (!product) return;

    const result = deleteProduct(product.id);
    if (!result.ok) {
      showToast(result.error || t('adminProducts.deleteError'), 'error');
      return;
    }

    removeProductReferences(product.id);
    showToast(t('adminProducts.deleteSuccess'), 'info');

    if (editingProductId === product.id) {
      resetAdminForm();
    }
  };

  return (
    <main className="max-w-6xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">{t('adminProducts.pageTitle')}</h1>
      <p className="text-gray-500 mb-6">{t('adminProducts.pageSubtitle')}</p>

      <section className="mb-8 rounded-2xl border border-indigo-200 bg-indigo-50/40 p-4" aria-label={t('adminProducts.sectionLabel')}>
        <h2 className="text-lg font-semibold text-indigo-900 mb-3">
          {editingProductId ? t('adminProducts.editProduct') : t('adminProducts.addProduct')}
        </h2>

        <form className="grid grid-cols-1 md:grid-cols-2 gap-3" onSubmit={handleAdminSubmit}>
          <label className="text-sm text-gray-700">
            {t('adminProducts.fieldName')}
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleFormChange}
              required
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>
          <label className="text-sm text-gray-700">
            {t('adminProducts.fieldPrice')}
            <input
              type="number"
              name="price"
              value={formData.price}
              onChange={handleFormChange}
              min="0"
              step="0.01"
              required
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>
          <label className="text-sm text-gray-700">
            {t('adminProducts.fieldCategory')}
            <input
              type="text"
              name="category"
              value={formData.category}
              onChange={handleFormChange}
              required
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>
          <label className="text-sm text-gray-700">
            {t('adminProducts.fieldImage')}
            <input
              type="url"
              name="image"
              value={formData.image}
              onChange={handleFormChange}
              placeholder="https://..."
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>
          {formData.image && (
            <div className="md:col-span-2 flex items-center gap-3">
              <img
                src={formData.image}
                alt={t('adminProducts.imagePreview')}
                className="h-20 w-20 rounded-xl object-cover border border-gray-200"
                onError={(e) => { e.currentTarget.style.display = 'none'; }}
              />
              <span className="text-xs text-gray-400">{t('adminProducts.imagePreview')}</span>
            </div>
          )}
          <label className="md:col-span-2 text-sm text-gray-700">
            {t('adminProducts.fieldDescription')}
            <textarea
              name="description"
              value={formData.description}
              onChange={handleFormChange}
              required
              rows={3}
              className="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </label>

          <div className="md:col-span-2 flex gap-2">
            <button
              type="submit"
              className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >
              {editingProductId ? t('adminProducts.saveChanges') : t('adminProducts.createProduct')}
            </button>
            {editingProductId && (
              <button
                type="button"
                onClick={resetAdminForm}
                className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                {t('adminProducts.cancelEdit')}
              </button>
            )}
          </div>
        </form>
      </section>

      <section className="mb-6" aria-label={t('adminProducts.searchLabel')}>
        <label className="relative block">
          <span className="sr-only">{t('adminProducts.searchLabel')}</span>
          <input
            ref={searchInputRef}
            type="search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            onKeyDown={(event) => {
              if (event.key === 'Escape' && search.trim()) {
                event.preventDefault();
                clearSearch();
              }
            }}
            placeholder={t('adminProducts.searchPlaceholder')}
            aria-describedby="admin-products-search-shortcut"
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 pr-24 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
          {search.trim() && (
            <button
              type="button"
              onClick={clearSearch}
              className="absolute right-2 top-1/2 -translate-y-1/2 rounded-lg border border-gray-300 bg-white px-2.5 py-1 text-xs font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              aria-label={t('common.clearSearch')}
            >
              {t('common.clearSearch')}
            </button>
          )}
          <p id="admin-products-search-shortcut" className="mt-1 text-xs text-gray-500">
            {t('adminProducts.searchShortcutHint')}
          </p>
        </label>
      </section>

      <p className="text-sm text-gray-500 mb-6" aria-live="polite">
        {t('adminProducts.productCount', { count: filteredProducts.length, suffix: filteredProducts.length !== 1 ? 's' : '' })}
      </p>

      <section
        aria-label={t('adminProducts.productListLabel')}
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"
      >
        {filteredProducts.map((product) => (
          <ProductCard
            key={product.id}
            product={product}
            onEditProduct={startEditing}
            onDeleteProduct={handleDeleteProduct}
          />
        ))}
      </section>

      <ConfirmDialog
        open={!!pendingDelete}
        title={t('adminProducts.deleteConfirmTitle')}
        message={pendingDelete ? t('adminProducts.deleteConfirmMessage', { name: pendingDelete.name }) : ''}
        confirmLabel={t('adminProducts.deleteConfirmButton')}
        onConfirm={confirmDelete}
        onCancel={() => setPendingDelete(null)}
        destructive
      />
    </main>
  );
}
