// Generated by GitHub Copilot
import { describe, expect, it, vi } from 'vitest';
import { buildOrderNumber, shouldBlockCheckoutSubmit } from './Checkout';

describe('checkout helpers', () => {
  it('buildOrderNumber uses first name prefix and uppercase suffix', () => {
    const randomSpy = vi.spyOn(Math, 'random').mockReturnValue(0.123456789);

    const orderNumber = buildOrderNumber('Ana Garcia');

    expect(orderNumber.startsWith('Ana-')).toBe(true);
    const [, suffix] = orderNumber.split('-');
    expect(suffix).toHaveLength(6);
    expect(/^[A-Z0-9]{6}$/.test(suffix)).toBe(true);

    randomSpy.mockRestore();
  });

  it('buildOrderNumber falls back to PEDIDO when no name provided', () => {
    const randomSpy = vi.spyOn(Math, 'random').mockReturnValue(0.987654321);

    const orderNumber = buildOrderNumber('   ');

    expect(orderNumber.startsWith('PEDIDO-')).toBe(true);
    randomSpy.mockRestore();
  });

  it('shouldBlockCheckoutSubmit blocks when cart is empty', () => {
    expect(shouldBlockCheckoutSubmit(0)).toBe(true);
    expect(shouldBlockCheckoutSubmit(-1)).toBe(true);
    expect(shouldBlockCheckoutSubmit(2)).toBe(false);
  });
});
