// Generated by GitHub Copilot
// Para que sirve: Funciones puras de apoyo para la página de Checkout.
//   buildOrderNumber genera un número de pedido legible y único a partir del nombre del cliente.
//   shouldBlockCheckoutSubmit evita enviar el formulario con el carrito vacío.
// Flujo principal: Checkout.jsx → buildOrderNumber + shouldBlockCheckoutSubmit antes de submitear.
// Dónde tocar cambios: formato del número de pedido en buildOrderNumber.

/** Generates a user-facing order number from customer name. */
export function buildOrderNumber(customerName) {
  const safePrefix = String(customerName || '').trim().split(' ')[0] || 'PEDIDO';
  const randomSuffix = Math.random().toString(36).slice(2, 8).toUpperCase();
  return `${safePrefix}-${randomSuffix}`;
}

/** Returns whether checkout submit must be blocked due to empty cart. */
export function shouldBlockCheckoutSubmit(cartLength) {
  return Number(cartLength) <= 0;
}
