// Generated by GitHub Copilot
// Para que sirve: Pagina de checkout con validaciones, envio, pago y confirmacion de pedido.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import useCart from '../context/useCart';
import useLanguage from '../context/useLanguage';
import useDocumentTitle from '../hooks/useDocumentTitle';

/* Maintenance guide:
 * - Field validation lives in validateField; update rules there first.
 * - Shipping pricing and ETA are controlled by shippingMethod, shippingFee, and estimatedDelivery.
 * - Final amount charged is payableTotal (cart total after discount + shipping).
 * - Persisted checkout draft excludes card by design for security.
 */

const CHECKOUT_STORAGE_KEY = 'tienda_react_checkout_form';
const ORDERS_STORAGE_KEY = 'tienda_react_orders';

/**
 * Maximum order history entries kept in localStorage.
 * Prevents unbounded growth of the stored payload over many purchases.
 */
const MAX_ORDERS = 50;

/**
 * Reads persisted checkout form values safely.
 * @returns {{ name: string, email: string, address: string, city: string, zip: string, card: string }}
 */
function getInitialCheckoutForm() {
  const fallback = {
    name: '',
    email: '',
    address: '',
    city: '',
    zip: '',
    card: '',
  };

  try {
    const rawForm = localStorage.getItem(CHECKOUT_STORAGE_KEY);
    if (!rawForm) {
      return fallback;
    }

    const parsed = JSON.parse(rawForm);
    return {
      ...fallback,
      ...parsed,
      // Never restore sensitive payment fields from persistent storage.
      card: '',
    };
  } catch {
    return fallback;
  }
}

/** Reads persisted shipping method safely from checkout draft. */
function getInitialShippingMethod() {
  try {
    const rawForm = localStorage.getItem(CHECKOUT_STORAGE_KEY);
    const parsed = rawForm ? JSON.parse(rawForm) : {};
    return parsed?.shippingMethod === 'express' ? 'express' : 'standard';
  } catch {
    return 'standard';
  }
}

/** Reads persisted delivery location safely from checkout draft. */
function getInitialDeliveryLocation() {
  try {
    const rawForm = localStorage.getItem(CHECKOUT_STORAGE_KEY);
    const parsed = rawForm ? JSON.parse(rawForm) : {};
    return ['home', 'store', 'other'].includes(parsed?.deliveryLocation)
      ? parsed.deliveryLocation
      : 'home';
  } catch {
    return 'home';
  }
}

/** Reads persisted shipping destination zone safely from checkout draft. */
function getInitialDestinationZone() {
  try {
    const rawForm = localStorage.getItem(CHECKOUT_STORAGE_KEY);
    const parsed = rawForm ? JSON.parse(rawForm) : {};
    const validZones = ['peninsula', 'islands_ceuta_melilla', 'europe', 'international'];
    return validZones.includes(parsed?.destinationZone) ? parsed.destinationZone : 'peninsula';
  } catch {
    return 'peninsula';
  }
}

/** Reads persisted payment method safely from checkout draft. */
function getInitialPaymentMethod() {
  try {
    const rawForm = localStorage.getItem(CHECKOUT_STORAGE_KEY);
    const parsed = rawForm ? JSON.parse(rawForm) : {};
    const validMethods = ['bizum', 'card', 'transfer', 'cash'];
    return validMethods.includes(parsed?.paymentMethod) ? parsed.paymentMethod : 'card';
  } catch {
    return 'card';
  }
}

const DESTINATION_SURCHARGES = {
  peninsula: 0,
  islands_ceuta_melilla: 5,
  europe: 10,
  international: 15,
};

/**
 * Writes JSON data to localStorage safely.
 * Keeps checkout usable when storage is unavailable or full.
 * @param {string} key
 * @param {unknown} value
 */
function safeWriteStorage(key, value) {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch {
    // Best-effort persistence only.
  }
}

/**
 * Basic Luhn validation to reduce malformed card input before submission.
 * @param {string} cardNumber
 * @returns {boolean}
 */
function isValidCardLuhn(cardNumber) {
  let sum = 0;
  let shouldDouble = false;

  for (let i = cardNumber.length - 1; i >= 0; i -= 1) {
    let digit = Number.parseInt(cardNumber[i], 10);
    if (Number.isNaN(digit)) {
      return false;
    }

    if (shouldDouble) {
      digit *= 2;
      if (digit > 9) {
        digit -= 9;
      }
    }

    sum += digit;
    shouldDouble = !shouldDouble;
  }

  return sum % 10 === 0;
}

/** Formats card digits into groups of four for readability. */
function formatCardNumber(value) {
  const digits = String(value || '').replace(/\D/g, '').slice(0, 16);
  return digits.replace(/(\d{4})(?=\d)/g, '$1 ');
}

/** Generates a stable order id with UUID when available. */
function buildOrderId() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }

  const randomSuffix = Math.random().toString(36).slice(2, 8);
  return `${Date.now()}-${randomSuffix}`;
}

/**
 * Saves a completed order to local history.
 * @param {{ name: string }} formData
 * @param {Array<{ id: number|string, name: string, quantity: number, price: number }>} items
 * @param {number} total
 */
function persistOrder(formData, items, subtotal, discountAmount, finalPrice, coupon) {
  const newOrder = {
    id: buildOrderId(),
    createdAt: new Date().toISOString(),
    customerName: formData.name.trim(),
    totalItems: items.reduce((sum, item) => sum + item.quantity, 0),
    subtotalPrice: subtotal,
    discountAmount,
    couponCode: coupon?.code ?? null,
    totalPrice: finalPrice,
    items: items.map((item) => ({
      id: item.id,
      name: item.name,
      quantity: item.quantity,
      price: item.price,
      image: item.image,
    })),
  };

  try {
    const rawOrders = localStorage.getItem(ORDERS_STORAGE_KEY);
    const currentOrders = rawOrders ? JSON.parse(rawOrders) : [];
    const safeOrders = Array.isArray(currentOrders) ? currentOrders : [];
    // Cap history at MAX_ORDERS to avoid unbounded localStorage growth.
    const trimmedOrders = [newOrder, ...safeOrders].slice(0, MAX_ORDERS);
    safeWriteStorage(ORDERS_STORAGE_KEY, trimmedOrders);
  } catch {
    safeWriteStorage(ORDERS_STORAGE_KEY, [newOrder]);
  }
}

/**
 * Reusable field used by checkout form sections.
 */
function CheckoutField({
  id,
  label,
  type = 'text',
  name,
  required = false,
  placeholder,
  autoComplete,
  inputMode,
  maxLength,
  value,
  hasError,
  errorMessage,
  onChange,
  onBlur,
}) {
  return (
    <div className="flex flex-col gap-1">
      <label htmlFor={id} className="text-sm font-medium text-gray-700">
        {label}
      </label>
      <input
        id={id}
        type={type}
        name={name}
        value={value}
        onChange={onChange}
        onBlur={onBlur}
        placeholder={placeholder}
        autoComplete={autoComplete}
        inputMode={inputMode}
        maxLength={maxLength}
        required={required}
        className={`border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 transition ${
          hasError ? 'border-red-400' : 'border-gray-300'
        }`}
        aria-invalid={hasError}
        aria-describedby={hasError ? `${id}-error` : undefined}
      />
      {hasError && (
        <span id={`${id}-error`} className="text-red-500 text-xs" role="alert">
          {errorMessage}
        </span>
      )}
    </div>
  );
}

/**
 * Checkout page with a simple order form.
 * On submission it clears the cart and redirects to a confirmation page.
 * Input validation happens on the client boundary.
 */
export default function Checkout() {
  const { t, formatCurrency, formatDateRange } = useLanguage();
  // WCAG 2.4.2: descriptive page title announced by screen readers on navigation.
  useDocumentTitle(t('checkout.title'));
  const { cart, totalPrice, discountAmount, finalPrice, coupon, dispatch, showToast } = useCart();
  const navigate = useNavigate();

  const [form, setForm] = useState(getInitialCheckoutForm);
  const [errors, setErrors] = useState({});
  const [touched, setTouched] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [shippingMethod, setShippingMethod] = useState(getInitialShippingMethod);
  const [deliveryLocation, setDeliveryLocation] = useState(getInitialDeliveryLocation);
  const [destinationZone, setDestinationZone] = useState(getInitialDestinationZone);
  const [paymentMethod, setPaymentMethod] = useState(getInitialPaymentMethod);

  const needsAddress = deliveryLocation !== 'store';
  const requiresCard = paymentMethod === 'card';
  const shippingBaseFee = needsAddress && shippingMethod === 'express' ? 4.99 : 0;
  const destinationFee = needsAddress ? (DESTINATION_SURCHARGES[destinationZone] || 0) : 0;
  const shippingFee = shippingBaseFee + destinationFee;
  const payableTotal = finalPrice + shippingFee;
  const paymentMethodLabelByKey = {
    bizum: t('checkout.paymentBizum'),
    card: t('checkout.paymentCard'),
    transfer: t('checkout.paymentTransfer'),
    cash: t('checkout.paymentCash'),
  };
  const selectedPaymentMethodLabel = paymentMethodLabelByKey[paymentMethod] || t('checkout.paymentCard');

  /** Counts how many required fields have valid values to drive progress indicator. */
  const filledFields = useMemo(() => {
    const requiredChecks = [
      !validateField('name', form.name),
      !validateField('email', form.email),
      needsAddress ? !validateField('address', form.address) : true,
      needsAddress ? !validateField('city', form.city) : true,
      needsAddress ? !validateField('zip', form.zip) : true,
      requiresCard ? !validateField('card', form.card) : true,
    ];
    return requiredChecks.filter(Boolean).length;
  }, [form, needsAddress, requiresCard]);

  const requiredFieldsCount = (needsAddress ? 5 : 2) + (requiresCard ? 1 : 0);

  const progressPercent = Math.round((filledFields / requiredFieldsCount) * 100);
  const hasVisibleErrors = Object.values(errors).some(Boolean);

  // Generated by GitHub Copilot
  /** Focuses the first invalid field after submit for keyboard and screen-reader users. */
  function focusFirstInvalidField(validationErrors) {
    const fieldOrder = ['name', 'email', ...(needsAddress ? ['address', 'city', 'zip'] : []), ...(requiresCard ? ['card'] : [])];
    const firstInvalidField = fieldOrder.find((field) => Boolean(validationErrors[field]));
    if (!firstInvalidField) {
      return;
    }

    const input = document.getElementById(firstInvalidField);
    if (input) {
      input.focus();
    }
  }

  /** Estimated delivery varies by selected shipping method. */
  const estimatedDelivery = useMemo(() => {
    const days = shippingMethod === 'express' ? { from: 1, to: 2 } : { from: 3, to: 5 };
    const from = new Date();
    from.setDate(from.getDate() + days.from);
    const to = new Date();
    to.setDate(to.getDate() + days.to);
    return formatDateRange(from, to, { day: 'numeric', month: 'short' });
  }, [formatDateRange, shippingMethod]);

  useEffect(() => {
    const persistedForm = {
      ...form,
      shippingMethod,
      deliveryLocation,
      destinationZone,
      paymentMethod,
      card: '',
    };
    safeWriteStorage(CHECKOUT_STORAGE_KEY, persistedForm);
  }, [form, shippingMethod, deliveryLocation, destinationZone, paymentMethod]);

  /** Validates one checkout field and returns an inline-friendly message. */
  function validateField(name, value) {
    if (name === 'name') {
      if (!value.trim()) return t('checkout.nameRequired');
      return undefined;
    }

    if (name === 'email') {
      if (!value.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) {
        return t('checkout.emailInvalid');
      }
      return undefined;
    }

    if (name === 'address') {
      if (!value.trim()) return t('checkout.addressRequired');
      return undefined;
    }

    if (name === 'city') {
      if (!value.trim()) return t('checkout.cityRequired');
      return undefined;
    }

    if (name === 'zip') {
      if (!value.trim() || !/^\d{4,10}$/.test(value)) {
        return t('checkout.zipInvalid');
      }
      return undefined;
    }

    if (name === 'card') {
      if (!requiresCard) {
        return undefined;
      }
      const normalizedCard = value.replace(/\s/g, '');
      if (!/^\d{16}$/.test(normalizedCard) || !isValidCardLuhn(normalizedCard)) {
        return t('checkout.cardInvalid');
      }
      return undefined;
    }

    return undefined;
  }

  const validate = () => ({
    name: validateField('name', form.name),
    email: validateField('email', form.email),
    address: needsAddress ? validateField('address', form.address) : undefined,
    city: needsAddress ? validateField('city', form.city) : undefined,
    zip: needsAddress ? validateField('zip', form.zip) : undefined,
    card: requiresCard ? validateField('card', form.card) : undefined,
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    const nextValue = name === 'card' ? formatCardNumber(value) : value;
    setForm((prev) => ({ ...prev, [name]: nextValue }));
    if (touched[name]) {
      setErrors((prev) => ({ ...prev, [name]: validateField(name, nextValue) }));
    }
  };

  /** Marks a field as touched and validates it. */
  const handleBlur = (e) => {
    const { name, value } = e.target;
    setTouched((prev) => ({ ...prev, [name]: true }));
    setErrors((prev) => ({ ...prev, [name]: validateField(name, value) }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    // Guard: prevent double-submission when the user clicks confirm twice quickly.
    if (isSubmitting) {
      return;
    }
    const validationErrors = validate();
    setTouched({
      name: true,
      email: true,
      address: needsAddress,
      city: needsAddress,
      zip: needsAddress,
      card: requiresCard,
    });
    setErrors(validationErrors);

    if (Object.values(validationErrors).some(Boolean)) {
      setErrors(validationErrors);
      focusFirstInvalidField(validationErrors);
      showToast(t('checkout.reviewFields'), 'error');
      return;
    }

    setIsSubmitting(true);
    persistOrder(form, cart, totalPrice, discountAmount, payableTotal, coupon);
    setSubmitted(true);
    dispatch({ type: 'CLEAR_CART' });
    localStorage.removeItem(CHECKOUT_STORAGE_KEY);
    showToast(t('checkout.orderConfirmed'), 'success');
    setTimeout(() => navigate('/pedidos'), 2200);
  };

  if (cart.length === 0 && !submitted) {
    return (
      <main className="max-w-xl mx-auto px-4 py-16 text-center">
        <p className="text-5xl mb-4" aria-hidden="true">🛒</p>
        <h1 className="text-2xl font-bold text-gray-800 mb-2">{t('checkout.cartEmpty')}</h1>
        <Link to="/" className="text-indigo-600 underline">{t('checkout.backToStore')}</Link>
      </main>
    );
  }

  if (submitted) {
    return (
      <main className="max-w-xl mx-auto px-4 py-20 text-center" role="status" aria-live="polite">
        <p className="text-6xl mb-4" aria-hidden="true">✔</p>
        <h1 className="text-2xl font-bold text-gray-800 mb-2">{t('checkout.confirmedTitle')}</h1>
        <p className="text-gray-500 mb-5">{t('checkout.confirmedBody')}</p>
        <Link
          to="/pedidos"
          className="inline-block rounded-xl bg-indigo-600 px-5 py-2.5 font-medium text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        >
          {t('checkout.viewOrders')}
        </Link>
      </main>
    );
  }

  return (
    <main className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-4">{t('checkout.title')}</h1>

      {/* Progress bar */}
      <div className="mb-6">
        <div className="flex justify-between text-xs text-gray-500 mb-1">
          <span>{t('checkout.completed')}</span>
          <span>{filledFields} / {requiredFieldsCount} {t('checkout.fields')}</span>
        </div>
        <div className="h-2 rounded-full bg-gray-200 overflow-hidden" role="progressbar" aria-valuenow={progressPercent} aria-valuemin={0} aria-valuemax={100} aria-label={t('checkout.formProgress')}>
          <div
            className="h-full rounded-full bg-indigo-600 transition-all duration-300"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>

      {/* Pasos visuales */}
      <div className="mb-8 flex items-center justify-between">
        {[{label: t('checkout.stepData'), num: 1}, {label: t('checkout.stepShipping'), num: 2}, {label: t('checkout.stepPayment'), num: 3}].map((step, idx) => (
          <div key={step.num} className="flex items-center flex-1">
            <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm ${idx === 0 ? 'bg-indigo-600 text-white' : 'bg-gray-200 text-gray-600'}`}>
              {step.num}
            </div>
            <p className="ml-2 text-sm font-medium text-gray-700">{step.label}</p>
            {idx < 2 && <div className="flex-1 h-0.5 ml-2 bg-gray-300" />}
          </div>
        ))}
      </div>

      <div className="flex flex-col lg:flex-row gap-8">
        {/* Form */}
        <section className="flex-1" aria-label={t('checkout.formSectionLabel')}>
          <form onSubmit={handleSubmit} noValidate aria-busy={isSubmitting} className="flex flex-col gap-5">
            {hasVisibleErrors && (
              <p className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">
                {t('checkout.fixFields')}
              </p>
            )}
            <fieldset className="flex flex-col gap-4">
              <legend className="font-semibold text-gray-800 text-base mb-1">{t('checkout.customerData')}</legend>
              <CheckoutField id="name" label={t('checkout.fullName')} name="name" required placeholder={t('checkout.namePlaceholder')} autoComplete="name" value={form.name} hasError={Boolean(touched.name && errors.name)} errorMessage={errors.name} onChange={handleChange} onBlur={handleBlur} />
              <CheckoutField id="email" label={t('common.email')} name="email" type="email" required placeholder="ana@email.com" autoComplete="email" value={form.email} hasError={Boolean(touched.email && errors.email)} errorMessage={errors.email} onChange={handleChange} onBlur={handleBlur} />
            </fieldset>

            <fieldset className="flex flex-col gap-4">
              <legend className="font-semibold text-gray-800 text-base mb-1">{t('checkout.deliveryData')}</legend>

              {/* Delivery location selector */}
              <fieldset className="rounded-xl border border-gray-200 bg-white px-3 py-3">
                <legend className="text-sm font-medium text-gray-700 px-1">{t('checkout.deliveryLocation')}</legend>
                {[
                  { value: 'home', label: t('checkout.deliveryHome'), icon: '🏠' },
                  { value: 'store', label: t('checkout.deliveryStore'), icon: '🏪' },
                  { value: 'other', label: t('checkout.deliveryOther'), icon: '📍' },
                ].map(({ value, label, icon }) => (
                  <label
                    key={value}
                    className={`mt-2 flex cursor-pointer items-center gap-3 rounded-lg border px-3 py-2 text-sm transition ${
                      deliveryLocation === value
                        ? 'border-indigo-500 bg-indigo-50'
                        : 'border-gray-200'
                    }`}
                  >
                    <span aria-hidden="true">{icon}</span>
                    <span className="flex-1">{label}</span>
                    <input
                      type="radio"
                      name="deliveryLocation"
                      value={value}
                      checked={deliveryLocation === value}
                      onChange={() => setDeliveryLocation(value)}
                      className="ml-1"
                      aria-label={label}
                    />
                  </label>
                ))}
              </fieldset>

              {deliveryLocation === 'store' ? (
                <p className="rounded-lg border border-indigo-100 bg-indigo-50 px-3 py-2 text-sm text-indigo-700">
                  {t('checkout.deliveryStoreNote')}
                </p>
              ) : (
                <>
                  <CheckoutField id="address" label={t('checkout.streetAndNumber')} name="address" required placeholder={t('checkout.addressPlaceholder')} autoComplete="street-address" value={form.address} hasError={Boolean(touched.address && errors.address)} errorMessage={errors.address} onChange={handleChange} onBlur={handleBlur} />
                  <div className="grid grid-cols-2 gap-4">
                    <CheckoutField id="city" label={t('checkout.city')} name="city" required placeholder={t('checkout.cityPlaceholder')} autoComplete="address-level2" value={form.city} hasError={Boolean(touched.city && errors.city)} errorMessage={errors.city} onChange={handleChange} onBlur={handleBlur} />
                    <CheckoutField id="zip" label={t('checkout.zip')} name="zip" required placeholder="1425" autoComplete="postal-code" value={form.zip} hasError={Boolean(touched.zip && errors.zip)} errorMessage={errors.zip} onChange={handleChange} onBlur={handleBlur} />
                  </div>

                  <fieldset className="rounded-xl border border-gray-200 bg-white px-3 py-3">
                    <legend className="text-sm font-medium text-gray-700 px-1">{t('checkout.destinationZone')}</legend>
                    <p className="text-xs text-gray-500 mb-2">{t('checkout.destinationZoneHelp')}</p>
                    {[
                      { value: 'peninsula', label: t('checkout.zonePeninsula'), fee: 0 },
                      { value: 'islands_ceuta_melilla', label: t('checkout.zoneIslandsCeutaMelilla'), fee: 5 },
                      { value: 'europe', label: t('checkout.zoneEurope'), fee: 10 },
                      { value: 'international', label: t('checkout.zoneInternational'), fee: 15 },
                    ].map(({ value, label, fee }) => (
                      <label
                        key={value}
                        className={`mt-2 flex cursor-pointer items-center justify-between rounded-lg border px-3 py-2 text-sm transition ${
                          destinationZone === value
                            ? 'border-indigo-500 bg-indigo-50'
                            : 'border-gray-200'
                        }`}
                      >
                        <span>{label}</span>
                        <span className="font-semibold text-gray-800">
                          {fee === 0 ? t('common.free') : `+${formatCurrency(fee)}`}
                        </span>
                        <input
                          type="radio"
                          name="destinationZone"
                          value={value}
                          checked={destinationZone === value}
                          onChange={(event) => setDestinationZone(event.target.value)}
                          className="ml-3"
                          aria-label={label}
                        />
                      </label>
                    ))}
                  </fieldset>
                </>
              )}

              {needsAddress && (
                <fieldset className="rounded-xl border border-gray-200 bg-white px-3 py-3">
                  <legend className="text-sm font-medium text-gray-700 px-1">{t('checkout.shippingMethod')}</legend>
                  <label className="mt-1 flex cursor-pointer items-center justify-between rounded-lg border border-gray-200 px-3 py-2 text-sm">
                    <span>{t('checkout.standardShipping')}</span>
                    <span className="font-semibold text-emerald-700">{t('common.free')}</span>
                    <input
                      type="radio"
                      name="shippingMethod"
                      value="standard"
                      checked={shippingMethod === 'standard'}
                      onChange={(event) => setShippingMethod(event.target.value)}
                      className="ml-3"
                    />
                  </label>
                  <label className="mt-2 flex cursor-pointer items-center justify-between rounded-lg border border-gray-200 px-3 py-2 text-sm">
                    <span>{t('checkout.expressShipping')}</span>
                    <span className="font-semibold text-gray-900">{formatCurrency(4.99)}</span>
                    <input
                      type="radio"
                      name="shippingMethod"
                      value="express"
                      checked={shippingMethod === 'express'}
                      onChange={(event) => setShippingMethod(event.target.value)}
                      className="ml-3"
                    />
                  </label>
                </fieldset>
              )}
            </fieldset>

            <fieldset className="flex flex-col gap-4">
              <legend className="font-semibold text-gray-800 text-base mb-1">{t('checkout.paymentData')}</legend>
              <fieldset className="rounded-xl border border-gray-200 bg-white px-3 py-3">
                <legend className="text-sm font-medium text-gray-700 px-1">{t('checkout.paymentMethod')}</legend>
                {[
                  { value: 'bizum', label: t('checkout.paymentBizum') },
                  { value: 'card', label: t('checkout.paymentCard') },
                  { value: 'transfer', label: t('checkout.paymentTransfer') },
                  { value: 'cash', label: t('checkout.paymentCash') },
                ].map(({ value, label }) => (
                  <label
                    key={value}
                    className={`mt-2 flex cursor-pointer items-center rounded-lg border px-3 py-2 text-sm transition ${
                      paymentMethod === value
                        ? 'border-indigo-500 bg-indigo-50'
                        : 'border-gray-200'
                    }`}
                  >
                    <span className="flex-1">{label}</span>
                    <input
                      type="radio"
                      name="paymentMethod"
                      value={value}
                      checked={paymentMethod === value}
                      onChange={(event) => setPaymentMethod(event.target.value)}
                      className="ml-3"
                      aria-label={label}
                    />
                  </label>
                ))}
              </fieldset>

              {requiresCard && (
                <CheckoutField
                  id="card"
                  label={t('checkout.card')}
                  name="card"
                  placeholder="1234 5678 9012 3456"
                  autoComplete="cc-number"
                  inputMode="numeric"
                  maxLength={19}
                  required
                  value={form.card}
                  hasError={Boolean(touched.card && errors.card)}
                  errorMessage={errors.card}
                  onChange={handleChange}
                  onBlur={handleBlur}
                />
              )}
            </fieldset>

            <button
              type="submit"
              disabled={isSubmitting}
              className="mt-2 bg-indigo-600 hover:bg-indigo-700 active:scale-95 text-white font-semibold px-4 py-3 rounded-xl transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:opacity-70 disabled:cursor-not-allowed"
            >
              {isSubmitting ? t('checkout.payNowSubmitting') : `${t('checkout.payNow')} - ${formatCurrency(payableTotal)}`}
            </button>
          </form>
        </section>

        {/* Order summary */}
        <aside className="lg:w-72" aria-label={t('checkout.summaryLabel')}>
          <div className="bg-white rounded-2xl shadow p-6 sticky top-24">
            <h2 className="font-bold text-gray-800 text-base mb-4">{t('checkout.yourOrder')}</h2>
            <ul className="flex flex-col gap-3 mb-4" role="list">
              {cart.map((item) => (
                <li key={item.id} className="flex items-center gap-3">
                  <img
                    src={item.image}
                    alt={item.name}
                    className="w-12 h-12 rounded-lg object-cover shrink-0"
                  />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-gray-800 truncate">{item.name}</p>
                    <p className="text-xs text-gray-500">x{item.quantity}</p>
                  </div>
                  <span className="text-sm font-semibold text-gray-900">
                    {formatCurrency(item.price * item.quantity)}
                  </span>
                </li>
              ))}
            </ul>
            <dl className="flex flex-col gap-1 text-sm text-gray-600 border-t pt-3">
              <div className="flex justify-between">
                <dt>{t('checkout.paymentMethod')}</dt>
                <dd className="font-medium">{selectedPaymentMethodLabel}</dd>
              </div>
              <div className="flex justify-between">
                <dt>{t('common.subtotal')}</dt>
                <dd className="font-medium">{formatCurrency(totalPrice)}</dd>
              </div>
              {discountAmount > 0 && (
                <div className="flex justify-between">
                  <dt className="text-green-700">{t('common.discount')} ({coupon?.code})</dt>
                  <dd className="font-medium text-green-700">-{formatCurrency(discountAmount)}</dd>
                </div>
              )}
              <div className="flex justify-between">
                <dt>{t('common.shipping')}</dt>
                <dd className="font-medium">
                  {shippingBaseFee === 0 ? <span className="text-green-600">{t('common.free')}</span> : formatCurrency(shippingBaseFee)}
                </dd>
              </div>
              {destinationFee > 0 && (
                <div className="flex justify-between">
                  <dt>{t('checkout.destinationSurcharge')}</dt>
                  <dd className="font-medium">+{formatCurrency(destinationFee)}</dd>
                </div>
              )}
            </dl>
            <div className="mt-2 flex justify-between font-bold text-gray-900">
              <span>{t('common.total')}</span>
              <span>{formatCurrency(payableTotal)}</span>
            </div>
            <p className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700 font-medium">
              {t('checkout.estimatedDelivery')}: {estimatedDelivery}
            </p>
          </div>
        </aside>
      </div>
    </main>
  );
}
