// Generated by GitHub Copilot
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import useCart from '../context/useCart';
import useProducts from '../context/useProducts';
import useLanguage from '../context/useLanguage';
import useDocumentTitle from '../hooks/useDocumentTitle';

/**
 * Favorites page that renders products saved by the signed-in client.
 * Accessibility: uses semantic headings and announces empty state clearly.
 */
export default function Favorites() {
	const { t, formatCurrency, translateCategory, translateProductText } = useLanguage();
	// WCAG 2.4.2: descriptive page title announced by screen readers on navigation.
	useDocumentTitle(t('navbar.favorites'));
	const { favorites, toggleFavorite, clearFavorites, restoreFavorites } = useCart();
	const { products } = useProducts();
	const [removedSnapshot, setRemovedSnapshot] = useState([]);

	const favoriteProducts = useMemo(() => {
		if (!Array.isArray(favorites) || favorites.length === 0) {
			return [];
		}

		const idSet = new Set(favorites);
		return products.filter((product) => idSet.has(product.id));
	}, [favorites, products]);

	/** Saves current favorites, clears them and enables one-click restore. */
	const handleClearAll = () => {
		setRemovedSnapshot([...favorites]);
		clearFavorites();
	};

	/** Restores the latest removed favorites snapshot if it exists. */
	const handleUndoClear = () => {
		if (removedSnapshot.length === 0) {
			return;
		}

		restoreFavorites(removedSnapshot);
		setRemovedSnapshot([]);
	};

	return (
		<main className="max-w-6xl mx-auto px-4 py-6" aria-labelledby="favorites-heading">
			<header className="mb-6 flex flex-wrap items-center justify-between gap-3">
				<div>
					<h1 id="favorites-heading" className="text-2xl font-bold text-gray-900">{t('favorites.title')}</h1>
					<p className="text-sm text-gray-600">
						{favoriteProducts.length === 0
							? t('favorites.noneSaved')
							: t('favorites.savedCount', {
								count: favoriteProducts.length,
								suffixProducts: favoriteProducts.length !== 1 ? 's' : '',
								suffixSaved: favoriteProducts.length !== 1 ? 's' : '',
							})}
					</p>
				</div>

				<div className="flex items-center gap-2">
					<button
						type="button"
						onClick={handleUndoClear}
						disabled={removedSnapshot.length === 0}
						className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
					>
						{t('favorites.undoClear')}
					</button>
					<button
						type="button"
						onClick={handleClearAll}
						disabled={favoriteProducts.length === 0}
						className="rounded-lg border border-rose-300 bg-rose-50 px-3 py-2 text-sm font-medium text-rose-700 transition hover:bg-rose-100 disabled:cursor-not-allowed disabled:opacity-50"
					>
						{t('favorites.clearAll')}
					</button>
				</div>
			</header>

			{favoriteProducts.length === 0 ? (
				<section className="rounded-2xl border border-dashed border-gray-300 bg-white p-8 text-center">
					<h2 className="text-lg font-semibold text-gray-800">{t('favorites.emptyTitle')}</h2>
					<p className="mt-2 text-sm text-gray-600">{t('favorites.emptyBody')}</p>
					<Link
						to="/"
						className="mt-5 inline-flex rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700"
					>
						{t('favorites.goCatalog')}
					</Link>
				</section>
			) : (
				<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
					{favoriteProducts.map((product) => (
						<article key={product.id} className="rounded-2xl bg-white p-4 shadow">
							<img
								src={product.image}
								alt={product.name}
								className="h-40 w-full rounded-xl object-cover"
								loading="lazy"
								decoding="async"
							/>
							<div className="mt-3">
								<p className="text-xs font-medium uppercase tracking-wide text-indigo-600">{translateCategory(product.category)}</p>
								<h2 className="mt-1 text-base font-semibold text-gray-900">{translateProductText(product.name)}</h2>
								<p className="mt-1 text-sm text-gray-600">{translateProductText(product.description)}</p>
								<p className="mt-2 text-lg font-bold text-gray-900">{formatCurrency(product.price)}</p>
							</div>
							<div className="mt-4 flex gap-2">
								<Link
									to={`/producto/${product.id}`}
									className="flex-1 rounded-lg border border-gray-300 bg-white px-3 py-2 text-center text-sm font-medium text-gray-700 transition hover:bg-gray-50"
								>
									{t('favorites.viewDetail')}
								</Link>
								<button
									type="button"
									onClick={() => toggleFavorite(product)}
									className="rounded-lg border border-rose-300 bg-rose-50 px-3 py-2 text-sm font-medium text-rose-700 transition hover:bg-rose-100"
									aria-label={t('productCard.removeFavorite', { name: translateProductText(product.name) })}
								>
									{t('common.remove')}
								</button>
							</div>
						</article>
					))}
				</section>
			)}
		</main>
	);
}
