// Generated by GitHub Copilot
import '@testing-library/jest-dom/vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import Favorites from './Favorites';

const mockToggleFavorite = vi.fn();
const mockClearFavorites = vi.fn();
const mockRestoreFavorites = vi.fn();

const MOCK_PRODUCT = {
  id: 1,
  name: 'Auriculares Bluetooth',
  price: 59.99,
  image: 'https://images.unsplash.com/photo-test?w=400',
  category: 'Electronica',
  description: 'Auriculares inalámbricos.',
};

const MOCK_PRODUCT_2 = {
  id: 2,
  name: 'Smartwatch Deportivo',
  price: 129.99,
  image: 'https://images.unsplash.com/photo-test-2?w=400',
  category: 'Electronica',
  description: 'Reloj inteligente con GPS.',
};

let mockFavorites = [];

vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom');
  return {
    ...actual,
    Link: ({ children, to, ...props }) => <a href={to} {...props}>{children}</a>,
  };
});

vi.mock('../context/useCart', () => ({
  default: () => ({
    favorites: mockFavorites,
    toggleFavorite: mockToggleFavorite,
    clearFavorites: mockClearFavorites,
    restoreFavorites: mockRestoreFavorites,
  }),
}));

vi.mock('../context/useProducts', () => ({
  default: () => ({ products: [MOCK_PRODUCT, MOCK_PRODUCT_2] }),
}));

vi.mock('../hooks/useDocumentTitle', () => ({
  default: () => undefined,
}));

vi.mock('../context/useLanguage', () => ({
  default: () => ({
    t: (key, vars) => {
      const map = {
        'navbar.favorites': 'Favoritos',
        'favorites.title': 'Favoritos',
        'favorites.noneSaved': 'No tienes productos guardados.',
        'favorites.savedCount': `${vars?.count ?? 0} producto${vars?.suffixProducts ?? 's'} guardado${vars?.suffixSaved ?? 's'}`,
        'favorites.undoClear': 'Deshacer',
        'favorites.clearAll': 'Borrar favoritos',
        'favorites.emptyTitle': 'Tu lista está vacía',
        'favorites.emptyBody': 'Guarda productos del catálogo para verlos aquí.',
        'favorites.goCatalog': 'Ir al catálogo',
        'favorites.viewDetail': 'Ver detalle',
        'favorites.removeAria': `Quitar de favoritos: ${vars?.name ?? ''}`,
        'productCard.removeFavorite': `Quitar de favoritos: ${vars?.name ?? ''}`,
        'common.remove': 'Eliminar',
      };
      return map[key] ?? key;
    },
    formatCurrency: (v) => `$${v.toFixed(2)}`,
    translateCategory: (c) => c,
    translateProductText: (text) => text,
  }),
}));

afterEach(() => {
  cleanup();
  mockToggleFavorite.mockClear();
  mockClearFavorites.mockClear();
  mockRestoreFavorites.mockClear();
  mockFavorites = [];
});

describe('Favorites integration', () => {
  it('renders empty state with heading, message and catalog link', () => {
    render(<Favorites />);

    expect(screen.getByRole('heading', { level: 2, name: 'Tu lista está vacía' })).toBeInTheDocument();
    expect(screen.getByText('Guarda productos del catálogo para verlos aquí.')).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Ir al catálogo' })).toHaveAttribute('href', '/');
  });

  it('clear all and undo buttons are disabled when no favorites', () => {
    render(<Favorites />);

    expect(screen.getByRole('button', { name: 'Borrar favoritos' })).toBeDisabled();
    expect(screen.getByRole('button', { name: 'Deshacer' })).toBeDisabled();
  });

  it('renders favorite product with remove button having accessible aria-label', () => {
    mockFavorites = [1];
    render(<Favorites />);

    expect(screen.getByRole('heading', { level: 2, name: 'Auriculares Bluetooth' })).toBeInTheDocument();
    expect(
      screen.getByRole('button', { name: 'Quitar de favoritos: Auriculares Bluetooth' }),
    ).toBeInTheDocument();
  });

  it('clear all calls clearFavorites and enables undo button', async () => {
    mockFavorites = [1];
    const user = userEvent.setup();
    render(<Favorites />);

    await user.click(screen.getByRole('button', { name: 'Borrar favoritos' }));

    expect(mockClearFavorites).toHaveBeenCalledOnce();
    // After clearing, undo snapshot is non-empty so undo should be enabled
    const undoButton = screen.getByRole('button', { name: 'Deshacer' });
    expect(undoButton).not.toBeDisabled();
    expect(undoButton).toHaveFocus();
  });

  it('undo button calls restoreFavorites with snapshot after clear', async () => {
    mockFavorites = [1];
    const user = userEvent.setup();
    render(<Favorites />);

    await user.click(screen.getByRole('button', { name: 'Borrar favoritos' }));
    await user.click(screen.getByRole('button', { name: 'Deshacer' }));

    expect(mockRestoreFavorites).toHaveBeenCalledWith([1]);
  });

  it('moves focus to next remove button after removing one favorite', async () => {
    mockFavorites = [1, 2];
    const user = userEvent.setup();
    const { rerender } = render(<Favorites />);

    const firstRemoveButton = screen.getByRole('button', { name: 'Quitar de favoritos: Auriculares Bluetooth' });
    await user.click(firstRemoveButton);

    mockFavorites = [2];
    rerender(<Favorites />);

    expect(screen.getByRole('button', { name: 'Quitar de favoritos: Smartwatch Deportivo' })).toHaveFocus();
  });

  it('moves focus to empty-state heading when last favorite is removed', async () => {
    mockFavorites = [1];
    const user = userEvent.setup();
    const { rerender } = render(<Favorites />);

    await user.click(screen.getByRole('button', { name: 'Quitar de favoritos: Auriculares Bluetooth' }));

    mockFavorites = [];
    rerender(<Favorites />);

    expect(screen.getByRole('heading', { name: 'Tu lista está vacía' })).toHaveFocus();
  });
});
