// Generated by GitHub Copilot
import { useMemo, useRef } from 'react';
import { Link } from 'react-router-dom';
import useCart from '../context/useCart';
import useProducts from '../context/useProducts';

/**
 * Favorites page that renders products saved by the signed-in client.
 * Accessibility: uses semantic headings and announces empty state clearly.
 */
export default function Favorites() {
	const { favorites, toggleFavorite, clearFavorites, restoreFavorites } = useCart();
	const { products } = useProducts();
	const removedSnapshotRef = useRef([]);

	const favoriteProducts = useMemo(() => {
		if (!Array.isArray(favorites) || favorites.length === 0) {
			return [];
		}

		const idSet = new Set(favorites);
		return products.filter((product) => idSet.has(product.id));
	}, [favorites, products]);

	/** Saves current favorites, clears them and enables one-click restore. */
	const handleClearAll = () => {
		removedSnapshotRef.current = [...favorites];
		clearFavorites();
	};

	/** Restores the latest removed favorites snapshot if it exists. */
	const handleUndoClear = () => {
		if (removedSnapshotRef.current.length === 0) {
			return;
		}

		restoreFavorites(removedSnapshotRef.current);
		removedSnapshotRef.current = [];
	};

	return (
		<main className="max-w-6xl mx-auto px-4 py-6" aria-labelledby="favorites-heading">
			<header className="mb-6 flex flex-wrap items-center justify-between gap-3">
				<div>
					<h1 id="favorites-heading" className="text-2xl font-bold text-gray-900">Favoritos</h1>
					<p className="text-sm text-gray-600">
						{favoriteProducts.length === 0
							? 'No tienes productos guardados.'
							: `${favoriteProducts.length} producto${favoriteProducts.length !== 1 ? 's' : ''} guardado${favoriteProducts.length !== 1 ? 's' : ''}`}
					</p>
				</div>

				<div className="flex items-center gap-2">
					<button
						type="button"
						onClick={handleUndoClear}
						disabled={removedSnapshotRef.current.length === 0}
						className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
					>
						Deshacer vaciado
					</button>
					<button
						type="button"
						onClick={handleClearAll}
						disabled={favoriteProducts.length === 0}
						className="rounded-lg border border-rose-300 bg-rose-50 px-3 py-2 text-sm font-medium text-rose-700 transition hover:bg-rose-100 disabled:cursor-not-allowed disabled:opacity-50"
					>
						Vaciar favoritos
					</button>
				</div>
			</header>

			{favoriteProducts.length === 0 ? (
				<section className="rounded-2xl border border-dashed border-gray-300 bg-white p-8 text-center">
					<h2 className="text-lg font-semibold text-gray-800">Tu lista estÃ¡ vacÃ­a</h2>
					<p className="mt-2 text-sm text-gray-600">Guarda productos desde el catÃ¡logo para verlos aquÃ­.</p>
					<Link
						to="/"
						className="mt-5 inline-flex rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700"
					>
						Ir al catÃ¡logo
					</Link>
				</section>
			) : (
				<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
					{favoriteProducts.map((product) => (
						<article key={product.id} className="rounded-2xl bg-white p-4 shadow">
							<img
								src={product.image}
								alt={product.name}
								className="h-40 w-full rounded-xl object-cover"
								loading="lazy"
								decoding="async"
							/>
							<div className="mt-3">
								<p className="text-xs font-medium uppercase tracking-wide text-indigo-600">{product.category}</p>
								<h2 className="mt-1 text-base font-semibold text-gray-900">{product.name}</h2>
								<p className="mt-1 text-sm text-gray-600">{product.description}</p>
								<p className="mt-2 text-lg font-bold text-gray-900">${product.price.toFixed(2)}</p>
							</div>
							<div className="mt-4 flex gap-2">
								<Link
									to={`/producto/${product.id}`}
									className="flex-1 rounded-lg border border-gray-300 bg-white px-3 py-2 text-center text-sm font-medium text-gray-700 transition hover:bg-gray-50"
								>
									Ver detalle
								</Link>
								<button
									type="button"
									onClick={() => toggleFavorite(product)}
									className="rounded-lg border border-rose-300 bg-rose-50 px-3 py-2 text-sm font-medium text-rose-700 transition hover:bg-rose-100"
									aria-label={`Quitar de favoritos: ${product.name}`}
								>
									Quitar
								</button>
							</div>
						</article>
					))}
				</section>
			)}
		</main>
	);
}
