// Generated by GitHub Copilot
// Para que sirve: Pagina para restablecer contrasena de usuario.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useEffect, useRef, useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import useAuth from '../context/useAuth';
import useCart from '../context/useCart';
import useLanguage from '../context/useLanguage';
import useDocumentTitle from '../hooks/useDocumentTitle';

/**
 * Simulated password recovery page using local user storage.
 */
export default function ForgotPassword() {
  const { t } = useLanguage();
  // WCAG 2.4.2: descriptive page title announced by screen readers on navigation.
  useDocumentTitle(t('forgot.title'));
  const { isAuthenticated, resetPassword } = useAuth();
  const { showToast } = useCart();
  const navigate = useNavigate();

  const [form, setForm] = useState({
    email: '',
    password: '',
    confirmPassword: '',
  });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [fieldErrors, setFieldErrors] = useState({});
  const [touched, setTouched] = useState({});
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const emailInputRef = useRef(null);
  const passwordInputRef = useRef(null);
  const confirmPasswordInputRef = useRef(null);
  const errorMessageRef = useRef(null);
  const successMessageRef = useRef(null);

  /**
   * Calculates password strength on a 0-4 scale with specific feedback tips.
   * @param {string} pwd
   * @returns {{ score: number, label: string, color: string, tips: string[] }}
   */
  const getPasswordStrength = (pwd) => {
    if (!pwd) return { score: 0, label: '', color: '', tips: [] };
    let score = 0;
    const tips = [];
    
    // Check each requirement and add specific feedback
    if (pwd.length >= 8) {
      score += 1;
    } else {
      tips.push(t('common.tipMinChars', { min: 8, current: pwd.length }));
    }
    
    if (/[a-z]/.test(pwd)) {
      score += 1;
    } else {
      tips.push(t('common.tipLower'));
    }
    
    if (/[A-Z]/.test(pwd)) {
      score += 1;
    } else {
      tips.push(t('common.tipUpper'));
    }
    
    if (/\d/.test(pwd)) {
      score += 1;
    } else {
      tips.push(t('common.tipNumber'));
    }
    
    const labels = ['', t('common.strengthWeak'), t('common.strengthRegular'), t('common.strengthGood'), t('common.strengthStrong')];
    const colors = ['', 'bg-red-400', 'bg-orange-400', 'bg-yellow-400', 'bg-green-500'];
    return { score, label: labels[score], color: colors[score], tips };
  };

  const passwordStrength = getPasswordStrength(form.password);

  /** Returns an inline validation error message for one recovery field. */
  const validateField = (name, value, nextForm = form) => {
    if (name === 'email') {
      const safeEmail = value.trim();
      if (!safeEmail) return t('common.requiredEmail');
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(safeEmail)) return t('common.invalidEmail');
      return undefined;
    }

    if (name === 'password') {
      if (!value) return t('forgot.newPasswordRequired');
      if (!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/.test(value)) {
        return t('common.strongPasswordHint');
      }
      return undefined;
    }

    if (name === 'confirmPassword') {
      if (!value) return t('common.confirmPasswordRequired');
      if (value !== nextForm.password) return t('common.passwordsMismatch');
      return undefined;
    }

    return undefined;
  };

  /** Updates one input and validates it in real time once touched. */
  const handleInputChange = (name, value) => {
    const nextForm = { ...form, [name]: value };
    setForm(nextForm);

    if (touched[name] || (name === 'password' && touched.confirmPassword)) {
      setFieldErrors((prev) => ({
        ...prev,
        [name]: validateField(name, value, nextForm),
        ...(name === 'password' && touched.confirmPassword
          ? { confirmPassword: validateField('confirmPassword', nextForm.confirmPassword, nextForm) }
          : {}),
      }));
    }

    if (error) setError('');
    if (success) setSuccess('');
  };

  /** Marks one input as touched and validates it. */
  const handleBlur = (name) => {
    setTouched((prev) => ({ ...prev, [name]: true }));
    setFieldErrors((prev) => ({ ...prev, [name]: validateField(name, form[name], form) }));
  };

  useEffect(() => {
    if (!submitAttempted) {
      return;
    }

    if (fieldErrors.email) {
      emailInputRef.current?.focus();
      return;
    }

    if (fieldErrors.password) {
      passwordInputRef.current?.focus();
      return;
    }

    if (fieldErrors.confirmPassword) {
      confirmPasswordInputRef.current?.focus();
    }
  }, [fieldErrors, submitAttempted]);

  useEffect(() => {
    if (submitAttempted && error) {
      errorMessageRef.current?.focus();
    }
  }, [error, submitAttempted]);

  useEffect(() => {
    if (success) {
      successMessageRef.current?.focus();
    }
  }, [success]);

  /** Handles password reset and returns user to login on success. */
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (isSubmitting) {
      return;
    }

    setSubmitAttempted(true);

    const nextErrors = {
      email: validateField('email', form.email, form),
      password: validateField('password', form.password, form),
      confirmPassword: validateField('confirmPassword', form.confirmPassword, form),
    };

    setTouched({ email: true, password: true, confirmPassword: true });
    setFieldErrors(nextErrors);

    if (Object.values(nextErrors).some(Boolean)) {
      return;
    }

    setIsSubmitting(true);
    const result = await resetPassword(form);

    if (!result.ok) {
      const message = result.error || t('forgot.resetFailed');
      setSuccess('');
      setError(message);
      showToast(message, 'error');
      setIsSubmitting(false);
      return;
    }

    setSubmitAttempted(false);
    setError('');
    setSuccess(t('forgot.resetSuccessRedirect'));
    showToast(t('forgot.resetSuccess'), 'success');
    setTimeout(() => navigate('/login', { replace: true }), 1200);
  };

  if (isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  return (
    <main className="min-h-[calc(100vh-4rem)] flex items-center justify-center px-4 py-10 bg-gray-50">
      <section className="w-full max-w-md rounded-2xl bg-white p-6 shadow" aria-label={t('forgot.formLabel')}>
        <h1 className="text-2xl font-bold text-gray-900 mb-2">{t('forgot.title')}</h1>
        <p className="text-sm text-gray-500 mb-6">{t('forgot.subtitle')}</p>

        <form onSubmit={handleSubmit} className="flex flex-col gap-4" noValidate>
          <div className="flex flex-col gap-1">
            <label htmlFor="email" className="text-sm font-medium text-gray-700">{t('common.email')}</label>
            <input
              ref={emailInputRef}
              id="email"
              type="email"
              name="email"
              autoComplete="email"
              value={form.email}
              onChange={(e) => handleInputChange('email', e.target.value)}
              onBlur={() => handleBlur('email')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.email && fieldErrors.email ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              aria-invalid={Boolean(touched.email && fieldErrors.email)}
              aria-describedby={touched.email && fieldErrors.email ? 'forgot-email-error' : undefined}
              required
            />
            {touched.email && fieldErrors.email && (
              <p id="forgot-email-error" className="text-xs text-red-600" role="alert">{fieldErrors.email}</p>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="password" className="text-sm font-medium text-gray-700">{t('forgot.newPassword')}</label>
            <input
              ref={passwordInputRef}
              id="password"
              type={showPassword ? 'text' : 'password'}
              name="password"
              autoComplete="new-password"
              value={form.password}
              onChange={(e) => handleInputChange('password', e.target.value)}
              onBlur={() => handleBlur('password')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.password && fieldErrors.password ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              minLength={8}
              pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}"
              title={t('common.minPasswordTitle')}
              aria-invalid={Boolean(touched.password && fieldErrors.password)}
              aria-describedby={[
                touched.password && fieldErrors.password ? 'forgot-password-error' : null,
                form.password ? 'forgot-password-strength' : null,
              ].filter(Boolean).join(' ') || undefined}
              required
            />
            <button
              type="button"
              onClick={() => setShowPassword((prev) => !prev)}
              className="mt-1 text-xs text-indigo-600 hover:text-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 w-fit"
              aria-label={showPassword ? t('common.hidePassword') : t('common.showPassword')}
            >
              {showPassword ? t('common.hidePassword') : t('common.showPassword')}
            </button>
            {form.password && (
              <div id="forgot-password-strength" role="status" className="mt-1">
                <div className="flex gap-1 mb-1" aria-hidden="true">
                  {[1, 2, 3, 4].map((step) => (
                    <div
                      key={step}
                      className={`h-1.5 flex-1 rounded-full transition-colors ${
                        step <= passwordStrength.score ? passwordStrength.color : 'bg-gray-200'
                      }`}
                    />
                  ))}
                </div>
                <p className="text-xs text-gray-500">
                  {t('common.passwordStrength')}: <span className="font-medium">{passwordStrength.label}</span>
                </p>
                {passwordStrength.tips && passwordStrength.tips.length > 0 && (
                  <ul className="mt-1 space-y-0.5" role="list">
                    {passwordStrength.tips.map((tip) => (
                      <li key={tip} className="text-xs text-amber-700 flex items-center gap-1">
                        <span className="text-amber-600">✗</span> {tip}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            )}
            {touched.password && fieldErrors.password && (
              <p id="forgot-password-error" className="text-xs text-red-600" role="alert">{fieldErrors.password}</p>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="confirmPassword" className="text-sm font-medium text-gray-700">{t('common.confirmPassword')}</label>
            <input
              ref={confirmPasswordInputRef}
              id="confirmPassword"
              type={showConfirmPassword ? 'text' : 'password'}
              name="confirmPassword"
              autoComplete="new-password"
              value={form.confirmPassword}
              onChange={(e) => handleInputChange('confirmPassword', e.target.value)}
              onBlur={() => handleBlur('confirmPassword')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.confirmPassword && fieldErrors.confirmPassword ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              minLength={8}
              aria-invalid={Boolean(touched.confirmPassword && fieldErrors.confirmPassword)}
              aria-describedby={touched.confirmPassword && fieldErrors.confirmPassword ? 'forgot-confirm-password-error' : undefined}
              required
            />
            <button
              type="button"
              onClick={() => setShowConfirmPassword((prev) => !prev)}
              className="mt-1 text-xs text-indigo-600 hover:text-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 w-fit"
              aria-label={showConfirmPassword ? t('common.hideConfirmation') : t('common.showConfirmation')}
            >
              {showConfirmPassword ? t('common.hideConfirmation') : t('common.showConfirmation')}
            </button>
            {touched.confirmPassword && fieldErrors.confirmPassword && (
              <p id="forgot-confirm-password-error" className="text-xs text-red-600" role="alert">{fieldErrors.confirmPassword}</p>
            )}
          </div>

          {error && <p ref={errorMessageRef} className="text-sm text-red-600" role="alert" tabIndex={-1}>{error}</p>}
          {success && <p ref={successMessageRef} className="text-sm text-emerald-700" role="status" tabIndex={-1}>{success}</p>}

          <button
            type="submit"
            disabled={isSubmitting}
            className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            {isSubmitting ? t('forgot.updating') : t('forgot.updatePassword')}
          </button>
        </form>

        <p className="mt-5 text-sm text-gray-600">
          {t('forgot.rememberedAccess')}{' '}
          <Link
            to="/login"
            className="font-medium text-indigo-600 underline underline-offset-2 hover:text-indigo-700"
          >
            {t('forgot.backToLogin')}
          </Link>
        </p>
      </section>
    </main>
  );
}
