// Generated by GitHub Copilot
import '@testing-library/jest-dom/vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import ForgotPassword from './ForgotPassword';

const mockNavigate = vi.fn();
const mockShowToast = vi.fn();
const mockResetPassword = vi.fn();

let mockAuth = {
  isAuthenticated: false,
  resetPassword: mockResetPassword,
};

vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom');
  return {
    ...actual,
    Link: ({ children, to, ...props }) => <a href={to} {...props}>{children}</a>,
    Navigate: ({ to }) => <div data-testid="navigate">{to}</div>,
    useNavigate: () => mockNavigate,
  };
});

vi.mock('../context/useAuth', () => ({
  default: () => mockAuth,
}));

vi.mock('../context/useCart', () => ({
  default: () => ({ showToast: mockShowToast }),
}));

vi.mock('../hooks/useDocumentTitle', () => ({
  default: () => undefined,
}));

vi.mock('../context/useLanguage', () => ({
  default: () => ({
    t: (key) => {
      const map = {
        'forgot.title': 'Recuperar contraseña',
        'forgot.subtitle': 'Ingresa tu correo y una nueva contraseña.',
        'forgot.formLabel': 'Formulario de recuperación',
        'common.email': 'Correo electrónico',
        'forgot.newPassword': 'Nueva contraseña',
        'common.confirmPassword': 'Confirmar contraseña',
        'common.requiredEmail': 'El correo es obligatorio.',
        'common.invalidEmail': 'Ingresa un correo válido.',
        'forgot.newPasswordRequired': 'La nueva contraseña es obligatoria.',
        'common.strongPasswordHint': 'Usa 8+ caracteres, mayúscula, minúscula y número.',
        'common.confirmPasswordRequired': 'Debes confirmar la contraseña.',
        'common.passwordsMismatch': 'Las contraseñas no coinciden.',
        'common.showPassword': 'Mostrar contraseña',
        'common.hidePassword': 'Ocultar contraseña',
        'common.showConfirmation': 'Mostrar confirmación',
        'common.hideConfirmation': 'Ocultar confirmación',
        'common.passwordStrength': 'Fortaleza',
        'common.strengthWeak': 'Débil',
        'common.strengthRegular': 'Regular',
        'common.strengthGood': 'Buena',
        'common.strengthStrong': 'Fuerte',
        'common.passwordRequired': 'La contraseña es obligatoria.',
        'forgot.updatePassword': 'Actualizar contraseña',
        'forgot.updating': 'Actualizando...',
        'forgot.resetFailed': 'No se pudo actualizar la contraseña.',
        'forgot.resetSuccess': 'Contraseña actualizada correctamente',
        'forgot.resetSuccessRedirect': 'Tu contraseña fue actualizada. Serás redirigido al login.',
        'forgot.rememberedAccess': '¿Recordaste tu acceso?',
        'forgot.backToLogin': 'Volver al login',
        'common.minPasswordTitle': 'Mínimo 8 caracteres, incluyendo mayúscula, minúscula y número.',
        'common.tipUpper': 'Añade letras MAYÚSCULAS (A-Z)',
        'common.tipLower': 'Añade letras minúsculas (a-z)',
        'common.tipNumber': 'Añade un número (0-9)',
        'common.tipMinChars': 'Mínimo 8 caracteres',
      };
      return map[key] || key;
    },
  }),
}));

describe('ForgotPassword integration', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.restoreAllMocks();
    mockAuth = {
      isAuthenticated: false,
      resetPassword: mockResetPassword,
    };
  });

  afterEach(() => {
    cleanup();
  });

  it('shows inline validation and tips, and blocks invalid submit', async () => {
    const user = userEvent.setup();
    render(<ForgotPassword />);

    await user.type(screen.getByLabelText('Correo electrónico'), 'correo-invalido');
    await user.type(screen.getByLabelText('Nueva contraseña'), 'abc');
    await user.type(screen.getByLabelText('Confirmar contraseña'), 'xyz');
    await user.click(screen.getByRole('button', { name: 'Actualizar contraseña' }));

    expect(mockResetPassword).not.toHaveBeenCalled();
    expect(screen.getByText('Ingresa un correo válido.')).toBeInTheDocument();
    expect(screen.getByText('Las contraseñas no coinciden.')).toBeInTheDocument();
    expect(screen.getByText(/Añade letras MAYÚSCULAS/i)).toBeInTheDocument();
  });

  it('submits valid form, shows success and schedules redirect to login', async () => {
    const timeoutSpy = vi.spyOn(globalThis, 'setTimeout');
    const user = userEvent.setup();
    mockResetPassword.mockResolvedValue({ ok: true });

    render(<ForgotPassword />);

    await user.type(screen.getByLabelText('Correo electrónico'), 'ana@email.com');
    await user.type(screen.getByLabelText('Nueva contraseña'), 'Password1');
    await user.type(screen.getByLabelText('Confirmar contraseña'), 'Password1');
    await user.click(screen.getByRole('button', { name: 'Actualizar contraseña' }));

    expect(mockResetPassword).toHaveBeenCalledWith({
      email: 'ana@email.com',
      password: 'Password1',
      confirmPassword: 'Password1',
    });
    expect(mockShowToast).toHaveBeenCalledWith('Contraseña actualizada correctamente', 'success');
    expect(screen.getByText('Tu contraseña fue actualizada. Serás redirigido al login.')).toBeInTheDocument();
    expect(timeoutSpy).toHaveBeenCalledWith(expect.any(Function), 1200);
  });
});
