// Generated by GitHub Copilot
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import ProductCard from '../components/ProductCard';
import { products, categories } from '../data/products';

const ALLOWED_SORTS = ['featured', 'price-asc', 'price-desc', 'name-asc'];

/**
 * Reads and sanitizes list params from URL to keep UI shareable and stable.
 * @param {import('react-router-dom').URLSearchParamsInit} searchParams
 */
function parseListParams(searchParams) {
  const categoryParam = searchParams.get('categoria') || 'Todos';
  const category = categories.includes(categoryParam) ? categoryParam : 'Todos';

  const sortParam = searchParams.get('orden') || 'featured';
  const sortBy = ALLOWED_SORTS.includes(sortParam) ? sortParam : 'featured';

  const pageParam = Number.parseInt(searchParams.get('pagina') || '1', 10);
  const currentPage = Number.isNaN(pageParam) || pageParam < 1 ? 1 : pageParam;

  const rawSearch = searchParams.get('q') || '';
  const search = rawSearch.slice(0, 100);

  return { category, sortBy, currentPage, search };
}

/**
 * Home page showing the product grid with category filter.
 * Filters are implemented client-side for performance.
 */
export default function Home() {
  const [searchParams, setSearchParams] = useSearchParams();
  const initialParams = parseListParams(searchParams);

  const [activeCategory, setActiveCategory] = useState(initialParams.category);
  const [search, setSearch] = useState(initialParams.search);
  const [debouncedSearch, setDebouncedSearch] = useState(initialParams.search);
  const [sortBy, setSortBy] = useState(initialParams.sortBy);
  const [currentPage, setCurrentPage] = useState(initialParams.currentPage);
  const pageSize = 8;

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      setDebouncedSearch(search);
    }, 250);

    return () => clearTimeout(timeoutId);
  }, [search]);

  const filteredByCategory = useMemo(
    () => (activeCategory === 'Todos'
      ? products
      : products.filter((p) => p.category === activeCategory)),
    [activeCategory]
  );

  const filtered = useMemo(() => {
    const normalizedSearch = debouncedSearch.trim().toLowerCase();
    if (!normalizedSearch) {
      return filteredByCategory;
    }

    return filteredByCategory.filter((product) => (
      product.name.toLowerCase().includes(normalizedSearch)
      || product.description.toLowerCase().includes(normalizedSearch)
      || product.category.toLowerCase().includes(normalizedSearch)
    ));
  }, [debouncedSearch, filteredByCategory]);

  const sortedProducts = useMemo(() => [...filtered].sort((a, b) => {
    if (sortBy === 'price-asc') {
      return a.price - b.price;
    }
    if (sortBy === 'price-desc') {
      return b.price - a.price;
    }
    if (sortBy === 'name-asc') {
      return a.name.localeCompare(b.name);
    }
    return 0;
  }), [filtered, sortBy]);

  const totalPages = Math.max(1, Math.ceil(sortedProducts.length / pageSize));
  const safeCurrentPage = Math.min(currentPage, totalPages);
  const paginatedProducts = sortedProducts.slice(
    (safeCurrentPage - 1) * pageSize,
    safeCurrentPage * pageSize
  );

  useEffect(() => {
    const params = new URLSearchParams();
    if (activeCategory !== 'Todos') {
      params.set('categoria', activeCategory);
    }
    if (sortBy !== 'featured') {
      params.set('orden', sortBy);
    }
    if (search.trim()) {
      params.set('q', search.trim());
    }
    if (safeCurrentPage > 1) {
      params.set('pagina', String(safeCurrentPage));
    }

    const nextParams = params.toString();
    const currentParams = searchParams.toString();
    if (nextParams !== currentParams) {
      setSearchParams(params, { replace: true });
    }
  }, [activeCategory, safeCurrentPage, search, searchParams, setSearchParams, sortBy]);

  const clearFilters = () => {
    setActiveCategory('Todos');
    setSearch('');
    setSortBy('featured');
    setCurrentPage(1);
  };

  return (
    <main className="max-w-6xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">Nuestros Productos</h1>
      <p className="text-gray-500 mb-6">Encuentra lo que buscas al mejor precio.</p>

      <section className="mb-6 grid grid-cols-1 md:grid-cols-3 gap-3" aria-label="Controles de búsqueda y ordenado">
        <label className="md:col-span-2">
          <span className="sr-only">Buscar productos</span>
          <input
            type="search"
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setCurrentPage(1);
            }}
            placeholder="Buscar por nombre, categoría o descripción..."
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </label>
        <label>
          <span className="sr-only">Ordenar productos</span>
          <select
            value={sortBy}
            onChange={(e) => {
              setSortBy(e.target.value);
              setCurrentPage(1);
            }}
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="featured">Destacados</option>
            <option value="price-asc">Precio: menor a mayor</option>
            <option value="price-desc">Precio: mayor a menor</option>
            <option value="name-asc">Nombre: A-Z</option>
          </select>
        </label>
      </section>

      <p className="text-sm text-gray-500 mb-6" aria-live="polite">
        {sortedProducts.length} resultado{sortedProducts.length !== 1 ? 's' : ''} · Página {safeCurrentPage} de {totalPages}
      </p>

      <div className="mb-6 flex justify-end">
        <button
          type="button"
          onClick={clearFilters}
          className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        >
          Limpiar filtros
        </button>
      </div>

      {/* Category filter */}
      <div
        className="flex flex-wrap gap-2 mb-8"
        role="group"
        aria-label="Filtrar por categoría"
      >
        {categories.map((cat) => (
          <button
            key={cat}
            type="button"
            onClick={() => {
              setActiveCategory(cat);
              setCurrentPage(1);
            }}
            className={`px-4 py-1.5 rounded-full text-sm font-medium transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 ${
              activeCategory === cat
                ? 'bg-indigo-600 text-white'
                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            }`}
            aria-pressed={activeCategory === cat}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Product grid */}
      <section
        aria-label="Lista de productos"
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"
      >
        {paginatedProducts.map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </section>

      {sortedProducts.length > pageSize && (
        <nav className="mt-8 flex items-center justify-center gap-3" aria-label="Paginación de productos">
          <button
            type="button"
            onClick={() => setCurrentPage((prev) => Math.max(1, prev - 1))}
            disabled={safeCurrentPage === 1}
            className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Anterior
          </button>
          <span className="text-sm text-gray-600">{safeCurrentPage} / {totalPages}</span>
          <button
            type="button"
            onClick={() => setCurrentPage((prev) => Math.min(totalPages, prev + 1))}
            disabled={safeCurrentPage === totalPages}
            className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Siguiente
          </button>
        </nav>
      )}

      {sortedProducts.length === 0 && (
        <div className="mt-8 rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-10 text-center">
          <p className="text-lg font-semibold text-gray-800">No encontramos productos</p>
          <p className="text-sm text-gray-500 mt-1">Prueba con otra búsqueda o cambia la categoría.</p>
        </div>
      )}
    </main>
  );
}
