// Generated by GitHub Copilot
import { useEffect, useState } from 'react';
import ProductCard from '../components/ProductCard';
import { products, categories } from '../data/products';
/**
 * Home page showing the product grid with category filter.
 * Filters are implemented client-side for performance.
 */
export default function Home() {
  const [activeCategory, setActiveCategory] = useState('Todos');
  const [search, setSearch] = useState('');
  const [sortBy, setSortBy] = useState('featured');
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 8;

  const filteredByCategory =
    activeCategory === 'Todos'
      ? products
      : products.filter((p) => p.category === activeCategory);

  const filtered = filteredByCategory.filter((product) => {
    const normalizedSearch = search.trim().toLowerCase();
    if (!normalizedSearch) {
      return true;
    }
    return (
      product.name.toLowerCase().includes(normalizedSearch)
      || product.description.toLowerCase().includes(normalizedSearch)
      || product.category.toLowerCase().includes(normalizedSearch)
    );
  });

  const sortedProducts = [...filtered].sort((a, b) => {
    if (sortBy === 'price-asc') {
      return a.price - b.price;
    }
    if (sortBy === 'price-desc') {
      return b.price - a.price;
    }
    if (sortBy === 'name-asc') {
      return a.name.localeCompare(b.name);
    }
    return 0;
  });

  const totalPages = Math.max(1, Math.ceil(sortedProducts.length / pageSize));
  const paginatedProducts = sortedProducts.slice(
    (currentPage - 1) * pageSize,
    currentPage * pageSize
  );

  useEffect(() => {
    setCurrentPage(1);
  }, [activeCategory, search, sortBy]);
  return (
    <main className="max-w-6xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">Nuestros Productos</h1>
      <p className="text-gray-500 mb-6">Encuentra lo que buscas al mejor precio.</p>

      <section className="mb-6 grid grid-cols-1 md:grid-cols-3 gap-3" aria-label="Controles de búsqueda y ordenado">
        <label className="md:col-span-2">
          <span className="sr-only">Buscar productos</span>
          <input
            type="search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Buscar por nombre, categoría o descripción..."
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </label>
        <label>
          <span className="sr-only">Ordenar productos</span>
          <select
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value)}
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="featured">Destacados</option>
            <option value="price-asc">Precio: menor a mayor</option>
            <option value="price-desc">Precio: mayor a menor</option>
            <option value="name-asc">Nombre: A-Z</option>
          </select>
        </label>
      </section>

      <p className="text-sm text-gray-500 mb-6" aria-live="polite">
        {sortedProducts.length} resultado{sortedProducts.length !== 1 ? 's' : ''} · Página {currentPage} de {totalPages}
      </p>

      {/* Category filter */}
      <div
        className="flex flex-wrap gap-2 mb-8"
        role="group"
        aria-label="Filtrar por categoría"
      >
        {categories.map((cat) => (
          <button
            key={cat}
            type="button"
            onClick={() => setActiveCategory(cat)}
            className={`px-4 py-1.5 rounded-full text-sm font-medium transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 ${
              activeCategory === cat
                ? 'bg-indigo-600 text-white'
                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            }`}
            aria-pressed={activeCategory === cat}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Product grid */}
      <section
        aria-label="Lista de productos"
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"
      >
        {paginatedProducts.map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </section>

      {sortedProducts.length > pageSize && (
        <nav className="mt-8 flex items-center justify-center gap-3" aria-label="Paginación de productos">
          <button
            type="button"
            onClick={() => setCurrentPage((prev) => Math.max(1, prev - 1))}
            disabled={currentPage === 1}
            className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Anterior
          </button>
          <span className="text-sm text-gray-600">{currentPage} / {totalPages}</span>
          <button
            type="button"
            onClick={() => setCurrentPage((prev) => Math.min(totalPages, prev + 1))}
            disabled={currentPage === totalPages}
            className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Siguiente
          </button>
        </nav>
      )}

      {sortedProducts.length === 0 && (
        <div className="mt-8 rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-10 text-center">
          <p className="text-lg font-semibold text-gray-800">No encontramos productos</p>
          <p className="text-sm text-gray-500 mt-1">Prueba con otra búsqueda o cambia la categoría.</p>
        </div>
      )}
    </main>
  );
}
