// Generated by GitHub Copilot
import '@testing-library/jest-dom/vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import Login from './Login';

const mockNavigate = vi.fn();
const mockShowToast = vi.fn();
const mockLogin = vi.fn();

let mockAuth = {
  isAuthenticated: false,
  login: mockLogin,
};

let mockLocation = { state: undefined };

vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom');
  return {
    ...actual,
    Link: ({ children, to, ...props }) => <a href={to} {...props}>{children}</a>,
    Navigate: ({ to }) => <div data-testid="navigate">{to}</div>,
    useNavigate: () => mockNavigate,
    useLocation: () => mockLocation,
  };
});

vi.mock('../context/useAuth', () => ({
  default: () => mockAuth,
}));

vi.mock('../context/useCart', () => ({
  default: () => ({ showToast: mockShowToast }),
}));

vi.mock('../hooks/useDocumentTitle', () => ({
  default: () => undefined,
}));

vi.mock('../context/useLanguage', () => ({
  default: () => ({
    t: (key, vars) => {
      const map = {
        'common.login': 'Iniciar sesión',
        'common.email': 'Correo electrónico',
        'common.password': 'Contraseña',
        'common.requiredEmail': 'El correo es obligatorio',
        'common.invalidEmail': 'Ingresa un correo válido.',
        'common.requiredPassword': 'La contraseña es obligatoria.',
        'common.passwordMin': 'Debe tener al menos 8 caracteres.',
        'common.signIn': 'Entrar',
        'common.signingIn': 'Entrando...',
        'common.showPassword': 'Mostrar contraseña',
        'common.hidePassword': 'Ocultar contraseña',
        'common.rememberEmail': 'Recordar mi correo',
        'common.signInFailed': 'No se pudo iniciar sesión.',
        'common.loginAs': `Sesión iniciada como ${vars?.role ?? ''}`,
        'common.roleAdmin': 'Administrador',
        'common.roleClient': 'Cliente',
        'common.accessToProducts': 'Accede para ver productos y completar tus compras.',
        'common.forgotPassword': '¿Olvidaste tu contraseña?',
        'common.dontHaveAccount': '¿No tienes cuenta?',
        'common.register': 'Registrarme',
      };
      return map[key] || key;
    },
  }),
}));

describe('Login integration', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    localStorage.clear();
    mockAuth = {
      isAuthenticated: false,
      login: mockLogin,
    };
    mockLocation = { state: undefined };
  });

  afterEach(() => {
    cleanup();
  });

  it('shows inline validation errors and does not submit invalid form', async () => {
    const user = userEvent.setup();
    render(<Login />);

    await user.type(screen.getByLabelText('Correo electrónico'), 'correo-invalido');
    await user.type(screen.getByLabelText('Contraseña'), '12345');
    await user.click(screen.getByRole('button', { name: 'Entrar' }));

    expect(mockLogin).not.toHaveBeenCalled();
    expect(screen.getByText('Ingresa un correo válido.')).toBeInTheDocument();
    expect(screen.getByText('Debe tener al menos 8 caracteres.')).toBeInTheDocument();
  });

  it('submits valid form, remembers email and navigates to redirect path', async () => {
    const user = userEvent.setup();
    mockLocation = { state: { from: { pathname: '/admin/productos' } } };
    mockLogin.mockResolvedValue({ ok: true, role: 'admin' });

    render(<Login />);

    await user.type(screen.getByLabelText('Correo electrónico'), 'admin@tienda.com');
    await user.type(screen.getByLabelText('Contraseña'), 'Password1');
    await user.click(screen.getByLabelText('Recordar mi correo'));
    await user.click(screen.getByRole('button', { name: 'Entrar' }));

    expect(mockLogin).toHaveBeenCalledWith({ email: 'admin@tienda.com', password: 'Password1' });
    expect(mockShowToast).toHaveBeenCalledWith('Sesión iniciada como administrador', 'success');
    expect(localStorage.getItem('tienda_react_remembered_email')).toBe('admin@tienda.com');
    expect(mockNavigate).toHaveBeenCalledWith('/admin/productos', { replace: true });
  });
});
