// Generated by GitHub Copilot
import '@testing-library/jest-dom/vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import NotFound from './NotFound';

const mockNavigate = vi.fn();

vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom');
  return {
    ...actual,
    Link: ({ children, to, ...props }) => <a href={to} {...props}>{children}</a>,
    useNavigate: () => mockNavigate,
  };
});

vi.mock('../hooks/useDocumentTitle', () => ({
  default: () => undefined,
}));

vi.mock('../context/useLanguage', () => ({
  default: () => ({
    t: (key) => {
      const map = {
        'notFound.title': 'Página no encontrada',
        'notFound.subtitle': 'La dirección no existe.',
        'notFound.back': 'Volver',
        'notFound.home': 'Ir al inicio',
        'notFound.exploreCategories': 'Explorar categorías',
      };
      return map[key] ?? key;
    },
    translateCategory: (c) => c,
  }),
}));

afterEach(() => {
  cleanup();
  mockNavigate.mockClear();
});

describe('NotFound', () => {
  it('renders the 404 heading and subtitle', () => {
    render(<NotFound />);

    const heading = screen.getByRole('heading', { level: 1, name: 'Página no encontrada' });
    expect(heading).toBeInTheDocument();
    expect(heading).toHaveFocus();
    expect(screen.getByText('La dirección no existe.')).toBeInTheDocument();
  });

  it('renders a link to go home', () => {
    render(<NotFound />);

    const homeLink = screen.getByRole('link', { name: 'Ir al inicio' });
    expect(homeLink).toBeInTheDocument();
    expect(homeLink).toHaveAttribute('href', '/');
  });

  it('back button calls navigate(-1)', async () => {
    const user = userEvent.setup();
    render(<NotFound />);

    await user.click(screen.getByRole('button', { name: /Volver/i }));
    expect(mockNavigate).toHaveBeenCalledWith(-1);
  });

  it('renders quick-category links', () => {
    render(<NotFound />);

    const categoryLinks = screen.getAllByRole('link').filter((l) =>
      l.getAttribute('href')?.includes('categoria=')
    );
    expect(categoryLinks.length).toBeGreaterThan(0);
  });
});
