// Generated by GitHub Copilot
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { products } from '../data/products';
import useCart from '../context/useCart';

const ORDERS_STORAGE_KEY = 'tienda_react_orders';
const REFERENCE_NOW_MS = Date.now();

/**
 * Reads persisted orders safely from local storage.
 * @returns {Array<{ id: string, createdAt: string, totalPrice: number, totalItems: number, customerName: string, items: Array<{ id: number|string, name: string, quantity: number, price: number }>}>}
 */
function getInitialOrders() {
  try {
    const rawOrders = localStorage.getItem(ORDERS_STORAGE_KEY);
    const parsed = rawOrders ? JSON.parse(rawOrders) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

/**
 * Formats an ISO date string in locale-friendly output.
 * @param {string} dateIso
 * @returns {string}
 */
function formatDate(dateIso) {
  const date = new Date(dateIso);
  if (Number.isNaN(date.getTime())) {
    return 'Fecha no disponible';
  }
  return new Intl.DateTimeFormat('es-ES', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(date);
}

/**
 * Orders page with local persistent history.
 */
export default function Orders() {
  const { dispatch, showToast } = useCart();
  const [orders, setOrders] = useState(getInitialOrders);
  const [search, setSearch] = useState('');
  const [dateFilter, setDateFilter] = useState('all');
  const [sortBy, setSortBy] = useState('newest');

  useEffect(() => {
    localStorage.setItem(ORDERS_STORAGE_KEY, JSON.stringify(orders));
  }, [orders]);

  const clearOrders = () => {
    setOrders([]);
  };

  const clearFilters = () => {
    setSearch('');
    setDateFilter('all');
    setSortBy('newest');
  };

  const productById = useMemo(() => new Map(products.map((product) => [product.id, product])), []);

  const filteredOrders = useMemo(() => {
    const searchValue = search.trim().toLowerCase();

    const filtered = orders.filter((order) => {
      if (dateFilter !== 'all') {
        const days = Number.parseInt(dateFilter, 10);
        const createdAtMs = new Date(order.createdAt).getTime();
        if (Number.isNaN(createdAtMs) || REFERENCE_NOW_MS - createdAtMs > days * 24 * 60 * 60 * 1000) {
          return false;
        }
      }

      if (!searchValue) {
        return true;
      }

      const haystack = [
        String(order.id),
        String(order.customerName || ''),
        String(order.couponCode || ''),
        ...order.items.map((item) => String(item.name || '')),
      ].join(' ').toLowerCase();

      return haystack.includes(searchValue);
    });

    return [...filtered].sort((a, b) => {
      if (sortBy === 'oldest') {
        return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
      }
      if (sortBy === 'total-high') {
        return Number(b.totalPrice || 0) - Number(a.totalPrice || 0);
      }
      if (sortBy === 'total-low') {
        return Number(a.totalPrice || 0) - Number(b.totalPrice || 0);
      }
      return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
    });
  }, [dateFilter, orders, search, sortBy]);

  const stats = useMemo(() => {
    const totalOrders = filteredOrders.length;
    const totalSpent = filteredOrders.reduce((sum, order) => sum + Number(order.totalPrice || 0), 0);
    const totalSaved = filteredOrders.reduce((sum, order) => sum + Number(order.discountAmount || 0), 0);
    return { totalOrders, totalSpent, totalSaved };
  }, [filteredOrders]);

  const handleReorder = (order) => {
    const items = order.items.map((item) => {
      const product = productById.get(item.id);
      return {
        id: item.id,
        name: item.name || product?.name || 'Producto',
        price: Number(item.price ?? product?.price ?? 0),
        image: item.image || product?.image || '',
        description: product?.description || '',
        category: product?.category || 'General',
        quantity: Number(item.quantity || 1),
      };
    });

    dispatch({ type: 'ADD_ORDER_ITEMS', payload: { items } });
    showToast(`Pedido #${order.id} agregado nuevamente al carrito`, 'success');
  };

  if (orders.length === 0) {
    return (
      <main className="max-w-2xl mx-auto px-4 py-16 text-center">
        <p className="text-5xl mb-4" aria-hidden="true">📦</p>
        <h1 className="text-2xl font-bold text-gray-800 mb-2">Aún no tienes pedidos</h1>
        <p className="text-gray-500 mb-6">Cuando completes una compra, aparecerá aquí.</p>
        <Link
          to="/"
          className="inline-block rounded-xl bg-indigo-600 px-5 py-2.5 font-medium text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        >
          Ir a productos
        </Link>
      </main>
    );
  }

  return (
    <main className="max-w-5xl mx-auto px-4 py-8">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-3xl font-bold text-gray-900">Historial de pedidos</h1>
        <button
          type="button"
          onClick={clearOrders}
          className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        >
          Limpiar historial
        </button>
      </div>

      <section className="mb-6 grid grid-cols-1 gap-3 md:grid-cols-4" aria-label="Filtros de pedidos">
        <label className="md:col-span-2">
          <span className="sr-only">Buscar en pedidos</span>
          <input
            type="search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Buscar por cliente, cupón, producto o número de pedido..."
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </label>
        <label>
          <span className="sr-only">Filtrar pedidos por fecha</span>
          <select
            value={dateFilter}
            onChange={(e) => setDateFilter(e.target.value)}
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="all">Todo el historial</option>
            <option value="7">Últimos 7 días</option>
            <option value="30">Últimos 30 días</option>
            <option value="90">Últimos 90 días</option>
          </select>
        </label>
        <label>
          <span className="sr-only">Ordenar pedidos</span>
          <select
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value)}
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="newest">Más recientes</option>
            <option value="oldest">Más antiguos</option>
            <option value="total-high">Mayor total</option>
            <option value="total-low">Menor total</option>
          </select>
        </label>
      </section>

      <div className="mb-6 flex items-center justify-end">
        <button
          type="button"
          onClick={clearFilters}
          className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        >
          Limpiar filtros
        </button>
      </div>

      <section className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-3" aria-label="Métricas de pedidos">
        <article className="rounded-2xl bg-white p-4 shadow">
          <p className="text-sm text-gray-500">Pedidos visibles</p>
          <p className="text-2xl font-bold text-gray-900">{stats.totalOrders}</p>
        </article>
        <article className="rounded-2xl bg-white p-4 shadow">
          <p className="text-sm text-gray-500">Gasto total</p>
          <p className="text-2xl font-bold text-indigo-700">${stats.totalSpent.toFixed(2)}</p>
        </article>
        <article className="rounded-2xl bg-white p-4 shadow">
          <p className="text-sm text-gray-500">Ahorro por cupones</p>
          <p className="text-2xl font-bold text-green-700">${stats.totalSaved.toFixed(2)}</p>
        </article>
      </section>

      {filteredOrders.length === 0 && (
        <div className="mb-6 rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-10 text-center">
          <p className="text-lg font-semibold text-gray-800">No hay resultados con esos filtros</p>
          <p className="text-sm text-gray-500 mt-1">Prueba otra búsqueda o amplía el rango de fecha.</p>
        </div>
      )}

      <section className="flex flex-col gap-4" aria-label="Lista de pedidos">
        {filteredOrders.map((order) => (
          <article key={order.id} className="rounded-2xl bg-white p-5 shadow">
            <header className="mb-3 flex flex-wrap items-center justify-between gap-2 border-b pb-3">
              <div>
                <p className="text-sm text-gray-500">Pedido #{order.id}</p>
                <h2 className="text-lg font-semibold text-gray-900">{order.customerName}</h2>
              </div>
              <div className="text-right">
                <p className="text-sm text-gray-500">{formatDate(order.createdAt)}</p>
                <p className="font-bold text-indigo-700">${Number(order.totalPrice).toFixed(2)}</p>
              </div>
            </header>

            <div className="mb-3 flex flex-wrap items-center gap-3 text-sm text-gray-600">
              <span>
                {order.totalItems} producto{order.totalItems !== 1 ? 's' : ''}
              </span>
              {order.discountAmount > 0 && (
                <span className="inline-flex items-center gap-1 rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-700">
                  🏷️ {order.couponCode} &minus;${Number(order.discountAmount).toFixed(2)}
                </span>
              )}
            </div>

            <ul className="grid grid-cols-1 gap-2 sm:grid-cols-2" role="list">
              {order.items.map((item) => (
                <li key={`${order.id}-${item.id}`} className="rounded-lg border border-gray-200 px-3 py-2 text-sm">
                  <span className="font-medium text-gray-800">{item.name}</span>
                  <span className="ml-2 text-gray-500">x{item.quantity}</span>
                  <span className="float-right font-semibold text-gray-700">
                    ${(item.price * item.quantity).toFixed(2)}
                  </span>
                </li>
              ))}
            </ul>

            <div className="mt-4 flex flex-wrap items-center justify-end gap-2">
              <button
                type="button"
                onClick={() => handleReorder(order)}
                className="rounded-lg border border-indigo-300 bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700 transition hover:bg-indigo-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Repetir pedido
              </button>
              <Link
                to="/carrito"
                className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Ir al carrito
              </Link>
            </div>
          </article>
        ))}
      </section>
    </main>
  );
}
