// Generated by GitHub Copilot
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import useCart from '../context/useCart';
import useProducts from '../context/useProducts';

const ORDERS_STORAGE_KEY = 'tienda_react_orders';

/**
 * Escapes CSV field values and wraps them in quotes when needed.
 * @param {string | number | null | undefined} value
 * @returns {string}
 */
function escapeCsvField(value) {
  const text = String(value ?? '');
  const escaped = text.replace(/"/g, '""');
  return /[",\n;]/.test(escaped) ? `"${escaped}"` : escaped;
}

/**
 * Builds a CSV string from the currently visible orders.
 * @param {Array} orders
 * @returns {string}
 */
function buildOrdersCsv(orders) {
  const headers = [
    'pedido_id',
    'fecha_iso',
    'cliente',
    'items_total',
    'subtotal',
    'descuento',
    'cupon',
    'total_final',
    'productos',
  ];

  const rows = orders.map((order) => {
    const products = order.items
      .map((item) => `${item.name} x${item.quantity}`)
      .join(' | ');

    return [
      order.id,
      order.createdAt,
      order.customerName,
      Number(order.totalItems || 0).toFixed(0),
      Number(order.subtotalPrice ?? order.totalPrice ?? 0).toFixed(2),
      Number(order.discountAmount || 0).toFixed(2),
      order.couponCode || '',
      Number(order.totalPrice || 0).toFixed(2),
      products,
    ].map(escapeCsvField).join(',');
  });

  return [headers.join(','), ...rows].join('\n');
}

/**
 * Downloads text content as a file and releases temporary resources.
 * @param {string} content
 * @param {string} fileName
 * @param {string} mimeType
 */
function downloadTextFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');

  link.href = url;
  link.download = fileName;
  document.body.append(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

/**
 * Reads persisted orders safely from local storage.
 * @returns {Array<{ id: string, createdAt: string, totalPrice: number, totalItems: number, customerName: string, items: Array<{ id: number|string, name: string, quantity: number, price: number }>}>}
 */
function getInitialOrders() {
  try {
    const rawOrders = localStorage.getItem(ORDERS_STORAGE_KEY);
    const parsed = rawOrders ? JSON.parse(rawOrders) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

/**
 * Formats an ISO date string in locale-friendly output.
 * @param {string} dateIso
 * @returns {string}
 */
function formatDate(dateIso) {
  const date = new Date(dateIso);
  if (Number.isNaN(date.getTime())) {
    return 'Fecha no disponible';
  }
  return new Intl.DateTimeFormat('es-ES', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(date);
}

/** Normalizes text for accent-insensitive and case-insensitive search. */
function normalizeSearchText(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
}

/**
 * Orders page with local persistent history.
 */
export default function Orders() {
  const { dispatch, showToast } = useCart();
  const { products } = useProducts();
  const [orders, setOrders] = useState(getInitialOrders);
  const [search, setSearch] = useState('');
  const [dateFilter, setDateFilter] = useState('all');
  const [sortBy, setSortBy] = useState('newest');
  const [expandedOrderIds, setExpandedOrderIds] = useState([]);
  const searchInputRef = useRef(null);

  useEffect(() => {
    localStorage.setItem(ORDERS_STORAGE_KEY, JSON.stringify(orders));
  }, [orders]);

  useEffect(() => {
    /** Shortcut: press / to focus orders search when not typing in a field. */
    const handleKeydown = (event) => {
      const targetTag = event.target?.tagName?.toLowerCase();
      const isTypingField = targetTag === 'input' || targetTag === 'textarea' || event.target?.isContentEditable;
      if (!isTypingField && event.key === '/') {
        event.preventDefault();
        searchInputRef.current?.focus();
      }
    };

    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  }, []);

  const clearOrders = () => {
    const shouldClear = window.confirm('Esta accion eliminara todo tu historial de pedidos. Deseas continuar?');
    if (!shouldClear) {
      return;
    }
    setOrders([]);
    showToast('Historial de pedidos eliminado', 'info');
  };

  const clearFilters = () => {
    setSearch('');
    setDateFilter('all');
    setSortBy('newest');
  };

  /**
   * Toggles expanded details for a single order card.
   * @param {string} orderId
   */
  const toggleOrderExpanded = (orderId) => {
    setExpandedOrderIds((prev) => (
      prev.includes(orderId)
        ? prev.filter((id) => id !== orderId)
        : [...prev, orderId]
    ));
  };

  const productById = useMemo(() => new Map(products.map((product) => [product.id, product])), [products]);

  const filteredOrders = useMemo(() => {
    const searchValue = normalizeSearchText(search.trim());

    const filtered = orders.filter((order) => {
      if (dateFilter !== 'all') {
        const days = Number.parseInt(dateFilter, 10);
        const createdAtMs = new Date(order.createdAt).getTime();
        if (Number.isNaN(createdAtMs) || Date.now() - createdAtMs > days * 24 * 60 * 60 * 1000) {
          return false;
        }
      }

      if (!searchValue) {
        return true;
      }

      const haystack = [
        String(order.id),
        String(order.customerName || ''),
        String(order.couponCode || ''),
        ...order.items.map((item) => String(item.name || '')),
      ].join(' ');

      return normalizeSearchText(haystack).includes(searchValue);
    });

    return [...filtered].sort((a, b) => {
      if (sortBy === 'oldest') {
        return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
      }
      if (sortBy === 'total-high') {
        return Number(b.totalPrice || 0) - Number(a.totalPrice || 0);
      }
      if (sortBy === 'total-low') {
        return Number(a.totalPrice || 0) - Number(b.totalPrice || 0);
      }
      return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
    });
  }, [dateFilter, orders, search, sortBy]);

  const stats = useMemo(() => {
    const totalOrders = filteredOrders.length;
    const totalSpent = filteredOrders.reduce((sum, order) => sum + Number(order.totalPrice || 0), 0);
    const totalSaved = filteredOrders.reduce((sum, order) => sum + Number(order.discountAmount || 0), 0);
    return { totalOrders, totalSpent, totalSaved };
  }, [filteredOrders]);

  const handleReorder = (order) => {
    const items = order.items.map((item) => {
      const product = productById.get(item.id);
      return {
        id: item.id,
        name: item.name || product?.name || 'Producto',
        price: Number(item.price ?? product?.price ?? 0),
        image: item.image || product?.image || '',
        description: product?.description || '',
        category: product?.category || 'General',
        quantity: Number(item.quantity || 1),
      };
    });

    dispatch({ type: 'ADD_ORDER_ITEMS', payload: { items } });
    showToast(`Pedido #${order.id} agregado nuevamente al carrito`, 'success');
  };

  /**
   * Copies order id to clipboard for quick support sharing.
   * @param {string} orderId
   */
  const handleCopyOrderId = async (orderId) => {
    try {
      await navigator.clipboard.writeText(String(orderId));
      showToast(`ID de pedido #${orderId} copiado`, 'success');
    } catch {
      showToast('No se pudo copiar el ID del pedido', 'error');
    }
  };

  /**
   * Exports currently visible orders to a UTF-8 CSV file.
   */
  const handleExportVisibleOrders = () => {
    if (filteredOrders.length === 0) {
      showToast('No hay pedidos visibles para exportar', 'info');
      return;
    }

    const csv = buildOrdersCsv(filteredOrders);
    const csvWithBom = `\uFEFF${csv}`;
    const date = new Date().toISOString().slice(0, 10);
    downloadTextFile(csvWithBom, `pedidos-${date}.csv`, 'text/csv;charset=utf-8;');

    showToast(`CSV exportado con ${filteredOrders.length} pedido${filteredOrders.length !== 1 ? 's' : ''}`, 'success');
  };

  /**
   * Exports currently visible orders as pretty JSON.
   */
  const handleExportVisibleOrdersJson = () => {
    if (filteredOrders.length === 0) {
      showToast('No hay pedidos visibles para exportar', 'info');
      return;
    }

    const date = new Date().toISOString().slice(0, 10);
    const jsonContent = `${JSON.stringify(filteredOrders, null, 2)}\n`;
    downloadTextFile(jsonContent, `pedidos-${date}.json`, 'application/json;charset=utf-8;');
    showToast(`JSON exportado con ${filteredOrders.length} pedido${filteredOrders.length !== 1 ? 's' : ''}`, 'success');
  };

  if (orders.length === 0) {
    return (
      <main className="max-w-2xl mx-auto px-4 py-16 text-center">
        <p className="text-5xl mb-4" aria-hidden="true">📦</p>
        <h1 className="text-2xl font-bold text-gray-800 mb-2">Aún no tienes pedidos</h1>
        <p className="text-gray-500 mb-6">Cuando completes una compra, aparecerá aquí.</p>
        <Link
          to="/"
          className="inline-block rounded-xl bg-indigo-600 px-5 py-2.5 font-medium text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        >
          Ir a productos
        </Link>
      </main>
    );
  }

  return (
    <main className="max-w-5xl mx-auto px-4 py-8">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-3xl font-bold text-gray-900">Historial de pedidos</h1>
        <button
          type="button"
          onClick={clearOrders}
          className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        >
          Limpiar historial
        </button>
      </div>

      <section className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-3" aria-label="Resumen de compras">
        <div className="rounded-xl border border-gray-200 bg-white px-4 py-3 text-center">
          <p className="text-xs uppercase tracking-wide text-gray-500 mb-1">Pedidos</p>
          <p className="text-2xl font-bold text-gray-900">{stats.totalOrders}</p>
        </div>
        <div className="rounded-xl border border-gray-200 bg-white px-4 py-3 text-center">
          <p className="text-xs uppercase tracking-wide text-gray-500 mb-1">Total gastado</p>
          <p className="text-2xl font-bold text-indigo-700">${stats.totalSpent.toFixed(2)}</p>
        </div>
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-center">
          <p className="text-xs uppercase tracking-wide text-emerald-700 mb-1">Total ahorrado</p>
          <p className="text-2xl font-bold text-emerald-700">${stats.totalSaved.toFixed(2)}</p>
        </div>
      </section>

      <section className="mb-6 grid grid-cols-1 gap-3 md:grid-cols-4" aria-label="Filtros de pedidos">
        <label className="md:col-span-2">
          <span className="sr-only">Buscar en pedidos</span>
          <input
            ref={searchInputRef}
            type="search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Buscar por cliente, cupón, producto o número de pedido..."
            title="Atajo: /"
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </label>
        <label>
          <span className="sr-only">Filtrar pedidos por fecha</span>
          <select
            value={dateFilter}
            onChange={(e) => setDateFilter(e.target.value)}
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="all">Todo el historial</option>
            <option value="7">Últimos 7 días</option>
            <option value="30">Últimos 30 días</option>
            <option value="90">Últimos 90 días</option>
          </select>
        </label>
        <label>
          <span className="sr-only">Ordenar pedidos</span>
          <select
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value)}
            className="w-full rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="newest">Más recientes</option>
            <option value="oldest">Más antiguos</option>
            <option value="total-high">Mayor total</option>
            <option value="total-low">Menor total</option>
          </select>
        </label>
      </section>

      <div className="mb-6 flex flex-wrap items-center justify-end gap-2">
        <button
          type="button"
          onClick={handleExportVisibleOrdersJson}
          disabled={filteredOrders.length === 0}
          className="rounded-lg border border-sky-300 bg-sky-50 px-3 py-2 text-sm font-semibold text-sky-700 transition hover:bg-sky-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Exportar JSON
        </button>
        <button
          type="button"
          onClick={handleExportVisibleOrders}
          disabled={filteredOrders.length === 0}
          className="rounded-lg border border-emerald-300 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700 transition hover:bg-emerald-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Exportar CSV
        </button>
        <button
          type="button"
          onClick={clearFilters}
          className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        >
          Limpiar filtros
        </button>
      </div>

      {filteredOrders.length === 0 && (
        <div className="mb-6 rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-10 text-center">
          <p className="text-lg font-semibold text-gray-800">No hay resultados con esos filtros</p>
          <p className="text-sm text-gray-500 mt-1">Prueba otra búsqueda o amplía el rango de fecha.</p>
        </div>
      )}

      <section className="flex flex-col gap-4" aria-label="Lista de pedidos">
        {filteredOrders.map((order) => (
          <article key={order.id} className="rounded-2xl bg-white p-5 shadow">
            <header className="mb-3 flex flex-wrap items-center justify-between gap-2 border-b pb-3">
              <div>
                <p className="text-sm text-gray-500">Pedido #{order.id}</p>
                <h2 className="text-lg font-semibold text-gray-900">{order.customerName}</h2>
              </div>
              <div className="text-right">
                <p className="text-sm text-gray-500">{formatDate(order.createdAt)}</p>
                <p className="font-bold text-indigo-700">${Number(order.totalPrice).toFixed(2)}</p>
              </div>
            </header>

            <div className="mb-3 flex flex-wrap items-center gap-3 text-sm text-gray-600">
              <span>
                {order.totalItems} producto{order.totalItems !== 1 ? 's' : ''}
              </span>
              <span>
                Subtotal: ${Number(order.subtotalPrice ?? order.totalPrice ?? 0).toFixed(2)}
              </span>
              {order.discountAmount > 0 && (
                <span className="inline-flex items-center gap-1 rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-700">
                  🏷️ {order.couponCode} &minus;${Number(order.discountAmount).toFixed(2)}
                </span>
              )}
            </div>

            {expandedOrderIds.includes(order.id) && (
              <ul className="grid grid-cols-1 gap-2 sm:grid-cols-2" role="list">
                {order.items.map((item) => (
                  <li key={`${order.id}-${item.id}`} className="rounded-lg border border-gray-200 px-3 py-2 text-sm">
                    <span className="font-medium text-gray-800">{item.name}</span>
                    <span className="ml-2 text-gray-500">x{item.quantity}</span>
                    <span className="float-right font-semibold text-gray-700">
                      ${(item.price * item.quantity).toFixed(2)}
                    </span>
                  </li>
                ))}
              </ul>
            )}

            <div className="mt-4 flex flex-wrap items-center justify-end gap-2">
              <button
                type="button"
                onClick={() => toggleOrderExpanded(order.id)}
                className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                aria-expanded={expandedOrderIds.includes(order.id)}
              >
                {expandedOrderIds.includes(order.id) ? 'Ocultar detalle' : 'Ver detalle'}
              </button>
              <button
                type="button"
                onClick={() => handleCopyOrderId(order.id)}
                className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Copiar ID
              </button>
              <button
                type="button"
                onClick={() => handleReorder(order)}
                className="rounded-lg border border-indigo-300 bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700 transition hover:bg-indigo-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Repetir pedido
              </button>
              <Link
                to="/carrito"
                className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Ir al carrito
              </Link>
            </div>
          </article>
        ))}
      </section>
    </main>
  );
}
