// Generated by GitHub Copilot
import { describe, expect, it } from 'vitest';
import { buildOrdersCsv } from './ordersHelpers';
import { normalizeSearchText } from './searchHelpers';

/** Pedido de ejemplo para usar en los tests */
const SAMPLE_ORDER = {
  id: 'uuid-abc-123',
  orderNumber: 'Ana-ABCDEF',
  createdAt: '2026-04-29T10:00:00.000Z',
  customerName: 'Ana García',
  totalItems: 2,
  subtotalPrice: 45.00,
  discountAmount: 5.00,
  couponCode: 'VERANO10',
  totalPrice: 40.00,
  items: [
    { name: 'Camiseta azul', quantity: 1, price: 25.00 },
    { name: 'Pantalón negro', quantity: 1, price: 20.00 },
  ],
};

describe('buildOrdersCsv', () => {
  it('incluye la columna order_number en la cabecera', () => {
    const csv = buildOrdersCsv([SAMPLE_ORDER]);
    const [header] = csv.split('\n');
    expect(header).toContain('order_number');
  });

  it('usa el orderNumber visible (no el UUID interno) en las filas', () => {
    const csv = buildOrdersCsv([SAMPLE_ORDER]);
    const [, dataRow] = csv.split('\n');
    expect(dataRow).toContain('Ana-ABCDEF');
    // El UUID interno puede aparecer en order_id pero no debe reemplazar al orderNumber
    expect(dataRow).not.toMatch(/^uuid-abc-123,uuid-abc-123/);
  });

  it('genera tantas filas de datos como pedidos recibe', () => {
    const csv = buildOrdersCsv([SAMPLE_ORDER, { ...SAMPLE_ORDER, id: 'uuid-xyz-456', orderNumber: 'Carlos-ZZZZZZ' }]);
    const lines = csv.split('\n');
    // 1 cabecera + 2 filas de datos
    expect(lines).toHaveLength(3);
  });

  it('devuelve solo la cabecera cuando la lista está vacía', () => {
    const csv = buildOrdersCsv([]);
    const lines = csv.split('\n');
    expect(lines).toHaveLength(1);
    expect(lines[0]).toContain('order_id');
  });

  it('escapa comillas dobles en nombres de productos', () => {
    const orderWithQuotes = {
      ...SAMPLE_ORDER,
      items: [{ name: 'Camiseta "premium"', quantity: 1, price: 30 }],
    };
    const csv = buildOrdersCsv([orderWithQuotes]);
    // Las comillas se duplican en CSV estándar
    expect(csv).toContain('""premium""');
  });
});

describe('normalizeSearchText', () => {
  it('convierte a minúsculas y elimina acentos', () => {
    expect(normalizeSearchText('García')).toBe('garcia');
    expect(normalizeSearchText('ÑOÑO')).toBe('nono');
    expect(normalizeSearchText('Über')).toBe('uber');
  });

  it('el haystack que incluye orderNumber permite buscar por él', () => {
    const haystack = [
      String(SAMPLE_ORDER.id),
      String(SAMPLE_ORDER.orderNumber || ''),
      String(SAMPLE_ORDER.customerName || ''),
    ].join(' ');

    // Buscar por orderNumber debe devolver true
    expect(normalizeSearchText(haystack).includes(normalizeSearchText('Ana-ABCDEF'))).toBe(true);
    // Buscar por UUID también debe funcionar
    expect(normalizeSearchText(haystack).includes(normalizeSearchText('uuid-abc-123'))).toBe(true);
  });

  it('devuelve cadena vacía para valores falsy', () => {
    expect(normalizeSearchText(null)).toBe('');
    expect(normalizeSearchText(undefined)).toBe('');
    expect(normalizeSearchText('')).toBe('');
  });
});
