// Generated by GitHub Copilot
import '@testing-library/jest-dom/vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import ProductDetail from './ProductDetail';

const mockNavigate = vi.fn();
const mockDispatch = vi.fn();
const mockShowToast = vi.fn();
const mockToggleFavorite = vi.fn();

const MOCK_PRODUCT = {
  id: 1,
  name: 'Auriculares Bluetooth',
  price: 59.99,
  image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
  category: 'Electronica',
  description: 'Auriculares inalámbricos con cancelación de ruido.',
};

let mockCartState = {
  cart: [],
  isFavorite: () => false,
  toggleFavorite: mockToggleFavorite,
  dispatch: mockDispatch,
  showToast: mockShowToast,
};

let mockAuthUser = { role: 'user' };
let mockParamId = '1';

vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom');
  return {
    ...actual,
    Link: ({ children, to, ...props }) => <a href={to} {...props}>{children}</a>,
    useNavigate: () => mockNavigate,
    useParams: () => ({ id: mockParamId }),
    Navigate: ({ to }) => <div data-testid="navigate-to">{to}</div>,
  };
});

vi.mock('../context/useCart', () => ({
  default: () => mockCartState,
}));

vi.mock('../context/useAuth', () => ({
  default: () => ({ user: mockAuthUser }),
}));

vi.mock('../context/useProducts', () => ({
  default: () => ({ products: [MOCK_PRODUCT] }),
}));

vi.mock('../hooks/useDocumentTitle', () => ({
  default: () => undefined,
}));

vi.mock('../context/useLanguage', () => ({
  default: () => ({
    t: (key, vars) => {
      const map = {
        'productDetail.title': 'Producto',
        'productDetail.backToProducts': 'Volver a productos',
        'productDetail.sectionLabel': 'Detalle del producto',
        'productDetail.share': 'Compartir',
        'productDetail.quantity': 'Cantidad',
        'productDetail.decreaseQuantity': 'Disminuir cantidad',
        'productDetail.increaseQuantity': 'Aumentar cantidad',
        'productDetail.alreadyInCart': 'Ya tienes {count} en el carrito',
        'productDetail.notInCartYet': 'Aún no has añadido este producto',
        'productDetail.relatedTitle': 'Productos relacionados',
        'productDetail.addedQuantity': `Añadiste ${vars?.quantity ?? 1} × "${vars?.name}" al carrito`,
        'productDetail.readyToBuyQuantity': `${vars?.quantity ?? 1} × "${vars?.name}" listo para comprar`,
        'productDetail.quantityAdjusted': `Cantidad ajustada a ${vars?.quantity ?? 1}`,
        'productCard.addProduct': 'Añadir al carrito',
        'productCard.buy': 'Comprar ahora',
        'productCard.favoriteOn': 'Quitar de favoritos',
        'productCard.favoriteOff': 'Añadir a favoritos',
        'productCard.addFavorite': `Añadir a favoritos: ${vars?.name}`,
        'productCard.removeFavorite': `Quitar de favoritos: ${vars?.name}`,
        'notFound.home': 'Inicio',
        'common.breadcrumb': 'Ruta de navegación',
      };
      return map[key] ?? key;
    },
    formatCurrency: (v) => `$${v.toFixed(2)}`,
    translateCategory: (c) => c,
    translateProductText: (text) => text,
  }),
}));

afterEach(() => {
  cleanup();
  mockDispatch.mockClear();
  mockShowToast.mockClear();
  mockNavigate.mockClear();
  mockToggleFavorite.mockClear();
  mockAuthUser = { role: 'user' };
  mockParamId = '1';
  mockCartState = {
    cart: [],
    isFavorite: () => false,
    toggleFavorite: mockToggleFavorite,
    dispatch: mockDispatch,
    showToast: mockShowToast,
  };
});

describe('ProductDetail integration', () => {
  it('renders product heading, breadcrumb and back link', () => {
    render(<ProductDetail />);

    expect(screen.getByRole('heading', { level: 1, name: 'Auriculares Bluetooth' })).toBeInTheDocument();
    expect(screen.getByRole('navigation', { name: 'Ruta de navegación' })).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Volver a productos' })).toBeInTheDocument();
  });

  it('decrease button is disabled at quantity 1 and enabled after increase', async () => {
    const user = userEvent.setup();
    render(<ProductDetail />);

    const decreaseBtn = screen.getByRole('button', { name: 'Disminuir cantidad' });
    const increaseBtn = screen.getByRole('button', { name: 'Aumentar cantidad' });

    // Initially qty=1, so decrease must be disabled
    expect(decreaseBtn).toBeDisabled();
    expect(increaseBtn).not.toBeDisabled();

    await user.click(increaseBtn);
    // Now qty=2, decrease should be enabled
    expect(decreaseBtn).not.toBeDisabled();
  });

  it('clamps quantity outside limits and announces the adjusted value', async () => {
    const user = userEvent.setup();
    render(<ProductDetail />);

    const quantityInput = screen.getByLabelText('Cantidad');
    await user.clear(quantityInput);
    await user.type(quantityInput, '999');

    expect(quantityInput).toHaveValue(99);
    expect(screen.getByRole('status')).toHaveTextContent('Cantidad ajustada a 99');
    expect(quantityInput).toHaveAttribute('aria-describedby', 'product-quantity-notice');
  });

  it('add to cart dispatches ADD_ORDER_ITEMS and shows toast', async () => {
    const user = userEvent.setup();
    render(<ProductDetail />);

    await user.click(screen.getByRole('button', { name: 'Añadir al carrito' }));

    expect(mockDispatch).toHaveBeenCalledWith(
      expect.objectContaining({ type: 'ADD_ORDER_ITEMS' }),
    );
    expect(mockShowToast).toHaveBeenCalledWith(
      expect.stringContaining('Auriculares Bluetooth'),
      'success',
    );
  });

  it('buy now dispatches ADD_ORDER_ITEMS and navigates to checkout', async () => {
    const user = userEvent.setup();
    render(<ProductDetail />);

    await user.click(screen.getByRole('button', { name: 'Comprar ahora' }));

    expect(mockDispatch).toHaveBeenCalledWith(
      expect.objectContaining({ type: 'ADD_ORDER_ITEMS' }),
    );
    expect(mockNavigate).toHaveBeenCalledWith('/checkout');
  });

  it('favorite button has correct aria-pressed and toggles favorite on click', async () => {
    const user = userEvent.setup();
    render(<ProductDetail />);

    const favBtn = screen.getByRole('button', { name: /añadir a favoritos/i });
    expect(favBtn).toHaveAttribute('aria-pressed', 'false');

    await user.click(favBtn);
    expect(mockToggleFavorite).toHaveBeenCalledWith(MOCK_PRODUCT);
  });

  it('admin view hides buy/cart buttons and shows product heading', () => {
    mockAuthUser = { role: 'admin' };
    render(<ProductDetail />);

    expect(screen.queryByRole('button', { name: 'Añadir al carrito' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'Comprar ahora' })).not.toBeInTheDocument();
    expect(screen.getByRole('heading', { level: 1, name: 'Auriculares Bluetooth' })).toBeInTheDocument();
  });

  it('redirects to not-found when product id is invalid', () => {
    mockParamId = 'abc';
    render(<ProductDetail />);

    expect(screen.getByTestId('navigate-to')).toHaveTextContent('/not-found');
  });
});
