// Generated by GitHub Copilot
// Para que sirve: Pagina de registro con validaciones de contrasena y confirmacion.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import useAuth from '../context/useAuth';
import useCart from '../context/useCart';
import useLanguage from '../context/useLanguage';
import useDocumentTitle from '../hooks/useDocumentTitle';

/**
 * Registration page to create a new local account.
 * Accessibility: labels and alerts are provided for all fields and errors.
 */
export default function Register() {
  const { t } = useLanguage();
  // WCAG 2.4.2: descriptive page title announced by screen readers on navigation.
  useDocumentTitle(t('common.registerAccount'));
  const { isAuthenticated, register } = useAuth();
  const { showToast } = useCart();
  const navigate = useNavigate();

  const [form, setForm] = useState({
    name: '',
    email: '',
    role: 'cliente',
    password: '',
    confirmPassword: '',
  });
  const [error, setError] = useState('');
  const [fieldErrors, setFieldErrors] = useState({});
  const [touched, setTouched] = useState({});
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  if (isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  /**
   * Calculates password strength on a 0-4 scale with specific feedback tips.
   * @param {string} pwd
   * @returns {{ score: number, label: string, color: string, tips: string[] }}
   */
  const getPasswordStrength = (pwd) => {
    if (!pwd) return { score: 0, label: '', color: '', tips: [] };
    let score = 0;
    const tips = [];
    
    // Check each requirement and add specific feedback
    if (pwd.length >= 8) {
      score += 1;
    } else {
      tips.push(t('common.tipMinChars', { min: 8, current: pwd.length }));
    }
    
    if (/[a-z]/.test(pwd)) {
      score += 1;
    } else {
      tips.push(t('common.tipLower'));
    }
    
    if (/[A-Z]/.test(pwd)) {
      score += 1;
    } else {
      tips.push(t('common.tipUpper'));
    }
    
    if (/\d/.test(pwd)) {
      score += 1;
    } else {
      tips.push(t('common.tipNumber'));
    }
    
    const labels = ['', t('common.strengthWeak'), t('common.strengthRegular'), t('common.strengthGood'), t('common.strengthStrong')];
    const colors = ['', 'bg-red-400', 'bg-orange-400', 'bg-yellow-400', 'bg-green-500'];
    return { score, label: labels[score], color: colors[score], tips };
  };

  const passwordStrength = getPasswordStrength(form.password);

  /** Returns an inline validation error message for one register field. */
  const validateField = (name, value, nextForm = form) => {
    if (name === 'name') {
      if (!value.trim()) return t('common.nameRequired');
      if (value.trim().length < 2) return t('common.nameMin');
      return undefined;
    }

    if (name === 'email') {
      const safeEmail = value.trim();
      if (!safeEmail) return t('common.requiredEmail');
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(safeEmail)) return t('common.invalidEmail');
      return undefined;
    }

    if (name === 'role') {
      if (value !== 'admin' && value !== 'cliente') return t('common.invalidRole');
      return undefined;
    }

    if (name === 'password') {
      if (!value) return t('common.passwordRequired');
      if (!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/.test(value)) {
        return t('common.strongPasswordHint');
      }
      return undefined;
    }

    if (name === 'confirmPassword') {
      if (!value) return t('common.confirmPasswordRequired');
      if (value !== nextForm.password) return t('common.passwordsMismatch');
      return undefined;
    }

    return undefined;
  };

  /** Updates one input and validates it in real time once touched. */
  const handleInputChange = (name, value) => {
    const nextForm = { ...form, [name]: value };
    setForm(nextForm);

    if (touched[name] || (name === 'password' && touched.confirmPassword)) {
      setFieldErrors((prev) => ({
        ...prev,
        [name]: validateField(name, value, nextForm),
        ...(name === 'password' && touched.confirmPassword
          ? { confirmPassword: validateField('confirmPassword', nextForm.confirmPassword, nextForm) }
          : {}),
      }));
    }

    if (error) setError('');
  };

  /** Marks one input as touched and validates it. */
  const handleBlur = (name) => {
    setTouched((prev) => ({ ...prev, [name]: true }));
    setFieldErrors((prev) => ({ ...prev, [name]: validateField(name, form[name], form) }));
  };

  /** Handles user registration and redirects to home on success. */
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (isSubmitting) {
      return;
    }

    const nextErrors = {
      name: validateField('name', form.name, form),
      email: validateField('email', form.email, form),
      role: validateField('role', form.role, form),
      password: validateField('password', form.password, form),
      confirmPassword: validateField('confirmPassword', form.confirmPassword, form),
    };

    setTouched({ name: true, email: true, role: true, password: true, confirmPassword: true });
    setFieldErrors(nextErrors);

    if (Object.values(nextErrors).some(Boolean)) {
      return;
    }

    setIsSubmitting(true);
    const result = await register(form);

    if (!result.ok) {
      const message = result.error || t('common.completeRegisterFailed');
      setError(message);
      showToast(message, 'error');
      setIsSubmitting(false);
      return;
    }

    setError('');
    showToast(t('common.accountCreated'), 'success');
    navigate('/', { replace: true });
  };

  return (
    <main className="min-h-[calc(100vh-4rem)] flex items-center justify-center px-4 py-10 bg-gray-50">
      <section className="w-full max-w-md rounded-2xl bg-white p-6 shadow" aria-label={t('common.registerFormLabel')}>
        <h1 className="text-2xl font-bold text-gray-900 mb-2">{t('common.registerAccount')}</h1>
        <p className="text-sm text-gray-500 mb-6">{t('common.registerToShop')}</p>

        <form onSubmit={handleSubmit} className="flex flex-col gap-4" noValidate>
          <div className="flex flex-col gap-1">
            <label htmlFor="name" className="text-sm font-medium text-gray-700">{t('common.name')}</label>
            <input
              id="name"
              type="text"
              name="name"
              autoComplete="name"
              value={form.name}
              onChange={(e) => handleInputChange('name', e.target.value)}
              onBlur={() => handleBlur('name')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.name && fieldErrors.name ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              minLength={2}
              aria-invalid={Boolean(touched.name && fieldErrors.name)}
              aria-describedby={touched.name && fieldErrors.name ? 'name-error' : undefined}
              required
            />
            {touched.name && fieldErrors.name && (
              <p id="name-error" className="text-xs text-red-600" role="alert">{fieldErrors.name}</p>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="email" className="text-sm font-medium text-gray-700">{t('common.email')}</label>
            <input
              id="email"
              type="email"
              name="email"
              autoComplete="email"
              value={form.email}
              onChange={(e) => handleInputChange('email', e.target.value)}
              onBlur={() => handleBlur('email')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.email && fieldErrors.email ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              aria-invalid={Boolean(touched.email && fieldErrors.email)}
              aria-describedby={touched.email && fieldErrors.email ? 'register-email-error' : undefined}
              required
            />
            {touched.email && fieldErrors.email && (
              <p id="register-email-error" className="text-xs text-red-600" role="alert">{fieldErrors.email}</p>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="role" className="text-sm font-medium text-gray-700">{t('common.role')}</label>
            <select
              id="role"
              name="role"
              value={form.role}
              onChange={(e) => handleInputChange('role', e.target.value)}
              onBlur={() => handleBlur('role')}
              className={`rounded-lg border px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.role && fieldErrors.role ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              aria-invalid={Boolean(touched.role && fieldErrors.role)}
              aria-describedby={touched.role && fieldErrors.role ? 'register-role-error' : undefined}
              required
            >
              <option value="cliente">{t('common.roleClient')}</option>
              <option value="admin">{t('common.roleAdmin')}</option>
            </select>
            {touched.role && fieldErrors.role && (
              <p id="register-role-error" className="text-xs text-red-600" role="alert">{fieldErrors.role}</p>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="password" className="text-sm font-medium text-gray-700">{t('common.password')}</label>
            <input
              id="password"
              type={showPassword ? 'text' : 'password'}
              name="password"
              value={form.password}
              onChange={(e) => handleInputChange('password', e.target.value)}
              onBlur={() => handleBlur('password')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.password && fieldErrors.password ? 'border-red-400' : 'border-gray-300'
              }`}
              autoComplete="new-password"
              disabled={isSubmitting}
              minLength={8}
              pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}"
              title={t('common.minPasswordTitle')}
              aria-invalid={Boolean(touched.password && fieldErrors.password)}
              aria-describedby={[
                touched.password && fieldErrors.password ? 'register-password-error' : null,
                form.password ? 'register-password-strength' : null,
              ].filter(Boolean).join(' ') || undefined}
              required
            />
            <button
              type="button"
              onClick={() => setShowPassword((prev) => !prev)}
              className="mt-1 text-xs text-indigo-600 hover:text-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 w-fit"
              aria-label={showPassword ? t('common.hidePassword') : t('common.showPassword')}
            >
              {showPassword ? t('common.hidePassword') : t('common.showPassword')}
            </button>
            {form.password && (
              <div id="register-password-strength" role="status" className="mt-1">
                <div className="flex gap-1 mb-1" aria-hidden="true">
                  {[1, 2, 3, 4].map((step) => (
                    <div
                      key={step}
                      className={`h-1.5 flex-1 rounded-full transition-colors ${
                        step <= passwordStrength.score ? passwordStrength.color : 'bg-gray-200'
                      }`}
                    />
                  ))}
                </div>
                <p className="text-xs text-gray-500">
                  {t('common.passwordStrength')}: <span className="font-medium">{passwordStrength.label}</span>
                </p>
                {passwordStrength.tips && passwordStrength.tips.length > 0 && (
                  <ul className="mt-1 space-y-0.5" role="list">
                    {passwordStrength.tips.map((tip) => (
                      <li key={tip} className="text-xs text-amber-700 flex items-center gap-1">
                        <span className="text-amber-600">✗</span> {tip}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            )}
            {touched.password && fieldErrors.password && (
              <p id="register-password-error" className="text-xs text-red-600" role="alert">{fieldErrors.password}</p>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="confirmPassword" className="text-sm font-medium text-gray-700">{t('common.confirmPassword')}</label>
            <input
              id="confirmPassword"
              type={showConfirmPassword ? 'text' : 'password'}
              name="confirmPassword"
              autoComplete="new-password"
              value={form.confirmPassword}
              onChange={(e) => handleInputChange('confirmPassword', e.target.value)}
              onBlur={() => handleBlur('confirmPassword')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.confirmPassword && fieldErrors.confirmPassword ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              minLength={8}
              aria-invalid={Boolean(touched.confirmPassword && fieldErrors.confirmPassword)}
              aria-describedby={touched.confirmPassword && fieldErrors.confirmPassword ? 'register-confirm-password-error' : undefined}
              required
            />
            <button
              type="button"
              onClick={() => setShowConfirmPassword((prev) => !prev)}
              className="mt-1 text-xs text-indigo-600 hover:text-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 w-fit"
              aria-label={showConfirmPassword ? t('common.hideConfirmation') : t('common.showConfirmation')}
            >
              {showConfirmPassword ? t('common.hideConfirmation') : t('common.showConfirmation')}
            </button>
            {touched.confirmPassword && fieldErrors.confirmPassword && (
              <p id="register-confirm-password-error" className="text-xs text-red-600" role="alert">{fieldErrors.confirmPassword}</p>
            )}
          </div>

          {error && (
            <p className="text-sm text-red-600" role="alert">{error}</p>
          )}

          <button
            type="submit"
            disabled={isSubmitting}
            className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            {isSubmitting ? t('common.registering') : t('common.register')}
          </button>
        </form>

        <p className="mt-5 text-sm text-gray-600">
          {t('common.alreadyHaveAccount')}{' '}
          <Link
            to="/login"
            className="font-medium text-indigo-600 underline underline-offset-2 hover:text-indigo-700"
          >
            {t('common.login')}
          </Link>
        </p>
      </section>
    </main>
  );
}
