// Generated by GitHub Copilot
// Para que sirve: Pagina de registro con validaciones de contrasena y confirmacion.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import useAuth from '../context/useAuth';
import useCart from '../context/useCart';
import useDocumentTitle from '../hooks/useDocumentTitle';

/**
 * Registration page to create a new local account.
 * Accessibility: labels and alerts are provided for all fields and errors.
 */
export default function Register() {
  // WCAG 2.4.2: descriptive page title announced by screen readers on navigation.
  useDocumentTitle('Registro');
  const { isAuthenticated, register } = useAuth();
  const { showToast } = useCart();
  const navigate = useNavigate();

  const [form, setForm] = useState({
    name: '',
    email: '',
    password: '',
    confirmPassword: '',
  });
  const [error, setError] = useState('');
  const [fieldErrors, setFieldErrors] = useState({});
  const [touched, setTouched] = useState({});
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  if (isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  /**
   * Calculates password strength on a 0-4 scale for the visual meter.
   * @param {string} pwd
   * @returns {{ score: number, label: string, color: string }}
   */
  const getPasswordStrength = (pwd) => {
    if (!pwd) return { score: 0, label: '', color: '' };
    let score = 0;
    if (pwd.length >= 8) score += 1;
    if (/[a-z]/.test(pwd)) score += 1;
    if (/[A-Z]/.test(pwd)) score += 1;
    if (/\d/.test(pwd)) score += 1;
    const labels = ['', 'DÃ©bil', 'Regular', 'Buena', 'Fuerte'];
    const colors = ['', 'bg-red-400', 'bg-orange-400', 'bg-yellow-400', 'bg-green-500'];
    return { score, label: labels[score], color: colors[score] };
  };

  const passwordStrength = getPasswordStrength(form.password);

  /** Returns an inline validation error message for one register field. */
  const validateField = (name, value, nextForm = form) => {
    if (name === 'name') {
      if (!value.trim()) return 'El nombre es obligatorio.';
      if (value.trim().length < 2) return 'El nombre debe tener al menos 2 caracteres.';
      return undefined;
    }

    if (name === 'email') {
      const safeEmail = value.trim();
      if (!safeEmail) return 'El correo es obligatorio.';
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(safeEmail)) return 'Ingresa un correo vÃ¡lido.';
      return undefined;
    }

    if (name === 'password') {
      if (!value) return 'La contraseÃ±a es obligatoria.';
      if (!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/.test(value)) {
        return 'Usa 8+ caracteres, mayÃºscula, minÃºscula y nÃºmero.';
      }
      return undefined;
    }

    if (name === 'confirmPassword') {
      if (!value) return 'Debes confirmar la contraseÃ±a.';
      if (value !== nextForm.password) return 'Las contraseÃ±as no coinciden.';
      return undefined;
    }

    return undefined;
  };

  /** Updates one input and validates it in real time once touched. */
  const handleInputChange = (name, value) => {
    const nextForm = { ...form, [name]: value };
    setForm(nextForm);

    if (touched[name] || (name === 'password' && touched.confirmPassword)) {
      setFieldErrors((prev) => ({
        ...prev,
        [name]: validateField(name, value, nextForm),
        ...(name === 'password' && touched.confirmPassword
          ? { confirmPassword: validateField('confirmPassword', nextForm.confirmPassword, nextForm) }
          : {}),
      }));
    }

    if (error) setError('');
  };

  /** Marks one input as touched and validates it. */
  const handleBlur = (name) => {
    setTouched((prev) => ({ ...prev, [name]: true }));
    setFieldErrors((prev) => ({ ...prev, [name]: validateField(name, form[name], form) }));
  };

  /** Handles user registration and redirects to home on success. */
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (isSubmitting) {
      return;
    }

    const nextErrors = {
      name: validateField('name', form.name, form),
      email: validateField('email', form.email, form),
      password: validateField('password', form.password, form),
      confirmPassword: validateField('confirmPassword', form.confirmPassword, form),
    };

    setTouched({ name: true, email: true, password: true, confirmPassword: true });
    setFieldErrors(nextErrors);

    if (Object.values(nextErrors).some(Boolean)) {
      return;
    }

    setIsSubmitting(true);
    const result = await register(form);

    if (!result.ok) {
      const message = result.error || 'No se pudo completar el registro.';
      setError(message);
      showToast(message, 'error');
      setIsSubmitting(false);
      return;
    }

    setError('');
    showToast('Cuenta creada correctamente', 'success');
    navigate('/', { replace: true });
  };

  return (
    <main className="min-h-[calc(100vh-4rem)] flex items-center justify-center px-4 py-10 bg-gray-50">
      <section className="w-full max-w-md rounded-2xl bg-white p-6 shadow" aria-label="Formulario de registro">
        <h1 className="text-2xl font-bold text-gray-900 mb-2">Crear cuenta</h1>
        <p className="text-sm text-gray-500 mb-6">RegÃ­strate para comprar y gestionar tus pedidos.</p>

        <form onSubmit={handleSubmit} className="flex flex-col gap-4" noValidate>
          <div className="flex flex-col gap-1">
            <label htmlFor="name" className="text-sm font-medium text-gray-700">Nombre</label>
            <input
              id="name"
              type="text"
              name="name"
              autoComplete="name"
              value={form.name}
              onChange={(e) => handleInputChange('name', e.target.value)}
              onBlur={() => handleBlur('name')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.name && fieldErrors.name ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              minLength={2}
              aria-invalid={Boolean(touched.name && fieldErrors.name)}
              aria-describedby={touched.name && fieldErrors.name ? 'name-error' : undefined}
              required
            />
            {touched.name && fieldErrors.name && (
              <p id="name-error" className="text-xs text-red-600" role="alert">{fieldErrors.name}</p>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="email" className="text-sm font-medium text-gray-700">Correo electrÃ³nico</label>
            <input
              id="email"
              type="email"
              name="email"
              autoComplete="email"
              value={form.email}
              onChange={(e) => handleInputChange('email', e.target.value)}
              onBlur={() => handleBlur('email')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.email && fieldErrors.email ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              aria-invalid={Boolean(touched.email && fieldErrors.email)}
              aria-describedby={touched.email && fieldErrors.email ? 'register-email-error' : undefined}
              required
            />
            {touched.email && fieldErrors.email && (
              <p id="register-email-error" className="text-xs text-red-600" role="alert">{fieldErrors.email}</p>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="password" className="text-sm font-medium text-gray-700">ContraseÃ±a</label>
            <input
              id="password"
              type={showPassword ? 'text' : 'password'}
              name="password"
              value={form.password}
              onChange={(e) => handleInputChange('password', e.target.value)}
              onBlur={() => handleBlur('password')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.password && fieldErrors.password ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              minLength={8}
              pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}"
              title="MÃ­nimo 8 caracteres, incluyendo mayÃºscula, minÃºscula y nÃºmero."
              aria-invalid={Boolean(touched.password && fieldErrors.password)}
              aria-describedby={touched.password && fieldErrors.password ? 'register-password-error' : undefined}
              required
            />
            <button
              type="button"
              onClick={() => setShowPassword((prev) => !prev)}
              className="mt-1 text-xs text-indigo-600 hover:text-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 w-fit"
              aria-label={showPassword ? 'Ocultar contraseÃ±a' : 'Mostrar contraseÃ±a'}
            >
              {showPassword ? 'Ocultar contraseÃ±a' : 'Mostrar contraseÃ±a'}
            </button>
            {form.password && (
              <div className="mt-1" aria-label={`Fortaleza de contraseÃ±a: ${passwordStrength.label}`}>
                <div className="flex gap-1 mb-1" aria-hidden="true">
                  {[1, 2, 3, 4].map((step) => (
                    <div
                      key={step}
                      className={`h-1.5 flex-1 rounded-full transition-colors ${
                        step <= passwordStrength.score ? passwordStrength.color : 'bg-gray-200'
                      }`}
                    />
                  ))}
                </div>
                <p className="text-xs text-gray-500">
                  Fortaleza: <span className="font-medium">{passwordStrength.label}</span>
                </p>
              </div>
            )}
            {touched.password && fieldErrors.password && (
              <p id="register-password-error" className="text-xs text-red-600" role="alert">{fieldErrors.password}</p>
            )}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="confirmPassword" className="text-sm font-medium text-gray-700">Confirmar contraseÃ±a</label>
            <input
              id="confirmPassword"
              type={showConfirmPassword ? 'text' : 'password'}
              name="confirmPassword"
              autoComplete="new-password"
              value={form.confirmPassword}
              onChange={(e) => handleInputChange('confirmPassword', e.target.value)}
              onBlur={() => handleBlur('confirmPassword')}
              className={`rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                touched.confirmPassword && fieldErrors.confirmPassword ? 'border-red-400' : 'border-gray-300'
              }`}
              disabled={isSubmitting}
              minLength={8}
              aria-invalid={Boolean(touched.confirmPassword && fieldErrors.confirmPassword)}
              aria-describedby={touched.confirmPassword && fieldErrors.confirmPassword ? 'register-confirm-password-error' : undefined}
              required
            />
            <button
              type="button"
              onClick={() => setShowConfirmPassword((prev) => !prev)}
              className="mt-1 text-xs text-indigo-600 hover:text-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 w-fit"
              aria-label={showConfirmPassword ? 'Ocultar confirmaciÃ³n' : 'Mostrar confirmaciÃ³n'}
            >
              {showConfirmPassword ? 'Ocultar confirmaciÃ³n' : 'Mostrar confirmaciÃ³n'}
            </button>
            {touched.confirmPassword && fieldErrors.confirmPassword && (
              <p id="register-confirm-password-error" className="text-xs text-red-600" role="alert">{fieldErrors.confirmPassword}</p>
            )}
          </div>

          {error && (
            <p className="text-sm text-red-600" role="alert">{error}</p>
          )}

          <button
            type="submit"
            disabled={isSubmitting}
            className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            {isSubmitting ? 'Creando cuenta...' : 'Registrarme'}
          </button>
        </form>

        <p className="mt-5 text-sm text-gray-600">
          Â¿Ya tienes cuenta?{' '}
          <Link
            to="/login"
            className="font-medium text-indigo-600 underline underline-offset-2 hover:text-indigo-700"
          >
            Inicia sesiÃ³n
          </Link>
        </p>
      </section>
    </main>
  );
}
