// Generated by GitHub Copilot
import { memo } from 'react';
import { Link } from 'react-router-dom';
import useLanguage from '../context/useLanguage';

/**
 * Footer component with company info, links, and social media.
 * Displayed at the bottom of every page after authentication.
 */
// Generated by GitHub Copilot
// memo prevents re-renders when parent context updates don't affect footer content.
function Footer() {
  const { t } = useLanguage();

  return (
    <footer className="bg-gray-900 text-gray-100 mt-16">
      <div className="max-w-6xl mx-auto px-4 py-12">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 mb-8">
          {/* Marca */}
          <div>
            <h2 className="text-lg font-bold text-white mb-3">TiendaReact</h2>
            <p className="text-sm text-gray-400">
              {t('footer.description')}
            </p>
          </div>

          {/* Navegación */}
          <div>
            <h3 className="font-semibold text-white mb-3">{t('footer.navigation')}</h3>
            <ul className="flex flex-col gap-2 text-sm" role="list">
              <li>
                <Link to="/" className="text-gray-400 hover:text-indigo-400 transition">
                  {t('navbar.home')}
                </Link>
              </li>
              <li>
                <Link to="/carrito" className="text-gray-400 hover:text-indigo-400 transition">
                  {t('navbar.cart')}
                </Link>
              </li>
              <li>
                <Link to="/favoritos" className="text-gray-400 hover:text-indigo-400 transition">
                  {t('navbar.favorites')}
                </Link>
              </li>
              <li>
                <Link to="/pedidos" className="text-gray-400 hover:text-indigo-400 transition">
                  {t('orders.title')}
                </Link>
              </li>
            </ul>
          </div>

          {/* Información */}
          <div>
            <h3 className="font-semibold text-white mb-3">{t('footer.information')}</h3>
            <ul className="flex flex-col gap-2 text-sm" role="list">
              <li>
                <a href="mailto:contacto@tiendareact.com" className="text-gray-400 hover:text-indigo-400 transition">
                  {t('footer.contact')}
                </a>
              </li>
              <li>
                <Link to="/legal#terms" className="text-gray-400 hover:text-indigo-400 transition">
                  {t('footer.terms')}
                </Link>
              </li>
              <li>
                <Link to="/legal#privacy" className="text-gray-400 hover:text-indigo-400 transition">
                  {t('footer.privacy')}
                </Link>
              </li>
              <li>
                <Link to="/legal#returns" className="text-gray-400 hover:text-indigo-400 transition">
                  {t('footer.returns')}
                </Link>
              </li>
            </ul>
          </div>

          {/* Redes sociales */}
          <div>
            <h3 className="font-semibold text-white mb-3">{t('footer.followUs')}</h3>
            <ul className="flex gap-3" role="list">
              <li>
                <a href="https://www.facebook.com" target="_blank" rel="noopener noreferrer" className="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center hover:bg-indigo-600 transition" aria-label={t('footer.socialFacebook')}>
                  f
                </a>
              </li>
              <li>
                <a href="https://x.com" target="_blank" rel="noopener noreferrer" className="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center hover:bg-indigo-600 transition" aria-label={t('footer.socialTwitter')}>
                  t
                </a>
              </li>
              <li>
                <a href="https://www.instagram.com" target="_blank" rel="noopener noreferrer" className="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center hover:bg-indigo-600 transition" aria-label={t('footer.socialInstagram')}>
                  i
                </a>
              </li>
            </ul>
          </div>
        </div>

        {/* Divider */}
        <div className="border-t border-gray-800 pt-8">
          <p className="text-center text-sm text-gray-500">
            © {new Date().getFullYear()} TiendaReact. {t('footer.rightsReserved')}
          </p>
        </div>
      </div>
    </footer>
  );
}

export default memo(Footer);
