// Generated by GitHub Copilot
import { Link } from 'react-router-dom';

/**
 * Footer component with company info, links, and social media.
 * Displayed at the bottom of every page after authentication.
 */
export default function Footer() {
  return (
    <footer className="bg-gray-900 text-gray-100 mt-16">
      <div className="max-w-6xl mx-auto px-4 py-12">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 mb-8">
          {/* Marca */}
          <div>
            <h2 className="text-lg font-bold text-white mb-3">🛍️ TiendaReact</h2>
            <p className="text-sm text-gray-400">
              Tu tienda de confianza para productos electrónicos, deportivos y accesorios de calidad.
            </p>
          </div>

          {/* Navegación */}
          <div>
            <h3 className="font-semibold text-white mb-3">Navegación</h3>
            <ul className="flex flex-col gap-2 text-sm" role="list">
              <li>
                <Link to="/" className="text-gray-400 hover:text-indigo-400 transition">
                  Productos
                </Link>
              </li>
              <li>
                <Link to="/carrito" className="text-gray-400 hover:text-indigo-400 transition">
                  Carrito
                </Link>
              </li>
              <li>
                <Link to="/favoritos" className="text-gray-400 hover:text-indigo-400 transition">
                  Favoritos
                </Link>
              </li>
              <li>
                <Link to="/pedidos" className="text-gray-400 hover:text-indigo-400 transition">
                  Mis Pedidos
                </Link>
              </li>
            </ul>
          </div>

          {/* Información */}
          <div>
            <h3 className="font-semibold text-white mb-3">Información</h3>
            <ul className="flex flex-col gap-2 text-sm" role="list">
              <li>
                <a href="mailto:contacto@tiendareact.com" className="text-gray-400 hover:text-indigo-400 transition">
                  Contacto
                </a>
              </li>
              <li>
                <a href="#" className="text-gray-400 hover:text-indigo-400 transition">
                  Términos y condiciones
                </a>
              </li>
              <li>
                <a href="#" className="text-gray-400 hover:text-indigo-400 transition">
                  Política de privacidad
                </a>
              </li>
              <li>
                <a href="#" className="text-gray-400 hover:text-indigo-400 transition">
                  Cambios y devoluciones
                </a>
              </li>
            </ul>
          </div>

          {/* Redes sociales */}
          <div>
            <h3 className="font-semibold text-white mb-3">Síguenos</h3>
            <ul className="flex gap-3" role="list">
              <li>
                <a href="#" className="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center hover:bg-indigo-600 transition" aria-label="Facebook">
                  f
                </a>
              </li>
              <li>
                <a href="#" className="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center hover:bg-indigo-600 transition" aria-label="Twitter">
                  𝕏
                </a>
              </li>
              <li>
                <a href="#" className="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center hover:bg-indigo-600 transition" aria-label="Instagram">
                  📷
                </a>
              </li>
            </ul>
          </div>
        </div>

        {/* Divider */}
        <div className="border-t border-gray-800 pt-8">
          <p className="text-center text-sm text-gray-500">
            © {new Date().getFullYear()} TiendaReact. Todos los derechos reservados.
          </p>
        </div>
      </div>
    </footer>
  );
}
