// Generated by GitHub Copilot
import '@testing-library/jest-dom/vitest';
import { cleanup, render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import Footer from './Footer';

vi.mock('../context/useLanguage', () => ({
  default: () => ({
    t: (key) => {
      const map = {
        'footer.description': 'Tienda de confianza.',
        'footer.navigation': 'Navegación',
        'footer.information': 'Información',
        'footer.contact': 'Contacto',
        'footer.terms': 'Términos y condiciones',
        'footer.privacy': 'Política de privacidad',
        'footer.returns': 'Cambios y devoluciones',
        'footer.followUs': 'Síguenos',
        'footer.rightsReserved': 'Todos los derechos reservados.',
        'footer.socialFacebook': 'Facebook',
        'footer.socialTwitter': 'Twitter',
        'footer.socialInstagram': 'Instagram',
        'navbar.home': 'Productos',
        'navbar.cart': 'Carrito',
        'navbar.favorites': 'Favoritos',
        'orders.title': 'Pedidos',
      };
      return map[key] ?? key;
    },
  }),
}));

afterEach(() => {
  cleanup();
});

describe('Footer integration', () => {
  it('renders legal links with hash targets', () => {
    render(
      <MemoryRouter>
        <Footer />
      </MemoryRouter>,
    );

    expect(screen.getByRole('link', { name: 'Términos y condiciones' })).toHaveAttribute('href', '/legal#terms');
    expect(screen.getByRole('link', { name: 'Política de privacidad' })).toHaveAttribute('href', '/legal#privacy');
    expect(screen.getByRole('link', { name: 'Cambios y devoluciones' })).toHaveAttribute('href', '/legal#returns');
  });

  it('renders social links with safe external link attributes', () => {
    render(
      <MemoryRouter>
        <Footer />
      </MemoryRouter>,
    );

    const facebook = screen.getByRole('link', { name: 'Facebook' });
    const twitter = screen.getByRole('link', { name: 'Twitter' });
    const instagram = screen.getByRole('link', { name: 'Instagram' });

    expect(facebook).toHaveAttribute('href', 'https://www.facebook.com');
    expect(twitter).toHaveAttribute('href', 'https://x.com');
    expect(instagram).toHaveAttribute('href', 'https://www.instagram.com');

    [facebook, twitter, instagram].forEach((link) => {
      expect(link).toHaveAttribute('target', '_blank');
      expect(link).toHaveAttribute('rel', 'noopener noreferrer');
    });
  });
});
