// Generated by GitHub Copilot
import { Link, useLocation } from 'react-router-dom';
import { useCart } from '../context/CartContext';

/**
 * Navbar component with accessible navigation links and cart badge.
 * Highlights the active route for better orientation.
 */
export default function Navbar() {
  const { totalItems } = useCart();
  const { pathname } = useLocation();

  const linkClass = (path) =>
    `font-medium transition-colors ${
      pathname === path ? 'text-indigo-600' : 'text-gray-600 hover:text-indigo-600'
    }`;

  return (
    <header className="sticky top-0 z-50 bg-white shadow-sm">
      <nav
        className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between"
        aria-label="Navegación principal"
      >
        {/* Brand */}
        <Link
          to="/"
          className="text-xl font-bold text-indigo-600 focus-visible:outline-2 focus-visible:outline-indigo-600 rounded"
          aria-label="Ir a inicio"
        >
          🛍️ TiendaReact
        </Link>

        {/* Links */}
        <ul className="flex items-center gap-6" role="list">
          <li>
            <Link to="/" className={linkClass('/')} aria-current={pathname === '/' ? 'page' : undefined}>
              Productos
            </Link>
          </li>
          <li>
            <Link
              to="/carrito"
              className={`relative flex items-center gap-1 font-medium transition-colors ${
                pathname === '/carrito' ? 'text-indigo-600' : 'text-gray-600 hover:text-indigo-600'
              }`}
              aria-current={pathname === '/carrito' ? 'page' : undefined}
              aria-label={`Carrito, ${totalItems} producto${totalItems !== 1 ? 's' : ''}`}
            >
              🛒 Carrito
              {totalItems > 0 && (
                <span
                  className="absolute -top-2 -right-3 bg-indigo-600 text-white text-xs font-bold rounded-full w-5 h-5 flex items-center justify-center"
                  aria-hidden="true"
                >
                  {totalItems}
                </span>
              )}
            </Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}
