// Generated by GitHub Copilot
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useEffect, useRef, useState } from 'react';
import useCart from '../context/useCart';
import useAuth from '../context/useAuth';
import useLanguage from '../context/useLanguage';

const FOCUSABLE_SELECTOR = 'a[href], button:not([disabled]), select:not([disabled]), input:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';

/**
 * Navbar component with accessible navigation links and cart badge.
 * Highlights the active route for better orientation.
 */
export default function Navbar() {
  const { totalItems, favoriteCount } = useCart();
  const { user, logout } = useAuth();
  const { language, languages, setLanguage, t } = useLanguage();
  const isAdmin = user?.role === 'admin';
  const navigate = useNavigate();
  const { pathname } = useLocation();
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const mobileMenuRef = useRef(null);
  const mobileMenuToggleButtonRef = useRef(null);
  const wasMobileMenuOpenRef = useRef(false);

  /** Ends session and routes user to login view. */
  const handleLogout = () => {
    logout({
      broadcastNotice: {
        message: t('navbar.manualLogoutNotice'),
        type: 'info',
        code: 'manual_logout',
      },
    });
    navigate('/login', { replace: true });
  };

  const linkClass = (path) =>
    `font-medium transition-colors ${
      pathname === path ? 'text-indigo-600' : 'text-gray-600 hover:text-indigo-600'
    }`;

  const languageLabel = t('navbar.language');
  const signOutLabel = t('navbar.signOut');

  /** Updates app language from the selector. */
  const handleChangeLanguage = (event) => {
    setLanguage(event.target.value);
  };

  /** Toggles the responsive navigation drawer. */
  const handleToggleMobileMenu = () => {
    setIsMobileMenuOpen((prev) => !prev);
  };

  /** Closes mobile menu after navigation action. */
  const handleCloseMobileMenu = () => {
    setIsMobileMenuOpen(false);
  };

  useEffect(() => {
    if (!isMobileMenuOpen) {
      return undefined;
    }

    /** Handles keyboard interactions while mobile menu is open. */
    const handleMenuKeyDown = (event) => {
      if (event.key === 'Escape') {
        setIsMobileMenuOpen(false);
        return;
      }

      if (event.key !== 'Tab') {
        return;
      }

      const focusableElements = mobileMenuRef.current?.querySelectorAll(FOCUSABLE_SELECTOR);
      if (!focusableElements || focusableElements.length === 0) {
        return;
      }

      const firstElement = focusableElements[0];
      const lastElement = focusableElements[focusableElements.length - 1];

      if (event.shiftKey && document.activeElement === firstElement) {
        event.preventDefault();
        lastElement.focus();
        return;
      }

      if (!event.shiftKey && document.activeElement === lastElement) {
        event.preventDefault();
        firstElement.focus();
      }
    };

    window.addEventListener('keydown', handleMenuKeyDown);
    return () => {
      window.removeEventListener('keydown', handleMenuKeyDown);
    };
  }, [isMobileMenuOpen]);

  useEffect(() => {
    if (!isMobileMenuOpen) {
      return undefined;
    }

    /** Closes menu when user taps/clicks outside mobile panel and toggle button. */
    const handlePointerDownOutside = (event) => {
      const eventTarget = event.target;
      const clickedInsideMenu = mobileMenuRef.current?.contains(eventTarget);
      const clickedToggleButton = mobileMenuToggleButtonRef.current?.contains(eventTarget);

      if (!clickedInsideMenu && !clickedToggleButton) {
        setIsMobileMenuOpen(false);
      }
    };

    window.addEventListener('pointerdown', handlePointerDownOutside);
    return () => {
      window.removeEventListener('pointerdown', handlePointerDownOutside);
    };
  }, [isMobileMenuOpen]);

  useEffect(() => {
    if (!isMobileMenuOpen) {
      return;
    }

    const firstInteractiveElement = mobileMenuRef.current?.querySelector(FOCUSABLE_SELECTOR);
    firstInteractiveElement?.focus();
  }, [isMobileMenuOpen]);

  useEffect(() => {
    if (!isMobileMenuOpen) {
      if (wasMobileMenuOpenRef.current) {
        mobileMenuToggleButtonRef.current?.focus();
      }
      wasMobileMenuOpenRef.current = false;
      return;
    }

    wasMobileMenuOpenRef.current = true;
  }, [isMobileMenuOpen]);

  useEffect(() => {
    if (!isMobileMenuOpen) {
      return undefined;
    }

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';

    return () => {
      document.body.style.overflow = previousOverflow;
    };
  }, [isMobileMenuOpen]);

  return (
    <header className="sticky top-0 z-50 bg-white shadow-sm">
      <nav
        className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between"
        aria-label={t('navbar.primaryNavigation')}
      >
        <Link
          to="/"
          className="text-xl font-bold text-indigo-600 focus-visible:outline-2 focus-visible:outline-indigo-600 rounded"
          aria-label={t('navbar.goHome')}
        >
          🛍️ TiendaReact
        </Link>

        <button
          ref={mobileMenuToggleButtonRef}
          type="button"
          className="inline-flex items-center rounded-lg border border-gray-300 px-3 py-1.5 text-sm text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 md:hidden"
          aria-expanded={isMobileMenuOpen}
          aria-haspopup="menu"
          aria-controls="mobile-main-menu"
          onClick={handleToggleMobileMenu}
        >
          {isMobileMenuOpen ? t('navbar.closeMenu') : t('navbar.openMenu')}
        </button>

        <ul className="hidden items-center gap-6 md:flex" role="list">
          <li>
            <Link to="/" className={linkClass('/')} aria-current={pathname === '/' ? 'page' : undefined}>
              {t('navbar.home')}
            </Link>
          </li>
          {isAdmin && (
            <li>
              <Link to="/admin/productos" className={linkClass('/admin/productos')} aria-current={pathname === '/admin/productos' ? 'page' : undefined}>
                {t('navbar.admin')}
              </Link>
            </li>
          )}
          {!isAdmin && (
            <li>
              <Link to="/pedidos" className={linkClass('/pedidos')} aria-current={pathname === '/pedidos' ? 'page' : undefined}>
                {t('navbar.orders')}
              </Link>
            </li>
          )}
          {!isAdmin && (
            <li>
              <Link
                to="/favoritos"
                className={`relative flex items-center gap-1 font-medium transition-colors ${
                  pathname === '/favoritos' ? 'text-indigo-600' : 'text-gray-600 hover:text-indigo-600'
                }`}
                aria-current={pathname === '/favoritos' ? 'page' : undefined}
                aria-label={t('navbar.favoritesCount', {
                  count: favoriteCount,
                  suffix: favoriteCount !== 1 ? 's' : '',
                })}
              >
                ❤ {t('navbar.favorites')}
                {favoriteCount > 0 && (
                  <span
                    className="absolute -top-2 -right-3 bg-rose-500 text-white text-xs font-bold rounded-full w-5 h-5 flex items-center justify-center"
                    aria-hidden="true"
                  >
                    {favoriteCount}
                  </span>
                )}
              </Link>
            </li>
          )}
          {!isAdmin && (
            <li>
              <Link
                to="/carrito"
                className={`relative flex items-center gap-1 font-medium transition-colors ${
                  pathname === '/carrito' ? 'text-indigo-600' : 'text-gray-600 hover:text-indigo-600'
                }`}
                aria-current={pathname === '/carrito' ? 'page' : undefined}
                aria-label={t('navbar.cartCount', {
                  count: totalItems,
                  suffix: totalItems !== 1 ? 's' : '',
                })}
              >
                🛒 {t('navbar.cart')}
                {totalItems > 0 && (
                  <span
                    className="absolute -top-2 -right-3 bg-indigo-600 text-white text-xs font-bold rounded-full w-5 h-5 flex items-center justify-center"
                    aria-hidden="true"
                  >
                    {totalItems}
                  </span>
                )}
              </Link>
            </li>
          )}
          <li>
            <label className="flex items-center gap-2 text-sm text-gray-700">
              <span className="sr-only">{languageLabel}</span>
              <select
                value={language}
                onChange={handleChangeLanguage}
                aria-label={languageLabel}
                className="rounded-lg border border-gray-300 bg-white px-2 py-1.5 text-sm text-gray-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                {languages.map((item) => (
                  <option key={item.code} value={item.code}>{item.label}</option>
                ))}
              </select>
            </label>
          </li>
          <li className="hidden lg:block text-xs text-gray-500" aria-label={t('navbar.authenticatedUser')}>
            {user?.email}
          </li>
          <li>
            <button
              type="button"
              onClick={handleLogout}
              className="rounded-lg border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              aria-label={t('navbar.closeSession')}
            >
              {signOutLabel}
            </button>
          </li>
        </ul>
      </nav>

      {isMobileMenuOpen && (
        <nav
          id="mobile-main-menu"
          ref={mobileMenuRef}
          aria-label={t('navbar.mobileMenu')}
          className="border-t border-gray-200 bg-white px-4 py-4 md:hidden"
        >
          <ul className="space-y-3" role="list">
            <li>
              <Link to="/" onClick={handleCloseMobileMenu} className={linkClass('/')} aria-current={pathname === '/' ? 'page' : undefined}>
                {t('navbar.home')}
              </Link>
            </li>
            {isAdmin && (
              <li>
                <Link to="/admin/productos" onClick={handleCloseMobileMenu} className={linkClass('/admin/productos')} aria-current={pathname === '/admin/productos' ? 'page' : undefined}>
                  {t('navbar.admin')}
                </Link>
              </li>
            )}
            {!isAdmin && (
              <li>
                <Link to="/pedidos" onClick={handleCloseMobileMenu} className={linkClass('/pedidos')} aria-current={pathname === '/pedidos' ? 'page' : undefined}>
                  {t('navbar.orders')}
                </Link>
              </li>
            )}
            {!isAdmin && (
              <li>
                <Link to="/favoritos" onClick={handleCloseMobileMenu} className={linkClass('/favoritos')} aria-current={pathname === '/favoritos' ? 'page' : undefined} aria-label={t('navbar.favoritesSaved', { count: favoriteCount })}>
                  {t('navbar.favorites')}
                </Link>
              </li>
            )}
            {!isAdmin && (
              <li>
                <Link to="/carrito" onClick={handleCloseMobileMenu} className={linkClass('/carrito')} aria-current={pathname === '/carrito' ? 'page' : undefined}>
                  {t('navbar.cart')}
                </Link>
              </li>
            )}
            <li>
              <label className="flex items-center gap-2 text-sm text-gray-700">
                <span>{languageLabel}</span>
                <select
                  value={language}
                  onChange={handleChangeLanguage}
                  aria-label={languageLabel}
                  className="rounded-lg border border-gray-300 bg-white px-2 py-1.5 text-sm text-gray-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                >
                  {languages.map((item) => (
                    <option key={item.code} value={item.code}>{item.label}</option>
                  ))}
                </select>
              </label>
            </li>
            <li>
              <button
                type="button"
                onClick={handleLogout}
                className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-left text-sm font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                aria-label={t('navbar.closeSession')}
              >
                {signOutLabel}
              </button>
            </li>
          </ul>
        </nav>
      )}
    </header>
  );
}
