// Generated by GitHub Copilot
import { useNavigate } from 'react-router-dom';
import useCart from '../context/useCart';
import useAuth from '../context/useAuth';
import useLanguage from '../context/useLanguage';

/**
 * ProductCard displays a single product with an accessible "Add to cart" button.
 * @param {{ product: object, onEditProduct?: Function, onDeleteProduct?: Function }} props
 */
export default function ProductCard({ product, onEditProduct, onDeleteProduct }) {
  const navigate = useNavigate();
  const { dispatch, isFavorite, toggleFavorite, showToast } = useCart();
  const { user } = useAuth();
  const { t, formatCurrency, translateCategory, translateProductText } = useLanguage();
  const translatedName = translateProductText(product.name);

  const isAdmin = user?.role === 'admin';
  const canManageCatalog = isAdmin && typeof onEditProduct === 'function' && typeof onDeleteProduct === 'function';
  const favorite = isFavorite(product.id);

  const handleAdd = () => {
    dispatch({ type: 'ADD_ITEM', payload: product });
    showToast(t('productCard.addedToCart', { name: product.name }), 'success');
  };

  /** Muestra un resumen rapido del producto al usuario. */
  const handleView = () => {
    navigate(`/producto/${product.id}`);
  };

  /** Agrega el producto y envia al checkout para compra rapida. */
  const handleBuy = () => {
    dispatch({ type: 'ADD_ITEM', payload: product });
    showToast(t('productCard.readyToBuy', { name: product.name }), 'success');
    navigate('/checkout');
  };

  return (
    <article
      className="bg-white rounded-2xl shadow hover:shadow-md transition-shadow overflow-hidden flex flex-col"
      aria-label={t('productCard.productLabel', { name: translatedName })}
    >
      <img
        src={product.image}
        alt={translatedName}
        className="w-full h-48 object-cover"
        loading="lazy"
      />
      <div className="p-4 flex flex-col flex-1 gap-2">
        <div className="flex items-start justify-between gap-2">
          <span className="text-xs font-medium text-indigo-500 uppercase tracking-wide">
            {translateCategory(product.category)}
          </span>
          {!isAdmin && (
            <button
              type="button"
              onClick={() => toggleFavorite(product)}
              className={`rounded-full px-2 py-1 text-xs font-semibold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 ${
                favorite
                  ? 'bg-rose-100 text-rose-700 hover:bg-rose-200'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
              aria-pressed={favorite}
              aria-label={favorite
                ? t('productCard.removeFavorite', { name: translatedName })
                : t('productCard.addFavorite', { name: translatedName })}
            >
              {favorite ? t('productCard.favoriteOn') : t('productCard.favoriteOff')}
            </button>
          )}
        </div>
        <h2 className="text-gray-800 font-semibold text-base leading-tight">{translatedName}</h2>
        <p className="text-gray-500 text-sm flex-1">{translateProductText(product.description)}</p>
        <div className="flex items-center justify-between mt-2">
          <span className="text-lg font-bold text-gray-900">{formatCurrency(product.price)}</span>
        </div>
        <div className="mt-1 grid grid-cols-2 gap-2">
          <button
            type="button"
            onClick={handleView}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            aria-label={t('productCard.viewLabel', { name: translatedName })}
          >
            {t('productCard.view')}
          </button>
          {canManageCatalog ? (
            <>
              <button
                type="button"
                onClick={() => onEditProduct?.(product)}
                className="rounded-lg border border-amber-300 bg-white px-3 py-2 text-xs font-medium text-amber-700 transition hover:bg-amber-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-500"
                aria-label={t('productCard.editLabel', { name: translatedName })}
              >
                {t('productCard.edit')}
              </button>
              <button
                type="button"
                onClick={() => onDeleteProduct?.(product)}
                className="rounded-lg border border-red-300 bg-white px-3 py-2 text-xs font-medium text-red-600 transition hover:bg-red-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-500"
                aria-label={t('productCard.deleteLabel', { name: translatedName })}
              >
                {t('productCard.delete')}
              </button>
            </>
          ) : (
            <>
              {!isAdmin && (
                <>
                  <button
                    type="button"
                    onClick={handleAdd}
                    className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-medium text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                    aria-label={t('productCard.addProduct', { name: product.name })}
                  >
                    {t('productCard.addProduct')}
                  </button>
                  <button
                    type="button"
                    onClick={handleBuy}
                    className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-medium text-white transition hover:bg-emerald-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600"
                    aria-label={t('productCard.buy', { name: product.name })}
                  >
                    {t('productCard.buy')}
                  </button>
                </>
              )}
            </>
          )}
        </div>
      </div>
    </article>
  );
}
