// Generated by GitHub Copilot
// Para que sirve: Placeholder animado de tarjeta de producto para el estado de carga.
//   Evita el CLS (Cumulative Layout Shift) al mostrar bloques grises del mismo tamaño que
//   las tarjetas reales mientras se cargan los datos del catálogo.
//   Memoizado con React.memo porque no recibe props y jamas cambia durante el render.
// Flujo principal: Home/AdminProducts muestran <ProductSkeleton /> mientras loading === true.
// Dónde tocar cambios: ajusta las dimensiones de los bloques si cambia el tamaño de ProductCard.
import { memo } from 'react';
import useLanguage from '../context/useLanguage';

/**
 * Skeleton loader for product cards during data fetch.
 * Provides visual feedback that content is loading without actual data.
 * Accessibility: role="status" announces loading state to screen readers.
 */
// memo avoids re-renders since skeleton has no props that change.
function ProductSkeleton() {
  const { t } = useLanguage();
  return (
    <article
      className="bg-white rounded-2xl shadow overflow-hidden flex flex-col animate-pulse"
      role="status"
      aria-label={t('common.loading')}
    >
      {/* Image placeholder */}
      <div className="w-full h-48 bg-gray-200" />
      
      {/* Content area */}
      <div className="p-4 flex flex-col flex-1 gap-2">
        {/* Category skeleton */}
        <div className="h-3 bg-gray-200 rounded w-20" />
        
        {/* Title skeleton */}
        <div className="space-y-2 mt-2">
          <div className="h-4 bg-gray-200 rounded w-full" />
          <div className="h-4 bg-gray-200 rounded w-3/4" />
        </div>
        
        {/* Price & buttons area */}
        <div className="mt-auto pt-2 space-y-2">
          <div className="h-5 bg-gray-200 rounded w-24" />
          <div className="flex gap-2 mt-2">
            <div className="h-9 bg-gray-200 rounded flex-1" />
            <div className="h-9 bg-gray-200 rounded flex-1" />
          </div>
        </div>
      </div>
    </article>
  );
}

export default memo(ProductSkeleton);
