// Generated by GitHub Copilot
import '@testing-library/jest-dom/vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import ProductCard from './ProductCard';

const mockNavigate = vi.fn();
const mockDispatch = vi.fn();
const mockToggleFavorite = vi.fn();
const mockShowToast = vi.fn();
const mockOnEditProduct = vi.fn();
const mockOnDeleteProduct = vi.fn();
const mockOnDuplicateProduct = vi.fn();

vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom');
  return {
    ...actual,
    useNavigate: () => mockNavigate,
  };
});

vi.mock('../context/useCart', () => ({
  default: () => ({
    cart: [],
    dispatch: mockDispatch,
    isFavorite: () => false,
    toggleFavorite: mockToggleFavorite,
    showToast: mockShowToast,
  }),
}));

vi.mock('../context/useAuth', () => ({
  default: () => ({ user: { role: 'cliente' } }),
}));

vi.mock('../context/useLanguage', () => ({
  default: () => ({
    t: (key, vars) => {
      if (key === 'productCard.productLabel') return `Producto ${vars?.name}`;
      if (key === 'productCard.addFavorite') return `Agregar ${vars?.name} a favoritos`;
      if (key === 'productCard.removeFavorite') return `Quitar ${vars?.name} de favoritos`;
      if (key === 'productCard.addedToCart') return `Agregado ${vars?.name}`;
      if (key === 'productCard.readyToBuy') return `Listo para comprar ${vars?.name}`;
      if (key === 'productCard.viewLabel') return `Ver ${vars?.name}`;
      if (key === 'productCard.addProduct') return `Agregar ${vars?.name}`;
      if (key === 'productCard.buy') return `Comprar ${vars?.name}`;
      if (key === 'productCard.favoriteOn') return 'Favorito';
      if (key === 'productCard.favoriteOff') return 'Favorito';
      if (key === 'productCard.view') return 'Ver';
      if (key === 'productCard.newBadge') return 'Nuevo';
      if (key === 'productCard.inCartText') return `${vars?.count ?? 0} en carrito`;
      if (key === 'productCard.inCartLabel') return `${vars?.count ?? 0} unidades en carrito`;
      if (key === 'productCard.newProduct') return 'Producto nuevo';
      return key;
    },
    formatCurrency: (value) => `€${Number(value).toFixed(2)}`,
    translateCategory: (value) => value,
    translateProductText: (value) => value,
  }),
}));

function renderCard(overrides = {}, props = {}) {
  const product = {
    id: 1,
    name: 'Auriculares inalámbricos',
    description: 'Gran sonido',
    category: 'Electrónica',
    image: 'https://example.com/item.jpg',
    price: 99.99,
    ...overrides,
  };

  return render(
    <ProductCard
      product={product}
      onEditProduct={mockOnEditProduct}
      onDeleteProduct={mockOnDeleteProduct}
      onDuplicateProduct={mockOnDuplicateProduct}
      searchQuery={props.searchQuery}
    />
  );
}

describe('ProductCard', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    cleanup();
  });

  it('renders accessible image alt with translated name and formatted price', () => {
    renderCard();
    const img = screen.getByRole('img', { name: 'Auriculares inalámbricos - €99.99' });
    expect(img).toBeInTheDocument();
  });

  it('dispatches ADD_ITEM and shows success toast when add button is clicked', async () => {
    const user = userEvent.setup();
    renderCard();

    await user.click(screen.getByRole('button', { name: 'Agregar Auriculares inalámbricos' }));

    expect(mockDispatch).toHaveBeenCalledWith({
      type: 'ADD_ITEM',
      payload: expect.objectContaining({ id: 1, name: 'Auriculares inalámbricos' }),
    });
    expect(mockShowToast).toHaveBeenCalledWith('Agregado Auriculares inalámbricos', 'success');
  });

  it('adds to cart and navigates to checkout when buy button is clicked', async () => {
    const user = userEvent.setup();
    renderCard();

    await user.click(screen.getByRole('button', { name: 'Comprar Auriculares inalámbricos' }));

    expect(mockDispatch).toHaveBeenCalledWith({
      type: 'ADD_ITEM',
      payload: expect.objectContaining({ id: 1 }),
    });
    expect(mockNavigate).toHaveBeenCalledWith('/checkout');
  });

  it('navigates to product detail when view button is clicked', async () => {
    const user = userEvent.setup();
    renderCard();

    await user.click(screen.getByRole('button', { name: 'Ver Auriculares inalámbricos' }));
    expect(mockNavigate).toHaveBeenCalledWith('/producto/1');
  });

  it('toggles favorite using accessible pressed button', async () => {
    const user = userEvent.setup();
    renderCard();

    const favoriteButton = screen.getByRole('button', { name: 'Agregar Auriculares inalámbricos a favoritos' });
    expect(favoriteButton).toHaveAttribute('aria-pressed', 'false');
    await user.click(favoriteButton);

    expect(mockToggleFavorite).toHaveBeenCalledWith(
      expect.objectContaining({ id: 1, name: 'Auriculares inalámbricos' })
    );
  });

  it('highlights matching text with accent-insensitive search query', () => {
    renderCard({}, { searchQuery: 'inalambricos' });

    const highlighted = screen.getAllByText(/inalámbricos/i, { selector: 'mark' });
    expect(highlighted.length).toBeGreaterThan(0);
  });
});
