// Generated by GitHub Copilot
import { useNavigate } from 'react-router-dom';
import useCart from '../context/useCart';
import useAuth from '../context/useAuth';

/**
 * ProductCard displays a single product with an accessible "Add to cart" button.
 * @param {{ product: object, onEditProduct?: Function, onDeleteProduct?: Function }} props
 */
export default function ProductCard({ product, onEditProduct, onDeleteProduct }) {
  const navigate = useNavigate();
  const { dispatch, isFavorite, toggleFavorite, showToast } = useCart();
  const { user } = useAuth();

  const isAdmin = user?.role === 'admin';
  const favorite = isFavorite(product.id);

  const handleAdd = () => {
    dispatch({ type: 'ADD_ITEM', payload: product });
    showToast(`Agregaste "${product.name}" al carrito`, 'success');
  };

  /** Muestra un resumen rapido del producto al usuario. */
  const handleView = () => {
    navigate(`/producto/${product.id}`);
  };

  /** Agrega el producto y envia al checkout para compra rapida. */
  const handleBuy = () => {
    dispatch({ type: 'ADD_ITEM', payload: product });
    showToast(`"${product.name}" listo para comprar`, 'success');
    navigate('/checkout');
  };

  return (
    <article
      className="bg-white rounded-2xl shadow hover:shadow-md transition-shadow overflow-hidden flex flex-col"
      aria-label={`Producto: ${product.name}`}
    >
      <img
        src={product.image}
        alt={product.name}
        className="w-full h-48 object-cover"
        loading="lazy"
      />
      <div className="p-4 flex flex-col flex-1 gap-2">
        <div className="flex items-start justify-between gap-2">
          <span className="text-xs font-medium text-indigo-500 uppercase tracking-wide">
            {product.category}
          </span>
          {!isAdmin && (
            <button
              type="button"
              onClick={() => toggleFavorite(product)}
              className={`rounded-full px-2 py-1 text-xs font-semibold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 ${
                favorite
                  ? 'bg-rose-100 text-rose-700 hover:bg-rose-200'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
              aria-pressed={favorite}
              aria-label={`${favorite ? 'Quitar de favoritos' : 'Agregar a favoritos'}: ${product.name}`}
            >
              {favorite ? '❤ Favorito' : '♡ Favorito'}
            </button>
          )}
        </div>
        <h2 className="text-gray-800 font-semibold text-base leading-tight">{product.name}</h2>
        <p className="text-gray-500 text-sm flex-1">{product.description}</p>
        <div className="flex items-center justify-between mt-2">
          <span className="text-lg font-bold text-gray-900">${product.price.toFixed(2)}</span>
        </div>
        <div className="mt-1 grid grid-cols-2 gap-2">
          <button
            type="button"
            onClick={handleView}
            className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-medium text-gray-700 transition hover:bg-gray-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            aria-label={`Ver producto: ${product.name}`}
          >
            Ver
          </button>
          {isAdmin ? (
            <>
              <button
                type="button"
                onClick={() => onEditProduct?.(product)}
                className="rounded-lg border border-amber-300 bg-white px-3 py-2 text-xs font-medium text-amber-700 transition hover:bg-amber-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-500"
                aria-label={`Editar producto: ${product.name}`}
              >
                Editar
              </button>
              <button
                type="button"
                onClick={() => onDeleteProduct?.(product)}
                className="rounded-lg border border-red-300 bg-white px-3 py-2 text-xs font-medium text-red-600 transition hover:bg-red-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-500"
                aria-label={`Borrar producto del catálogo: ${product.name}`}
              >
                Borrar
              </button>
            </>
          ) : (
            <>
              <button
                type="button"
                onClick={handleAdd}
                className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-medium text-white transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                aria-label={`Añadir producto: ${product.name}`}
              >
                Añadir producto
              </button>
              <button
                type="button"
                onClick={handleBuy}
                className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-medium text-white transition hover:bg-emerald-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600"
                aria-label={`Comprar producto: ${product.name}`}
              >
                Comprar
              </button>
            </>
          )}
        </div>
      </div>
    </article>
  );
}
