// Generated by GitHub Copilot
// Para que sirve: Protector de rutas que exige autenticación.
//   Si el usuario no está autenticado, redirige a /login guardando la ruta actual
//   en location.state.from para redirigir de vuelta tras el inicio de sesión.
// Flujo principal: App.jsx envuelve rutas privadas con <RequireAuth>.
// Dónde tocar cambios: cambia la ruta de redirección si el login se mueve de /login.
import { Navigate, useLocation } from 'react-router-dom';
import useAuth from '../context/useAuth';

/**
 * Protects a route and redirects unauthenticated users to login.
 * @param {{ children: React.ReactNode }} props
 */
export default function RequireAuth({ children }) {
  const { isAuthenticated } = useAuth();
  const location = useLocation();

  if (!isAuthenticated) {
    return <Navigate to="/login" replace state={{ from: location }} />;
  }

  return children;
}
