// Generated by GitHub Copilot
// Para que sirve: Protector de rutas para exigir autenticacion.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { Navigate, useLocation } from 'react-router-dom';
import useAuth from '../context/useAuth';

/**
 * Protects a route and redirects unauthenticated users to login.
 * @param {{ children: React.ReactNode }} props
 */
export default function RequireAuth({ children }) {
  const { isAuthenticated } = useAuth();
  const location = useLocation();

  if (!isAuthenticated) {
    return <Navigate to="/login" replace state={{ from: location }} />;
  }

  return children;
}
