// Generated by GitHub Copilot
// Para que sirve: Protector de rutas para exigir rol/permisos.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { Navigate, useLocation } from 'react-router-dom';
import useAuth from '../context/useAuth';

/**
 * Protects routes by authentication and role membership.
 * @param {{ children: React.ReactNode, allowedRoles: Array<string> }} props
 */
export default function RequireRole({ children, allowedRoles }) {
  const { isAuthenticated, user } = useAuth();
  const location = useLocation();

  if (!isAuthenticated) {
    return <Navigate to="/login" replace state={{ from: location }} />;
  }

  const role = String(user?.role || '').toLowerCase();
  const isAllowed = allowedRoles.some((item) => String(item).toLowerCase() === role);

  if (!isAllowed) {
    const fallback = role === 'admin' ? '/admin/productos' : '/';
    return <Navigate to={fallback} replace />;
  }

  return children;
}
