// Generated by GitHub Copilot
// Para que sirve: Control de desplazamiento superior y progreso de lectura.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useEffect, useState } from 'react';

/**
 * Floating scroll-to-top button and a thin reading-progress bar at the top
 * of the viewport.
 * Accessibility: visible focus ring, aria-label, aria-hidden on decorative bar.
 */
export default function ScrollToTop() {
  const [scrollPercent, setScrollPercent] = useState(0);

  useEffect(() => {
    /** Tracks scroll progress and shows/hides the button. */
    const handleScroll = () => {
      const docHeight = document.documentElement.scrollHeight - window.innerHeight;
      setScrollPercent(docHeight > 0 ? Math.round((window.scrollY / docHeight) * 100) : 0);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <>
      {/* Reading progress bar â€” always present, grows with scroll */}
      <div
        aria-hidden="true"
        style={{ width: `${scrollPercent}%` }}
        className="fixed top-0 left-0 z-60 h-1 bg-indigo-500 pointer-events-none transition-[width] duration-100"
      />

      {scrollPercent > 8 && (
        <button
          type="button"
          onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          aria-label="Volver al inicio de la pÃ¡gina"
          className="fixed bottom-20 right-4 z-50 flex h-10 w-10 items-center justify-center rounded-full bg-indigo-600 text-white shadow-lg transition hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 active:scale-90"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2.5"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="h-5 w-5"
            aria-hidden="true"
          >
            <polyline points="18 15 12 9 6 15" />
          </svg>
        </button>
      )}
    </>
  );
}
