// Generated by GitHub Copilot
import '@testing-library/jest-dom/vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import Toast from './Toast';

const mockDismissToast = vi.fn();

let mockCartState = {
  toast: { message: '', type: 'info' },
  dismissToast: mockDismissToast,
};

vi.mock('../context/useCart', () => ({
  default: () => mockCartState,
}));

vi.mock('../context/useLanguage', () => ({
  default: () => ({
    t: (key) => {
      if (key === 'common.closeNotification') {
        return 'Cerrar notificación';
      }
      return key;
    },
  }),
}));

describe('Toast integration', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockCartState = {
      toast: { message: '', type: 'info' },
      dismissToast: mockDismissToast,
    };
  });

  afterEach(() => {
    cleanup();
  });

  it('does not render when toast message is empty', () => {
    render(<Toast />);

    expect(screen.queryByRole('alert')).not.toBeInTheDocument();
    expect(screen.queryByRole('status')).not.toBeInTheDocument();
  });

  it('renders error toast as assertive alert with shake animation', () => {
    mockCartState = {
      toast: { message: 'Error de prueba', type: 'error' },
      dismissToast: mockDismissToast,
    };

    const { container } = render(<Toast />);

    const alert = screen.getByRole('alert');
    expect(alert).toHaveAttribute('aria-live', 'assertive');
  expect(alert).toHaveAttribute('aria-atomic', 'true');
    expect(alert).toHaveTextContent('Error de prueba');
    expect(alert).toHaveClass('animate-shake');

    const closeButton = screen.getByRole('button', { name: 'Cerrar notificación' });
    expect(closeButton).toBeInTheDocument();

    // Tone class should reflect error style.
    expect(container.querySelector('.bg-red-600')).toBeInTheDocument();
  });

  it('renders success toast as polite status and supports dismiss click', async () => {
    const user = userEvent.setup();
    mockCartState = {
      toast: { message: 'Guardado correctamente', type: 'success' },
      dismissToast: mockDismissToast,
    };

    const { container } = render(<Toast />);

    const status = screen.getByRole('status');
    expect(status).toHaveAttribute('aria-live', 'polite');
    expect(status).toHaveTextContent('Guardado correctamente');
    expect(status).toHaveClass('animate-slide-in-right');

    expect(container.querySelector('.bg-emerald-600')).toBeInTheDocument();

    await user.click(screen.getByRole('button', { name: 'Cerrar notificación' }));
    expect(mockDismissToast).toHaveBeenCalledTimes(1);
  });

  it('dismisses toast when Escape key is pressed', async () => {
    const user = userEvent.setup();
    mockCartState = {
      toast: { message: 'Aviso temporal', type: 'info' },
      dismissToast: mockDismissToast,
    };

    render(<Toast />);
    expect(screen.getByRole('status')).toBeInTheDocument();

    await user.keyboard('{Escape}');

    expect(mockDismissToast).toHaveBeenCalledTimes(1);
  });
});
