// Generated by GitHub Copilot
import useCart from '../context/useCart';

/**
 * Global toast notification component.
 * Announces changes with aria-live for accessibility.
 */
export default function Toast() {
  const { toast } = useCart();

  if (!toast.message) {
    return null;
  }

  const toneClass = {
    info: 'bg-slate-900 text-white',
    success: 'bg-emerald-600 text-white',
    error: 'bg-red-600 text-white',
  }[toast.type] || 'bg-slate-900 text-white';

  return (
    <div
      role="status"
      aria-live="polite"
      className="fixed bottom-4 right-4 z-[60]"
    >
      <div className={`rounded-xl px-4 py-3 text-sm shadow-lg ${toneClass}`}>
        {toast.message}
      </div>
    </div>
  );
}
