// Generated by GitHub Copilot
// Para que sirve: Notificacion flotante para feedback rapido de acciones.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import useCart from '../context/useCart';
import useLanguage from '../context/useLanguage';

/**
 * Global toast notification component.
 * Announces changes with aria-live for accessibility.
 */
export default function Toast() {
  const { toast, dismissToast } = useCart();
  const { t } = useLanguage();

  if (!toast.message) {
    return null;
  }

  // Generated by GitHub Copilot
  // Error toasts should be announced immediately; informational toasts can be polite.
  const isErrorToast = toast.type === 'error';

  // Select animation based on toast type: shake for errors, slide for success, fade for info
  const animationClass = {
    error: 'animate-shake',
    success: 'animate-slide-in-right',
    info: 'animate-fade-in-up',
  }[toast.type] || 'animate-fade-in-up';

  const toneClass = {
    info: 'bg-slate-900 text-white',
    success: 'bg-emerald-600 text-white',
    error: 'bg-red-600 text-white',
  }[toast.type] || 'bg-slate-900 text-white';

  return (
    <div
      role={isErrorToast ? 'alert' : 'status'}
      aria-live={isErrorToast ? 'assertive' : 'polite'}
      // z-[9000] keeps the toast above all overlays including the sticky Navbar (z-50) and dialogs.
      className={`fixed bottom-4 right-4 z-9000 ${animationClass}`}
    >
      <div className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm shadow-lg ${toneClass}`}>
        <span>{toast.message}</span>
        <button
          type="button"
          onClick={dismissToast}
          className="ml-1 rounded p-0.5 opacity-70 hover:opacity-100 focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-white transition"
          aria-label={t('common.closeNotification')}
        >
          ×
        </button>
      </div>
    </div>
  );
}
