// Generated by GitHub Copilot
import useCart from '../context/useCart';

/**
 * Global toast notification component.
 * Announces changes with aria-live for accessibility.
 */
export default function Toast() {
  const { toast, dismissToast } = useCart();

  if (!toast.message) {
    return null;
  }

  const toneClass = {
    info: 'bg-slate-900 text-white',
    success: 'bg-emerald-600 text-white',
    error: 'bg-red-600 text-white',
  }[toast.type] || 'bg-slate-900 text-white';

  return (
    <div
      role="status"
      aria-live="polite"
      className="fixed bottom-4 right-4 z-60 animate-fade-in-up"
    >
      <div className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm shadow-lg ${toneClass}`}>
        <span>{toast.message}</span>
        <button
          type="button"
          onClick={dismissToast}
          className="ml-1 rounded p-0.5 opacity-70 hover:opacity-100 focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-white transition"
          aria-label="Cerrar notificación"
        >
          ✕
        </button>
      </div>
    </div>
  );
}
