// Generated by GitHub Copilot
import { describe, expect, it } from 'vitest';
import {
  areSameCategory,
  buildCategoryFilterHref,
  getCategoryParamValue,
  getCanonicalCategoryKey,
  normalizeCategoryLookup,
  resolveCategorySelection,
} from './categoryUtils';

describe('category utils', () => {
  it('normalizes category labels for accent-insensitive lookup', () => {
    expect(normalizeCategoryLookup('  Electrónica  ')).toBe('electronica');
  });

  it('maps translated labels to the same canonical category key', () => {
    expect(getCanonicalCategoryKey('Electronics')).toBe('electronics');
    expect(getCanonicalCategoryKey('Elektronika')).toBe('electronics');
    expect(getCanonicalCategoryKey('Électronique')).toBe('electronics');
  });

  it('resolves translated URL params to an available category label', () => {
    const categories = ['Todos', 'Electrónica', 'Deportes', 'Accesorios'];

    expect(resolveCategorySelection('electronics', categories)).toBe('Electrónica');
    expect(resolveCategorySelection('esports', categories)).toBe('Deportes');
  });

  it('falls back to the all category for translated all aliases', () => {
    const categories = ['Todos', 'Electrónica', 'Deportes', 'Accesorios'];

    expect(resolveCategorySelection('all', categories)).toBe('Todos');
    expect(resolveCategorySelection('tots', categories)).toBe('Todos');
  });

  it('returns canonical URL params for selected categories', () => {
    expect(getCategoryParamValue('Electrónica')).toBe('electronics');
    expect(getCategoryParamValue('Todos')).toBe('');
    expect(getCategoryParamValue('Tots')).toBe('');
  });

  it('builds canonical Home filter hrefs', () => {
    expect(buildCategoryFilterHref('Electrónica')).toBe('/?categoria=electronics');
    expect(buildCategoryFilterHref('Todos')).toBe('/');
    expect(buildCategoryFilterHref('Deportes', '/productos')).toBe('/productos?categoria=sports');
  });

  it('compares equivalent categories by canonical alias', () => {
    expect(areSameCategory('Electrónica', 'Electronica')).toBe(true);
    expect(areSameCategory('Deportes', 'sports')).toBe(true);
    expect(areSameCategory('Electrónica', 'Deportes')).toBe(false);
  });
});