// Generated by GitHub Copilot
// Para que sirve: Utilidad de texto para búsqueda insensible a acentos e mayúsculas.
//   Normaliza cadenas (NFD + strip de diacríticos + minúsculas) para que la búsqueda
//   encuentre «auriculares» aunque el usuario escriba «Auriculares» o «ãuriculãres».
// Flujo principal: normalizeSearchText → usado en Home (filtro), ProductCard (highlight) y AdminProducts.
// Dónde tocar cambios: este archivo si se necesita soporte de idiomas con caracteres no-latinos.

/**
 * Normalizes text for accent-insensitive and case-insensitive search.
 * @param {string} value
 * @returns {string}
 */
export function normalizeSearchText(value) {
  return String(value ?? '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
}