// Generated by GitHub Copilot

/**
 * Validates a remote image URL using strict security constraints.
 * Security: rejects non-http(s), credentials in URL, localhost, and private network hosts.
 * @param {string} value
 * @returns {boolean}
 */
export function isSafeHttpImageUrl(value) {
  const raw = String(value ?? '').trim();
  if (!raw) {
    return false;
  }

  if (raw.length > 2048) {
    return false;
  }

  let parsed;
  try {
    parsed = new URL(raw);
  } catch {
    return false;
  }

  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    return false;
  }

  if (parsed.username || parsed.password) {
    return false;
  }

  const hostname = parsed.hostname.toLowerCase();
  if (!hostname) {
    return false;
  }

  if (hostname === 'localhost' || hostname === '0.0.0.0' || hostname === '127.0.0.1' || hostname === '::1') {
    return false;
  }

  if (hostname.startsWith('10.') || hostname.startsWith('192.168.')) {
    return false;
  }

  if (hostname.startsWith('172.')) {
    const secondOctet = Number.parseInt(hostname.split('.')[1] || '', 10);
    if (Number.isInteger(secondOctet) && secondOctet >= 16 && secondOctet <= 31) {
      return false;
    }
  }

  return true;
}
