// Generated by GitHub Copilot
import { act, renderHook } from '@testing-library/react';
import { beforeEach, describe, expect, it } from 'vitest';
import { AuthProvider } from './AuthContext';
import useAuth from './useAuth';

describe('AuthContext security hardening', () => {
  beforeEach(() => {
    localStorage.clear();
  });

  it('stores newly registered passwords as SHA-256 hashes', async () => {
    const { result } = renderHook(() => useAuth(), { wrapper: AuthProvider });

    await act(async () => {
      const registrationResult = await result.current.register({
        name: 'Persona Test',
        email: 'test@example.com',
        password: 'Test1234',
        confirmPassword: 'Test1234',
      });
      expect(registrationResult.ok).toBe(true);
    });

    const rawUsers = localStorage.getItem('tienda_react_auth_users');
    const users = JSON.parse(rawUsers || '[]');
    const created = users.find((item) => item.email === 'test@example.com');

    expect(created).toBeTruthy();
    expect(created.password).toMatch(/^sha256:[a-f0-9]{64}$/);
    expect(created.password).not.toBe('Test1234');
  });

  it('temporarily blocks login after repeated failed attempts', async () => {
    const { result } = renderHook(() => useAuth(), { wrapper: AuthProvider });

    for (let i = 0; i < 5; i += 1) {
      await act(async () => {
        const loginResult = await result.current.login({
          email: 'admin@tienda.com',
          password: 'WrongPass123',
        });
        expect(loginResult.ok).toBe(false);
      });
    }

    let blockedResult;
    await act(async () => {
      blockedResult = await result.current.login({
        email: 'admin@tienda.com',
        password: 'WrongPass123',
      });
    });

    expect(blockedResult.ok).toBe(false);
    expect(blockedResult.error).toMatch(/demasiados intentos/i);
  });
});
