// Generated by GitHub Copilot
// Para que sirve: Proveedor de autenticacion con login, logout y recuperacion de contrasena.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AuthContext } from './AuthStateContext';
import useLanguage from './useLanguage';

const AUTH_STORAGE_KEY = 'tienda_react_auth_user';
const USERS_STORAGE_KEY = 'tienda_react_auth_users';
const LOGIN_GUARD_STORAGE_KEY = 'tienda_react_auth_login_guard';
const AUTH_NOTICE_STORAGE_KEY = 'tienda_react_auth_notice';
const AUTH_AUDIT_STORAGE_KEY = 'tienda_react_auth_audit';
const SESSION_ACTIVITY_STORAGE_KEY = 'tienda_react_auth_last_activity';
const SESSION_EXPIRED_STORAGE_KEY = 'tienda_react_auth_session_expired';
const SESSION_EXPIRED_REDIRECT_STORAGE_KEY = 'tienda_react_auth_session_expired_redirect';
const MAX_FAILED_LOGIN_ATTEMPTS = 5;
const LOGIN_LOCK_WINDOW_MS = 5 * 60 * 1000;
const SESSION_IDLE_TIMEOUT_MS = 30 * 60 * 1000;
const SESSION_WARNING_BEFORE_MS = 60 * 1000;
const SESSION_ACTIVITY_SYNC_MS = 15 * 1000;
const SESSION_CHECK_INTERVAL_MS = 1000;
const AUTH_AUDIT_MAX_ITEMS = 120;
const AUTH_AUDIT_RETENTION_MS = 30 * 24 * 60 * 60 * 1000;
const DEFAULT_USERS = [
  {
    name: 'Administrador',
    email: 'admin@tienda.com',
    passwordHash: '3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2',
    role: 'admin',
  },
  {
    name: 'Cliente Demo',
    email: 'cliente@tienda.com',
    passwordHash: '34e422278ea745b5d87ba6592f0ea3fe32a2eb7593f5960ac72d7094fb121f3d',
    role: 'cliente',
  },
];

/**
 * Merges stored users with built-in demo users by email.
 * Stored users take precedence if emails collide.
 * @param {Array<{ name: string, email: string, passwordHash?: string, password?: string, role?: string }>} storedUsers
 * @returns {Array<{ name: string, email: string, passwordHash?: string, password?: string, role?: string }>}
 */
function mergeDefaultUsers(storedUsers) {
  const byEmail = new Map(DEFAULT_USERS.map((item) => [item.email, item]));
  storedUsers.forEach((item) => {
    byEmail.set(item.email, item);
  });
  return Array.from(byEmail.values());
}

/**
 * Reads persisted auth user from localStorage in a safe way.
 * @returns {{ email: string, name?: string, role?: string } | null}
 */
function getInitialUser() {
  try {
    const rawUser = localStorage.getItem(AUTH_STORAGE_KEY);
    if (!rawUser) {
      return null;
    }

    const parsed = JSON.parse(rawUser);
    if (!parsed?.email) {
      return null;
    }

    return {
      email: String(parsed.email),
      name: parsed.name ? String(parsed.name) : '',
      role: parsed.role ? String(parsed.role) : 'cliente',
    };
  } catch {
    return null;
  }
}

/**
 * Parses auth user from a storage payload.
 * @param {string | null} rawUser
 * @returns {{ email: string, name?: string, role?: string } | null}
 */
function parseAuthUser(rawUser) {
  try {
    if (!rawUser) {
      return null;
    }

    const parsed = JSON.parse(rawUser);
    if (!parsed?.email) {
      return null;
    }

    return {
      email: String(parsed.email),
      name: parsed.name ? String(parsed.name) : '',
      role: parsed.role ? String(parsed.role) : 'cliente',
    };
  } catch {
    return null;
  }
}

/**
 * Parses a cross-tab auth notice payload.
 * @param {string | null} rawNotice
 * @returns {{ message: string, type: 'info' | 'success' | 'error', code: string } | null}
 */
function parseAuthNotice(rawNotice) {
  try {
    if (!rawNotice) {
      return null;
    }

    const parsed = JSON.parse(rawNotice);
    const message = String(parsed?.message || '').trim();
    if (!message) {
      return null;
    }

    const type = parsed?.type === 'success' || parsed?.type === 'error' ? parsed.type : 'info';
    const code = /^[a-z0-9_-]{3,40}$/i.test(String(parsed?.code || '')) ? String(parsed.code) : 'general_notice';
    return { message, type, code };
  } catch {
    return null;
  }
}

/**
 * Reads local auth audit records.
 * @returns {Array<{ id: string, at: string, code: string, type: 'info' | 'success' | 'error', message: string, source: string }>}
 */
function getAuthAuditRecords() {
  try {
    const raw = localStorage.getItem(AUTH_AUDIT_STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    if (!Array.isArray(parsed)) {
      return [];
    }

    const cutoffMs = Date.now() - AUTH_AUDIT_RETENTION_MS;
    return parsed
      .filter((item) => typeof item?.message === 'string' && item.message.trim().length > 0)
      .filter((item) => {
        const atMs = Date.parse(String(item?.at || ''));
        return Number.isFinite(atMs) && atMs >= cutoffMs;
      })
      .map((item) => ({
        id: String(item.id || `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`),
        at: String(item.at),
        code: /^[a-z0-9_-]{3,40}$/i.test(String(item.code || '')) ? String(item.code) : 'general_notice',
        type: item.type === 'success' || item.type === 'error' ? item.type : 'info',
        message: String(item.message).trim(),
        source: String(item.source || 'local').trim() || 'local',
      }))
      .slice(0, AUTH_AUDIT_MAX_ITEMS);
  } catch {
    return [];
  }
}

/**
 * Persists one auth audit event while keeping bounded storage growth.
 * @param {{ code: string, type?: 'info' | 'success' | 'error', message: string, source?: string }} event
 */
function appendAuthAuditEvent(event) {
  const message = String(event?.message || '').trim();
  if (!message) {
    return;
  }

  const code = /^[a-z0-9_-]{3,40}$/i.test(String(event?.code || '')) ? String(event.code) : 'general_notice';
  const type = event?.type === 'success' || event?.type === 'error' ? event.type : 'info';
  const source = String(event?.source || 'local').trim() || 'local';
  const nextEvent = {
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    at: new Date().toISOString(),
    code,
    type,
    message,
    source,
  };

  const current = getAuthAuditRecords();
  const next = [nextEvent, ...current].slice(0, AUTH_AUDIT_MAX_ITEMS);
  localStorage.setItem(AUTH_AUDIT_STORAGE_KEY, JSON.stringify(next));
}

/**
 * Broadcasts a one-time auth notice to other tabs.
 * @param {{ message: string, type?: 'info' | 'success' | 'error', code?: string }} payload
 */
function broadcastAuthNotice(payload) {
  const safeMessage = String(payload?.message || '').trim();
  if (!safeMessage) {
    return;
  }

  const noticePayload = {
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    message: safeMessage,
    type: payload?.type === 'success' || payload?.type === 'error' ? payload.type : 'info',
    code: /^[a-z0-9_-]{3,40}$/i.test(String(payload?.code || '')) ? String(payload.code) : 'general_notice',
  };
  localStorage.setItem(AUTH_NOTICE_STORAGE_KEY, JSON.stringify(noticePayload));
}

/**
 * Reads persisted users from localStorage in a safe way.
 * @returns {Array<{ name: string, email: string, passwordHash?: string, password?: string, role?: string }>}
 */
function getInitialUsers() {
  try {
    const rawUsers = localStorage.getItem(USERS_STORAGE_KEY);
    if (!rawUsers) {
      return DEFAULT_USERS;
    }

    const parsed = JSON.parse(rawUsers);
    if (!Array.isArray(parsed)) {
      return DEFAULT_USERS;
    }

    const normalizedUsers = parsed
      .filter((item) => item?.email && (item?.passwordHash || item?.password))
      .map((item) => ({
        name: String(item.name || ''),
        email: String(item.email).toLowerCase(),
        passwordHash: item.passwordHash ? String(item.passwordHash) : undefined,
        password: item.password ? String(item.password) : undefined,
        role: item.role ? String(item.role) : 'cliente',
      }));

    return mergeDefaultUsers(normalizedUsers);
  } catch {
    return DEFAULT_USERS;
  }
}

/**
 * Enforces a stronger password baseline for local auth flows.
 * @param {string} password
 * @returns {boolean}
 */
function isStrongPassword(password) {
  return /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/.test(password);
}

/**
 * Reads login guard state from localStorage.
 * @returns {{ failedCount: number, lockedUntil: number }}
 */
function getLoginGuard() {
  try {
    const raw = localStorage.getItem(LOGIN_GUARD_STORAGE_KEY);
    if (!raw) {
      return { failedCount: 0, lockedUntil: 0 };
    }

    const parsed = JSON.parse(raw);
    return {
      failedCount: Number.isInteger(parsed?.failedCount) && parsed.failedCount > 0 ? parsed.failedCount : 0,
      lockedUntil: Number.isFinite(parsed?.lockedUntil) && parsed.lockedUntil > 0 ? parsed.lockedUntil : 0,
    };
  } catch {
    return { failedCount: 0, lockedUntil: 0 };
  }
}

/**
 * Persists login guard state.
 * @param {{ failedCount: number, lockedUntil: number }} guard
 */
function setLoginGuard(guard) {
  localStorage.setItem(LOGIN_GUARD_STORAGE_KEY, JSON.stringify(guard));
}

/** Clears login guard lock and failed attempt counters. */
function clearLoginGuard() {
  localStorage.removeItem(LOGIN_GUARD_STORAGE_KEY);
}

/**
 * Reads last activity timestamp for the authenticated session.
 * @returns {number}
 */
function getLastSessionActivity() {
  try {
    const raw = localStorage.getItem(SESSION_ACTIVITY_STORAGE_KEY);
    const parsed = Number.parseInt(String(raw || ''), 10);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : 0;
  } catch {
    return 0;
  }
}

/**
 * Stores a new last-activity timestamp for session timeout checks.
 * @param {number} timestampMs
 */
function setLastSessionActivity(timestampMs) {
  localStorage.setItem(SESSION_ACTIVITY_STORAGE_KEY, String(timestampMs));
}

/** Clears persisted session activity metadata. */
function clearSessionActivity() {
  localStorage.removeItem(SESSION_ACTIVITY_STORAGE_KEY);
}

/** Marks next login screen with an inactivity-expired session reason. */
function markSessionExpired() {
  const currentPath = `${window.location.pathname || '/'}${window.location.search || ''}${window.location.hash || ''}`;
  localStorage.setItem(SESSION_EXPIRED_REDIRECT_STORAGE_KEY, currentPath);
  localStorage.setItem(SESSION_EXPIRED_STORAGE_KEY, '1');
}

/** Clears expired-session metadata once it is no longer needed. */
function clearSessionExpiredMetadata() {
  localStorage.removeItem(SESSION_EXPIRED_STORAGE_KEY);
  localStorage.removeItem(SESSION_EXPIRED_REDIRECT_STORAGE_KEY);
}

/**
 * Builds a stable SHA-256 hash for a password.
 * Security note: this improves local storage safety but is not a replacement for server-side auth.
 * @param {string} password
 * @returns {Promise<string>}
 */
async function hashPassword(password) {
  const safePassword = String(password || '');
  if (typeof crypto !== 'undefined' && crypto.subtle && typeof TextEncoder !== 'undefined') {
    const data = new TextEncoder().encode(safePassword);
    const digest = await crypto.subtle.digest('SHA-256', data);
    return Array.from(new Uint8Array(digest))
      .map((byte) => byte.toString(16).padStart(2, '0'))
      .join('');
  }

  // Fallback hash for old browser environments where SubtleCrypto is unavailable.
  let hash = 2166136261;
  for (let i = 0; i < safePassword.length; i += 1) {
    hash ^= safePassword.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return `fnv-${(hash >>> 0).toString(16).padStart(8, '0')}`;
}

/**
 * Compares two hash strings in a length-normalized way.
 * @param {string} left
 * @param {string} right
 * @returns {boolean}
 */
function safeHashEquals(left, right) {
  const a = String(left || '');
  const b = String(right || '');
  const maxLen = Math.max(a.length, b.length);
  let diff = a.length === b.length ? 0 : 1;

  for (let i = 0; i < maxLen; i += 1) {
    diff |= (a.charCodeAt(i) || 0) ^ (b.charCodeAt(i) || 0);
  }

  return diff === 0;
}

/**
 * AuthProvider stores login status and exposes auth actions.
 * Security note: password is never persisted in storage.
 * @param {{ children: React.ReactNode }} props
 */
export function AuthProvider({ children }) {
  const { t } = useLanguage();
  const [user, setUser] = useState(getInitialUser);
  const [users, setUsers] = useState(getInitialUsers);
  const [authNotice, setAuthNotice] = useState(null);
  const [showSessionExpiryWarning, setShowSessionExpiryWarning] = useState(false);
  const [sessionExpiryRemainingSeconds, setSessionExpiryRemainingSeconds] = useState(0);
  const lastActivityWriteRef = useRef(0);

  useEffect(() => {
    // Normalize and purge stale audit records on provider startup.
    const normalizedAudit = getAuthAuditRecords();
    localStorage.setItem(AUTH_AUDIT_STORAGE_KEY, JSON.stringify(normalizedAudit));
  }, []);

  /**
   * Ends the active user session.
   * @param {{ keepExpiredMetadata?: boolean }} options
   */
  const logout = useCallback((options = {}) => {
    const keepExpiredMetadata = options.keepExpiredMetadata === true;
    const broadcastNoticeMessage = String(options.broadcastNotice?.message || '').trim();
    if (broadcastNoticeMessage) {
      const noticeType = options.broadcastNotice?.type;
      const noticeCode = options.broadcastNotice?.code;
      broadcastAuthNotice({
        message: broadcastNoticeMessage,
        type: noticeType,
        code: noticeCode,
      });
      appendAuthAuditEvent({
        message: broadcastNoticeMessage,
        type: noticeType,
        code: noticeCode,
        source: 'local-broadcast',
      });
    }
    clearSessionActivity();
    if (!keepExpiredMetadata) {
      clearSessionExpiredMetadata();
    }
    setShowSessionExpiryWarning(false);
    setSessionExpiryRemainingSeconds(0);
    setUser(null);
  }, []);

  /** Clears the current in-memory auth notice after UI consumption. */
  const clearAuthNotice = useCallback(() => {
    setAuthNotice(null);
  }, []);

  /** Returns normalized auth audit events for diagnostic views. */
  const getAuthAuditTrail = useCallback(() => getAuthAuditRecords(), []);

  /** Clears all persisted auth audit events. */
  const clearAuthAuditTrail = useCallback(() => {
    localStorage.removeItem(AUTH_AUDIT_STORAGE_KEY);
  }, []);

  /** Extends the active session by refreshing last user activity timestamp. */
  const extendSession = useCallback(() => {
    const now = Date.now();
    lastActivityWriteRef.current = now;
    setLastSessionActivity(now);
    setShowSessionExpiryWarning(false);
    setSessionExpiryRemainingSeconds(0);
  }, []);

  useEffect(() => {
    if (!user) {
      localStorage.removeItem(AUTH_STORAGE_KEY);
      return;
    }

    localStorage.setItem(AUTH_STORAGE_KEY, JSON.stringify(user));
  }, [user]);

  useEffect(() => {
    /** Keeps authentication state synchronized across browser tabs. */
    const handleStorage = (event) => {
      if (event.key === AUTH_NOTICE_STORAGE_KEY) {
        const nextNotice = parseAuthNotice(event.newValue);
        if (nextNotice) {
          setAuthNotice(nextNotice);
          appendAuthAuditEvent({
            message: nextNotice.message,
            type: nextNotice.type,
            code: nextNotice.code,
            source: 'cross-tab-received',
          });
        }
        return;
      }

      if (event.key !== AUTH_STORAGE_KEY) {
        return;
      }

      const nextUser = parseAuthUser(event.newValue);
      if (!nextUser) {
        setShowSessionExpiryWarning(false);
        setSessionExpiryRemainingSeconds(0);
        setUser(null);
        return;
      }

      setUser(nextUser);
    };

    window.addEventListener('storage', handleStorage);
    return () => window.removeEventListener('storage', handleStorage);
  }, []);

  useEffect(() => {
    localStorage.setItem(USERS_STORAGE_KEY, JSON.stringify(users));
  }, [users]);

  useEffect(() => {
    if (!user) {
      return undefined;
    }

    const now = Date.now();
    setLastSessionActivity(now);
    lastActivityWriteRef.current = now;

    const updateActivity = () => {
      const nextNow = Date.now();
      setShowSessionExpiryWarning((prev) => (prev ? false : prev));
      setSessionExpiryRemainingSeconds((prev) => (prev > 0 ? 0 : prev));
      if (nextNow - lastActivityWriteRef.current < SESSION_ACTIVITY_SYNC_MS) {
        return;
      }
      lastActivityWriteRef.current = nextNow;
      setLastSessionActivity(nextNow);
    };

    const activityEvents = ['click', 'keydown', 'mousemove', 'scroll', 'touchstart', 'focus', 'visibilitychange'];
    activityEvents.forEach((eventName) => {
      window.addEventListener(eventName, updateActivity, { passive: true });
    });

    const intervalId = window.setInterval(() => {
      const lastActivity = getLastSessionActivity();
      const idleMs = Date.now() - lastActivity;
      if (lastActivity > 0 && idleMs >= SESSION_IDLE_TIMEOUT_MS) {
        markSessionExpired();
        logout({
          keepExpiredMetadata: true,
          broadcastNotice: {
            message: t('common.sessionClosedInactive'),
            type: 'info',
            code: 'idle_timeout',
          },
        });
        return;
      }

      const remainingMs = SESSION_IDLE_TIMEOUT_MS - idleMs;
      const shouldWarn = lastActivity > 0
        && remainingMs > 0
        && remainingMs <= SESSION_WARNING_BEFORE_MS;

      setShowSessionExpiryWarning((prev) => (prev === shouldWarn ? prev : shouldWarn));
      setSessionExpiryRemainingSeconds((prev) => {
        const nextSeconds = shouldWarn ? Math.max(1, Math.ceil(remainingMs / 1000)) : 0;
        return prev === nextSeconds ? prev : nextSeconds;
      });
    }, SESSION_CHECK_INTERVAL_MS);

    return () => {
      activityEvents.forEach((eventName) => {
        window.removeEventListener(eventName, updateActivity);
      });
      window.clearInterval(intervalId);
    };
  }, [logout, user]);

  /**
   * Performs a minimal credential validation and starts session.
   * @param {{ email: string, password: string }} credentials
   * @returns {{ ok: boolean, role?: string, error?: string }}
   */
  const login = useCallback(async ({ email, password }) => {
    const safeEmail = email.trim().toLowerCase();
    const now = Date.now();
    const guard = getLoginGuard();

    if (guard.lockedUntil > now) {
      const remainingSeconds = Math.ceil((guard.lockedUntil - now) / 1000);
      return {
        ok: false,
        error: `Demasiados intentos fallidos. Intenta de nuevo en ${remainingSeconds} segundos.`,
      };
    }

    if (guard.lockedUntil > 0 && guard.lockedUntil <= now) {
      clearLoginGuard();
    }

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(safeEmail)) {
      return { ok: false, error: t('common.invalidEmail') };
    }

    if (!password || password.length < 8) {
      return { ok: false, error: t('auth.passwordTooShort') };
    }

    const existingUser = users.find((item) => item.email === safeEmail);
    let isValidPassword = false;

    if (existingUser?.passwordHash) {
      const incomingHash = await hashPassword(password);
      isValidPassword = safeHashEquals(existingUser.passwordHash, incomingHash);
    } else if (existingUser?.password) {
      isValidPassword = existingUser.password === password;
      if (isValidPassword) {
        const migratedHash = await hashPassword(password);
        setUsers((prev) => prev.map((item) => (
          item.email === safeEmail
            ? {
              ...item,
              passwordHash: migratedHash,
            }
            : item
        )));
      }
    }

    if (!existingUser || !isValidPassword) {
      const nextFailedCount = guard.failedCount + 1;

      if (nextFailedCount >= MAX_FAILED_LOGIN_ATTEMPTS) {
        const lockedUntil = now + LOGIN_LOCK_WINDOW_MS;
        setLoginGuard({ failedCount: 0, lockedUntil });
        appendAuthAuditEvent({
          code: 'login_lockout',
          type: 'error',
          message: t('auth.loginLockoutAudit'),
          source: 'local',
        });
        return {
          ok: false,
          error: t('auth.loginLockoutError'),
        };
      }

      setLoginGuard({ failedCount: nextFailedCount, lockedUntil: 0 });
      const remainingAttempts = MAX_FAILED_LOGIN_ATTEMPTS - nextFailedCount;
      return {
        ok: false,
        error: t('auth.invalidCredentials', { remainingAttempts, suffix: remainingAttempts !== 1 ? 's' : '' }),
      };
    }

    clearLoginGuard();
    appendAuthAuditEvent({
      code: 'login_success',
      type: 'success',
      message: t('auth.loginSuccessAudit'),
      source: 'local',
    });
    const role = existingUser.role || 'cliente';
    setUser({ email: existingUser.email, name: existingUser.name || '', role });
    return { ok: true, role };
  }, [users]);

  /**
   * Registers a new user and starts authenticated session.
   * @param {{ name: string, email: string, password: string, confirmPassword: string, role?: string }} payload
   * @returns {{ ok: boolean, error?: string }}
   */
  const register = useCallback(async ({ name, email, password, confirmPassword, role }) => {
    const safeName = name.trim();
    const safeEmail = email.trim().toLowerCase();
    const safeRole = String(role || 'cliente').toLowerCase();

    if (safeName.length < 2) {
      return { ok: false, error: 'El nombre debe tener al menos 2 caracteres.' };
    }

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(safeEmail)) {
      return { ok: false, error: t('common.invalidEmail') };
    }

    if (!isStrongPassword(password)) {
      return { ok: false, error: t('auth.registerPasswordInvalid') };
    }

    if (password !== confirmPassword) {
      return { ok: false, error: t('common.passwordsMismatch') };
    }

    if (users.some((item) => item.email === safeEmail)) {
      return { ok: false, error: t('auth.emailTaken') };
    }

    if (safeRole !== 'admin' && safeRole !== 'cliente') {
      return { ok: false, error: t('common.invalidRole') };
    }

    const passwordHash = await hashPassword(password);
    const createdUser = { name: safeName, email: safeEmail, passwordHash, role: safeRole };
    setUsers((prev) => [...prev, createdUser]);
    setUser({ email: createdUser.email, name: createdUser.name, role: createdUser.role });
    appendAuthAuditEvent({
      code: 'register_success',
      type: 'success',
      message: t('auth.registerSuccessAudit'),
      source: 'local',
    });
    return { ok: true };
  }, [t, users]);

  /**
   * Resets an existing user's password by email.
   * @param {{ email: string, password: string, confirmPassword: string }} payload
   * @returns {{ ok: boolean, error?: string }}
   */
  const resetPassword = useCallback(async ({ email, password, confirmPassword }) => {
    const safeEmail = email.trim().toLowerCase();

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(safeEmail)) {
      return { ok: false, error: t('common.invalidEmail') };
    }

    if (!isStrongPassword(password)) {
      return { ok: false, error: t('auth.resetPasswordInvalid') };
    }

    if (password !== confirmPassword) {
      return { ok: false, error: t('common.passwordsMismatch') };
    }

    const exists = users.some((item) => item.email === safeEmail);
    if (!exists) {
      return { ok: false, error: t('auth.accountMissing') };
    }

    const passwordHash = await hashPassword(password);

    setUsers((prev) => prev.map((item) => (
      item.email === safeEmail
        ? { ...item, passwordHash }
        : item
    )));

    appendAuthAuditEvent({
      code: 'password_reset',
      type: 'info',
      message: t('auth.passwordResetAudit'),
      source: 'local',
    });

    return { ok: true };
  }, [t, users]);

  const value = useMemo(() => ({
    user,
    isAuthenticated: !!user,
    authNotice,
    clearAuthNotice,
    getAuthAuditTrail,
    clearAuthAuditTrail,
    showSessionExpiryWarning,
    sessionExpiryRemainingSeconds,
    extendSession,
    login,
    register,
    resetPassword,
    logout,
  }), [authNotice, clearAuthAuditTrail, clearAuthNotice, extendSession, getAuthAuditTrail, login, logout, register, resetPassword, sessionExpiryRemainingSeconds, showSessionExpiryWarning, user]);

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
