// Generated by GitHub Copilot
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AuthContext } from './AuthStateContext';

const AUTH_STORAGE_KEY = 'tienda_react_auth_user';
const USERS_STORAGE_KEY = 'tienda_react_auth_users';
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const HASH_PREFIX = 'sha256:';
const LOGIN_WINDOW_MS = 10 * 60 * 1000;
const LOGIN_LOCK_MS = 60 * 1000;
const MAX_LOGIN_ATTEMPTS = 5;

/**
 * Hashes a password using SHA-256 via the Web Crypto API.
 * Returns a prefixed hex digest to distinguish hashed from legacy plain-text values.
 * @param {string} password
 * @returns {Promise<string>}
 */
async function hashPassword(password) {
  const encoded = new TextEncoder().encode(password);
  const hashBuffer = await crypto.subtle.digest('SHA-256', encoded);
  const hex = Array.from(new Uint8Array(hashBuffer))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
  return `${HASH_PREFIX}${hex}`;
}

/**
 * Verifies a plain-text input against a stored password.
 * Supports SHA-256 hashed passwords (registered users) and plain-text (built-in demo users).
 * @param {string} input Plain-text password entered by the user.
 * @param {string} stored Stored password (hashed or plain-text for demo users).
 * @returns {Promise<boolean>}
 */
async function verifyPassword(input, stored) {
  if (stored.startsWith(HASH_PREFIX)) {
    const inputHash = await hashPassword(input);
    return inputHash === stored;
  }
  // Backward compat: built-in demo users keep plain-text passwords in source.
  return input === stored;
}

const DEFAULT_USERS = [
  {
    name: 'Administrador',
    email: 'admin@tienda.com',
    password: 'Admin123',
    role: 'admin',
  },
  {
    name: 'Cliente Demo',
    email: 'cliente@tienda.com',
    password: 'Cliente123',
    role: 'cliente',
  },
];

/**
 * Merges stored users with built-in demo users by email.
 * Stored users take precedence if emails collide.
 * @param {Array<{ name: string, email: string, password: string, role?: string }>} storedUsers
 * @returns {Array<{ name: string, email: string, password: string, role?: string }>}
 */
function mergeDefaultUsers(storedUsers) {
  const byEmail = new Map(DEFAULT_USERS.map((item) => [item.email, item]));
  storedUsers.forEach((item) => {
    byEmail.set(item.email, item);
  });
  return Array.from(byEmail.values());
}

/**
 * Lightweight email format validation for auth forms.
 * @param {string} email
 * @returns {boolean}
 */
function isValidEmail(email) {
  return EMAIL_REGEX.test(email);
}

/**
 * Writes JSON to storage in a best-effort way.
 * @param {string} key
 * @param {unknown} value
 */
function safeWriteStorage(key, value) {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch {
    // Best-effort persistence only.
  }
}

/**
 * Removes a storage key in a best-effort way.
 * @param {string} key
 */
function safeRemoveStorage(key) {
  try {
    localStorage.removeItem(key);
  } catch {
    // Best-effort persistence only.
  }
}

/**
 * Reads persisted auth user from localStorage in a safe way.
 * @returns {{ email: string } | null}
 */
function getInitialUser() {
  try {
    const rawUser = localStorage.getItem(AUTH_STORAGE_KEY);
    if (!rawUser) {
      return null;
    }

    const parsed = JSON.parse(rawUser);
    if (!parsed?.email) {
      return null;
    }

    return {
      email: String(parsed.email),
      name: parsed.name ? String(parsed.name) : '',
      role: parsed.role ? String(parsed.role) : 'cliente',
    };
  } catch {
    return null;
  }
}

/**
 * Reads persisted users from localStorage in a safe way.
 * @returns {Array<{ name: string, email: string, password: string, role?: string }>}
 */
function getInitialUsers() {
  try {
    const rawUsers = localStorage.getItem(USERS_STORAGE_KEY);
    if (!rawUsers) {
      return DEFAULT_USERS;
    }

    const parsed = JSON.parse(rawUsers);
    if (!Array.isArray(parsed)) {
      return DEFAULT_USERS;
    }

    const normalizedUsers = parsed
      .filter((item) => item?.email && item?.password)
      .map((item) => ({
        name: String(item.name || ''),
        email: String(item.email).toLowerCase(),
        password: String(item.password),
        role: item.role ? String(item.role) : 'cliente',
      }));

    return mergeDefaultUsers(normalizedUsers);
  } catch {
    return DEFAULT_USERS;
  }
}

/**
 * AuthProvider stores login status and exposes auth actions.
 * Security note: password is never persisted in storage.
 * @param {{ children: React.ReactNode }} props
 */
export function AuthProvider({ children }) {
  const [user, setUser] = useState(getInitialUser);
  const [users, setUsers] = useState(getInitialUsers);
  const loginAttemptsRef = useRef(new Map());

  useEffect(() => {
    let cancelled = false;

    /** Migrates legacy plain-text passwords in storage to SHA-256 hashes. */
    const migrateLegacyPasswords = async () => {
      const needsMigration = users.some((item) => !String(item.password).startsWith(HASH_PREFIX));
      if (!needsMigration) {
        return;
      }

      const migratedUsers = await Promise.all(users.map(async (item) => {
        if (String(item.password).startsWith(HASH_PREFIX)) {
          return item;
        }

        return {
          ...item,
          password: await hashPassword(String(item.password)),
        };
      }));

      if (!cancelled) {
        setUsers(migratedUsers);
      }
    };

    migrateLegacyPasswords();
    return () => {
      cancelled = true;
    };
  }, [users]);

  useEffect(() => {
    if (!user) {
      safeRemoveStorage(AUTH_STORAGE_KEY);
      return;
    }

    // Persist name and role so RequireRole works after page reload.
    safeWriteStorage(AUTH_STORAGE_KEY, {
      email: user.email,
      name: user.name || '',
      role: user.role || 'cliente',
    });
  }, [user]);

  useEffect(() => {
    safeWriteStorage(USERS_STORAGE_KEY, users);
  }, [users]);

  /**
   * Performs a minimal credential validation and starts session.
   * @param {{ email: string, password: string }} credentials
   * @returns {Promise<{ ok: boolean, role?: string, error?: string, lockedUntil?: number, retryAfterMs?: number }>}
   */
  const login = useCallback(async ({ email, password }) => {
    const safeEmail = email.trim().toLowerCase();
    const now = Date.now();
    if (!isValidEmail(safeEmail)) {
      return { ok: false, error: 'Ingresa un correo válido.' };
    }

    if (!password || password.length < 6) {
      return { ok: false, error: 'La contraseña debe tener al menos 6 caracteres.' };
    }

    const attemptState = loginAttemptsRef.current.get(safeEmail);
    if (attemptState?.lockedUntil && now < attemptState.lockedUntil) {
      return {
        ok: false,
        error: 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.',
        lockedUntil: attemptState.lockedUntil,
        retryAfterMs: Math.max(0, attemptState.lockedUntil - now),
      };
    }

    const existingUser = users.find((item) => item.email === safeEmail);
    if (!existingUser) {
      const recentAttempts = (attemptState?.attempts || []).filter((ts) => now - ts <= LOGIN_WINDOW_MS);
      const updatedAttempts = [...recentAttempts, now];
      const shouldLock = updatedAttempts.length >= MAX_LOGIN_ATTEMPTS;
      const lockedUntil = shouldLock ? now + LOGIN_LOCK_MS : 0;

      loginAttemptsRef.current.set(safeEmail, {
        attempts: updatedAttempts,
        lockedUntil,
      });

      if (shouldLock) {
        return {
          ok: false,
          error: 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.',
          lockedUntil,
          retryAfterMs: LOGIN_LOCK_MS,
        };
      }

      return { ok: false, error: 'Correo o contraseña incorrectos.' };
    }

    const passwordMatch = await verifyPassword(password, existingUser.password);
    if (!passwordMatch) {
      const recentAttempts = (attemptState?.attempts || []).filter((ts) => now - ts <= LOGIN_WINDOW_MS);
      const updatedAttempts = [...recentAttempts, now];
      const shouldLock = updatedAttempts.length >= MAX_LOGIN_ATTEMPTS;
      const lockedUntil = shouldLock ? now + LOGIN_LOCK_MS : 0;

      loginAttemptsRef.current.set(safeEmail, {
        attempts: updatedAttempts,
        lockedUntil,
      });

      if (shouldLock) {
        return {
          ok: false,
          error: 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.',
          lockedUntil,
          retryAfterMs: LOGIN_LOCK_MS,
        };
      }

      return { ok: false, error: 'Correo o contraseña incorrectos.' };
    }

    loginAttemptsRef.current.delete(safeEmail);

    const role = existingUser.role || 'cliente';
    setUser({ email: existingUser.email, name: existingUser.name || '', role });
    return { ok: true, role };
  }, [users]);

  /**
   * Registers a new user and starts authenticated session.
   * @param {{ name: string, email: string, password: string, confirmPassword: string }} payload
   * @returns {{ ok: boolean, error?: string }}
   */
  const register = useCallback(async ({ name, email, password, confirmPassword }) => {
    const safeName = name.trim();
    const safeEmail = email.trim().toLowerCase();

    if (safeName.length < 2) {
      return { ok: false, error: 'El nombre debe tener al menos 2 caracteres.' };
    }

    if (!isValidEmail(safeEmail)) {
      return { ok: false, error: 'Ingresa un correo válido.' };
    }

    if (!password || password.length < 6) {
      return { ok: false, error: 'La contraseña debe tener al menos 6 caracteres.' };
    }

    if (password !== confirmPassword) {
      return { ok: false, error: 'Las contraseñas no coinciden.' };
    }

    if (users.some((item) => item.email === safeEmail)) {
      return { ok: false, error: 'Ese correo ya está registrado.' };
    }

    const hashedPassword = await hashPassword(password);
    const createdUser = { name: safeName, email: safeEmail, password: hashedPassword, role: 'cliente' };
    setUsers((prev) => [...prev, createdUser]);
    setUser({ email: createdUser.email, name: createdUser.name, role: createdUser.role });
    return { ok: true };
  }, [users]);

  /**
   * Resets an existing user's password by email.
   * @param {{ email: string, password: string, confirmPassword: string }} payload
   * @returns {{ ok: boolean, error?: string }}
   */
  const resetPassword = useCallback(async ({ email, password, confirmPassword }) => {
    const safeEmail = email.trim().toLowerCase();

    if (!isValidEmail(safeEmail)) {
      return { ok: false, error: 'Ingresa un correo válido.' };
    }

    if (!password || password.length < 6) {
      return { ok: false, error: 'La nueva contraseña debe tener al menos 6 caracteres.' };
    }

    if (password !== confirmPassword) {
      return { ok: false, error: 'Las contraseñas no coinciden.' };
    }

    const exists = users.some((item) => item.email === safeEmail);
    if (!exists) {
      return { ok: false, error: 'No existe una cuenta con ese correo.' };
    }

    const hashedPassword = await hashPassword(password);
    setUsers((prev) => prev.map((item) => (
      item.email === safeEmail
        ? { ...item, password: hashedPassword }
        : item
    )));

    return { ok: true };
  }, [users]);

  /** Ends the active user session. Accepts optional metadata for compatibility with callers. */
  const logout = useCallback((_options) => {
    setUser(null);
  }, []);

  const value = useMemo(() => ({
    user,
    isAuthenticated: !!user,
    login,
    register,
    resetPassword,
    logout,
  }), [login, logout, register, resetPassword, user]);

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
