// Generated by GitHub Copilot
// Para que sirve: Definicion del contexto de autenticacion.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { createContext } from 'react';

/**
 * Dedicated auth context object to keep Fast Refresh stable.
 */
export const AuthContext = createContext(null);
