// Generated by GitHub Copilot
// Para que sirve: Declara el objeto de contexto de autenticación (AuthContext).
//   Separado de AuthContext.jsx para estabilizar React Fast Refresh: un módulo que solo
//   exporta createContext() no activa el hot-reload de los componentes que lo consumen.
// Dónde tocar cambios: no hay lógica aquí; toda la lógica del provider está en AuthContext.jsx.
import { createContext } from 'react';

/**
 * Dedicated auth context object to keep Fast Refresh stable.
 */
export const AuthContext = createContext(null);
