// Generated by GitHub Copilot
import { act, render } from '@testing-library/react';
import { beforeEach, describe, expect, it } from 'vitest';
import { AuthProvider } from './AuthContext';
import useAuth from './useAuth';

let authApi;

/**
 * Captures AuthContext API for direct invocation in tests.
 * This keeps tests focused on provider business rules, not UI details.
 * @returns {null}
 */
function AuthProbe() {
  authApi = useAuth();
  return null;
}

describe('AuthContext security hardening', () => {
  beforeEach(() => {
    localStorage.clear();
    authApi = undefined;
  });

  it('stores newly registered passwords as SHA-256 hashes', async () => {
    render(
      <AuthProvider>
        <AuthProbe />
      </AuthProvider>
    );

    await act(async () => {
      const result = await authApi.register({
        name: 'Persona Test',
        email: 'test@example.com',
        password: 'Test1234',
        confirmPassword: 'Test1234',
      });
      expect(result.ok).toBe(true);
    });

    const rawUsers = localStorage.getItem('tienda_react_auth_users');
    const users = JSON.parse(rawUsers || '[]');
    const created = users.find((item) => item.email === 'test@example.com');

    expect(created).toBeTruthy();
    expect(created.password).toMatch(/^sha256:[a-f0-9]{64}$/);
    expect(created.password).not.toBe('Test1234');
  });

  it('temporarily blocks login after repeated failed attempts', async () => {
    render(
      <AuthProvider>
        <AuthProbe />
      </AuthProvider>
    );

    for (let i = 0; i < 5; i += 1) {
      await act(async () => {
        const result = await authApi.login({
          email: 'admin@tienda.com',
          password: 'WrongPass123',
        });
        expect(result.ok).toBe(false);
      });
    }

    let blockedResult;
    await act(async () => {
      blockedResult = await authApi.login({
        email: 'admin@tienda.com',
        password: 'WrongPass123',
      });
    });

    expect(blockedResult.ok).toBe(false);
    expect(blockedResult.error).toMatch(/demasiados intentos/i);
  });
});
