// Generated by GitHub Copilot
import { useMemo, useEffect, useReducer, useState } from 'react';
import { CartContext } from './CartStateContext';
import { findCoupon, calcDiscount } from '../data/coupons';

/**
 * CartContext provides global cart state and dispatch to all child components.
 * Uses useReducer for predictable state management.
 */
const CART_STORAGE_KEY = 'tienda_react_cart';
const FAVORITES_STORAGE_KEY = 'tienda_react_favorites';

/**
 * Reads persisted cart from localStorage safely.
 * @returns {Array}
 */
function getInitialCart() {
  try {
    const rawCart = localStorage.getItem(CART_STORAGE_KEY);
    return rawCart ? JSON.parse(rawCart) : [];
  } catch {
    return [];
  }
}

/**
 * Reads persisted favorites from localStorage safely.
 * @returns {Array<number | string>}
 */
function getInitialFavorites() {
  try {
    const rawFavorites = localStorage.getItem(FAVORITES_STORAGE_KEY);
    const parsed = rawFavorites ? JSON.parse(rawFavorites) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

/**
 * Reducer that handles all cart actions.
 * @param {Array} state - Current cart items array.
 * @param {{ type: string, payload: object }} action - Dispatched action.
 * @returns {Array} New cart state.
 */
function cartReducer(state, action) {
  switch (action.type) {
    case 'ADD_ITEM': {
      const existing = state.find((item) => item.id === action.payload.id);
      if (existing) {
        return state.map((item) =>
          item.id === action.payload.id
            ? { ...item, quantity: item.quantity + 1 }
            : item
        );
      }
      return [...state, { ...action.payload, quantity: 1 }];
    }
    case 'REMOVE_ITEM':
      return state.filter((item) => item.id !== action.payload.id);
    case 'UPDATE_QUANTITY': {
      if (action.payload.quantity <= 0) {
        return state.filter((item) => item.id !== action.payload.id);
      }
      return state.map((item) =>
        item.id === action.payload.id
          ? { ...item, quantity: action.payload.quantity }
          : item
      );
    }
    case 'CLEAR_CART':
      return [];
    case 'ADD_ORDER_ITEMS': {
      const incomingItems = Array.isArray(action.payload?.items) ? action.payload.items : [];
      if (incomingItems.length === 0) {
        return state;
      }

      const byId = new Map(state.map((item) => [item.id, { ...item }]));

      incomingItems.forEach((item) => {
        if (!item || item.id === undefined || item.id === null) {
          return;
        }

        const quantity = Math.max(1, Number.parseInt(item.quantity, 10) || 1);
        const existing = byId.get(item.id);

        if (existing) {
          byId.set(item.id, { ...existing, quantity: existing.quantity + quantity });
          return;
        }

        byId.set(item.id, { ...item, quantity });
      });

      return Array.from(byId.values());
    }
    default:
      return state;
  }
}

/**
 * CartProvider wraps the app and provides cart state via Context API.
 * @param {{ children: React.ReactNode }} props
 */
export function CartProvider({ children }) {
  const [cart, dispatch] = useReducer(cartReducer, [], getInitialCart);
  const [toast, setToast] = useState({ message: '', type: 'info' });
  const [coupon, setCoupon] = useState(null);
  const [favorites, setFavorites] = useState(getInitialFavorites);

  useEffect(() => {
    localStorage.setItem(CART_STORAGE_KEY, JSON.stringify(cart));
  }, [cart]);

  useEffect(() => {
    localStorage.setItem(FAVORITES_STORAGE_KEY, JSON.stringify(favorites));
  }, [favorites]);

  // Derive effective coupon: auto-invalidate when cart empties.
  const effectiveCoupon = useMemo(
    () => (cart.length === 0 ? null : coupon),
    [cart.length, coupon]
  );

  useEffect(() => {
    if (!toast.message) {
      return undefined;
    }

    const timeoutId = setTimeout(() => {
      setToast({ message: '', type: 'info' });
    }, 2500);

    return () => clearTimeout(timeoutId);
  }, [toast]);

  /**
   * Shows a toast message for user feedback.
   * @param {string} message
   * @param {'info' | 'success' | 'error'} type
   */
  const showToast = (message, type = 'info') => {
    setToast({ message, type });
  };

  const dismissToast = () => {
    setToast({ message: '', type: 'info' });
  };

  const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
  const totalPrice = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const favoriteCount = favorites.length;
  const discountAmount = calcDiscount(effectiveCoupon, totalPrice);
  const finalPrice = Math.max(0, totalPrice - discountAmount);

  /**
   * Tries to apply a coupon code. Shows toast feedback.
   * @param {string} rawCode
   * @returns {boolean} Whether the code was valid.
   */
  const applyCoupon = (rawCode) => {
    const found = findCoupon(rawCode);
    if (!found) {
      showToast('Cupón inválido o no existe', 'error');
      return false;
    }
    if (coupon?.code === found.code) {
      showToast(`El cupón "${found.code}" ya está aplicado`, 'info');
      return false;
    }
    setCoupon(found);
    showToast(`Cupón "${found.code}" aplicado — ${found.label}`, 'success');
    return true;
  };

  /** Removes the active coupon. */
  const removeCoupon = () => {
    setCoupon(null);
    showToast('Cupón eliminado', 'info');
  };

  /**
   * Returns whether a product id is currently in favorites.
   * @param {number | string} productId
   * @returns {boolean}
   */
  const isFavorite = (productId) => favorites.includes(productId);

  /**
   * Toggles a product id in favorites and notifies the user.
   * @param {{ id: number | string, name: string }} product
   */
  const toggleFavorite = (product) => {
    const exists = favorites.includes(product.id);

    if (exists) {
      setFavorites((prev) => prev.filter((id) => id !== product.id));
      showToast(`Quitaste "${product.name}" de favoritos`, 'info');
      return;
    }

    setFavorites((prev) => [...prev, product.id]);
    showToast(`Agregaste "${product.name}" a favoritos`, 'success');
  };

  /** Clears all favorites in one action with a single feedback toast. */
  const clearFavorites = () => {
    if (favorites.length === 0) {
      showToast('No hay favoritos para quitar', 'info');
      return;
    }

    const removedCount = favorites.length;
    setFavorites([]);
    showToast(`Quitaste ${removedCount} favorito${removedCount !== 1 ? 's' : ''}`, 'info');
  };

  /** Restores favorites from a previous snapshot for undo operations. */
  const restoreFavorites = (snapshotIds) => {
    if (!Array.isArray(snapshotIds) || snapshotIds.length === 0) {
      showToast('No hay favoritos para restaurar', 'info');
      return;
    }

    const restored = Array.from(new Set(snapshotIds));
    setFavorites(restored);
    showToast(`Favoritos restaurados (${restored.length})`, 'success');
  };

  /**
   * Removes all references to a product from cart and favorites.
   * @param {number | string} productId
   */
  const removeProductReferences = (productId) => {
    dispatch({ type: 'REMOVE_ITEM', payload: { id: productId } });
    setFavorites((prev) => prev.filter((id) => id !== productId));
  };

  return (
    <CartContext.Provider value={{ cart, dispatch, totalItems, totalPrice, discountAmount, finalPrice, coupon: effectiveCoupon, applyCoupon, removeCoupon, favorites, favoriteCount, isFavorite, toggleFavorite, clearFavorites, restoreFavorites, removeProductReferences, toast, showToast }}>
      {children}
    </CartContext.Provider>
  );
}
