// Generated by GitHub Copilot
// Para que sirve: Proveedor de carrito, favoritos, cupones y metricas de compra.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useMemo, useCallback, useEffect, useReducer, useRef, useState } from 'react';
import { CartContext } from './CartStateContext';
import { MAX_ITEM_QUANTITY } from './cartConstants';
import { cartReducer } from './cartReducer';
import { findCoupon, calcDiscount } from '../data/coupons';

/**
 * CartContext provides global cart state and dispatch to all child components.
 * Uses useReducer for predictable state management.
 */
const CART_STORAGE_KEY = 'tienda_react_cart';
const FAVORITES_STORAGE_KEY = 'tienda_react_favorites';

/**
 * Reads persisted cart from localStorage safely.
 * @returns {Array}
 */
function getInitialCart() {
  try {
    const rawCart = localStorage.getItem(CART_STORAGE_KEY);
    const parsed = rawCart ? JSON.parse(rawCart) : [];
    if (!Array.isArray(parsed)) {
      return [];
    }

    return parsed
      .filter((item) => item && item.id !== undefined && item.id !== null)
      .map((item) => {
        const quantity = Number.parseInt(item.quantity, 10);
        return {
          ...item,
          quantity: Number.isNaN(quantity)
            ? 1
            : Math.min(Math.max(1, quantity), MAX_ITEM_QUANTITY),
        };
      });
  } catch {
    return [];
  }
}

/**
 * Reads persisted favorites from localStorage safely.
 * Filters out duplicates and ensures array integrity.
 * @returns {Array<number | string>}
 */
function getInitialFavorites() {
  try {
    const rawFavorites = localStorage.getItem(FAVORITES_STORAGE_KEY);
    const parsed = rawFavorites ? JSON.parse(rawFavorites) : [];
    // Validate array and remove duplicates for data integrity
    if (!Array.isArray(parsed)) {
      return [];
    }
    // Remove duplicates by converting to Set and back
    return Array.from(new Set(parsed));
  } catch {
    return [];
  }
}

/**
 * Writes JSON data to localStorage safely.
 * Prevents runtime crashes in restricted storage environments.
 * @param {string} key
 * @param {unknown} value
 */
function safeWriteStorage(key, value) {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch {
    // Best-effort persistence only.
  }
}

/**
 * CartProvider wraps the app and provides cart state via Context API.
 * @param {{ children: React.ReactNode }} props
 */
export function CartProvider({ children }) {
  const [cart, dispatch] = useReducer(cartReducer, [], getInitialCart);
  const [toast, setToast] = useState({ message: '', type: 'info' });
  const [coupon, setCoupon] = useState(null);
  const [favorites, setFavorites] = useState(getInitialFavorites);
  const couponRef = useRef(coupon);
  const favoritesRef = useRef(favorites);

  useEffect(() => {
    couponRef.current = coupon;
  }, [coupon]);

  useEffect(() => {
    favoritesRef.current = favorites;
  }, [favorites]);

  useEffect(() => {
    safeWriteStorage(CART_STORAGE_KEY, cart);
  }, [cart]);

  useEffect(() => {
    safeWriteStorage(FAVORITES_STORAGE_KEY, favorites);
  }, [favorites]);

  // Derive effective coupon: auto-invalidate when cart empties.
  const effectiveCoupon = useMemo(
    () => (cart.length === 0 ? null : coupon),
    [cart.length, coupon]
  );

  useEffect(() => {
    if (!toast.message) {
      return undefined;
    }

    const timeoutId = setTimeout(() => {
      setToast({ message: '', type: 'info' });
    }, 2500);

    return () => clearTimeout(timeoutId);
  }, [toast]);

  /**
   * Shows a toast message for user feedback.
   * Wrapped in useCallback so memo'd children (e.g. ProductCard) never re-render
   * just because CartProvider re-rendered for an unrelated state change.
   * @param {string} message
   * @param {'info' | 'success' | 'error'} type
   */
  const showToast = useCallback((message, type = 'info') => {
    setToast({ message, type });
  }, []);

  /** Clears the current toast. Stable reference — safe to use in dependency arrays. */
  const dismissToast = useCallback(() => {
    setToast({ message: '', type: 'info' });
  }, []);

  const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
  const totalPrice = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const favoriteCount = favorites.length;
  const discountAmount = calcDiscount(effectiveCoupon, totalPrice);
  const finalPrice = Math.max(0, totalPrice - discountAmount);

  /**
   * Tries to apply a coupon code. Shows toast feedback.
   * @param {string} rawCode
   * @returns {boolean} Whether the code was valid.
   */
  // useCallback: stable reference while still reading latest coupon from ref.
  const applyCoupon = useCallback((rawCode) => {
    const found = findCoupon(rawCode);
    if (!found) {
      showToast('Cupón inválido o no existe', 'error');
      return false;
    }
    if (couponRef.current?.code === found.code) {
      showToast(`El cupón "${found.code}" ya está aplicado`, 'info');
      return false;
    }
    setCoupon(found);
    showToast(`Cupón "${found.code}" aplicado — ${found.label}`, 'success');
    return true;
  }, [showToast]);

  /** Removes the active coupon. */
  const removeCoupon = useCallback(() => {
    setCoupon(null);
    showToast('Cupón eliminado', 'info');
  }, [showToast]);

  /**
   * Returns whether a product id is currently in favorites.
   * @param {number | string} productId
   * @returns {boolean}
   */
  // useCallback: stable reference while reading latest favorites from ref.
  const isFavorite = useCallback((productId) => favoritesRef.current.includes(productId), []);

  /**
   * Toggles a product id in favorites and notifies the user.
   * Depends on favorites (to detect whether the product already exists) and
   * showToast (stable — useCallback with empty deps).
   * @param {{ id: number | string, name: string }} product
   */
  const toggleFavorite = useCallback((product) => {
    const exists = favoritesRef.current.includes(product.id);

    if (exists) {
      setFavorites((prev) => prev.filter((id) => id !== product.id));
      showToast(`Quitaste "${product.name}" de favoritos`, 'info');
      return;
    }

    setFavorites((prev) => [...prev, product.id]);
    showToast(`Agregaste "${product.name}" a favoritos`, 'success');
  }, [showToast]);

  /** Clears all favorites in one action with a single feedback toast. */
  const clearFavorites = useCallback(() => {
    const currentFavorites = favoritesRef.current;
    if (currentFavorites.length === 0) {
      showToast('No hay favoritos para quitar', 'info');
      return;
    }

    const removedCount = currentFavorites.length;
    setFavorites([]);
    showToast(`Quitaste ${removedCount} favorito${removedCount !== 1 ? 's' : ''}`, 'info');
  }, [showToast]);

  /** Restores favorites from a previous snapshot for undo operations. */
  const restoreFavorites = useCallback((snapshotIds) => {
    if (!Array.isArray(snapshotIds) || snapshotIds.length === 0) {
      showToast('No hay favoritos para restaurar', 'info');
      return;
    }

    // De-duplicate snapshot values to avoid inconsistent favorite counters.
    const restored = Array.from(new Set(snapshotIds));
    setFavorites(restored);
    showToast(`Favoritos restaurados (${restored.length})`, 'success');
  }, [showToast]);

  /**
   * Removes all references to a product from cart and favorites.
   * @param {number | string} productId
   */
  // useCallback with empty deps: dispatch is stable (from useReducer), setFavorites too.
  const removeProductReferences = useCallback((productId) => {
    dispatch({ type: 'REMOVE_ITEM', payload: { id: productId } });
    setFavorites((prev) => prev.filter((id) => id !== productId));
  }, []);

  // Generated by GitHub Copilot
  // Memoize provider value so consumers only re-render when relevant data changes.
  const contextValue = useMemo(() => ({
    cart,
    dispatch,
    totalItems,
    totalPrice,
    discountAmount,
    finalPrice,
    coupon: effectiveCoupon,
    applyCoupon,
    removeCoupon,
    favorites,
    favoriteCount,
    isFavorite,
    toggleFavorite,
    clearFavorites,
    restoreFavorites,
    removeProductReferences,
    toast,
    showToast,
    dismissToast,
  }), [
    applyCoupon,
    cart,
    clearFavorites,
    discountAmount,
    dismissToast,
    dispatch,
    effectiveCoupon,
    favoriteCount,
    favorites,
    finalPrice,
    isFavorite,
    removeCoupon,
    removeProductReferences,
    restoreFavorites,
    showToast,
    toast,
    toggleFavorite,
    totalItems,
    totalPrice,
  ]);

  return (
    <CartContext.Provider value={contextValue}>
      {children}
    </CartContext.Provider>
  );
}
