// Generated by GitHub Copilot

/**
 * Maximum quantity allowed per cart line item.
 * Kept in a standalone module so context files only export React components.
 */
export const MAX_ITEM_QUANTITY = 99;
