// Generated by GitHub Copilot
import { createContext } from 'react';

/**
 * Dedicated context object kept separate for fast refresh compatibility.
 */
export const CartContext = createContext(null);
