// Generated by GitHub Copilot
import { createContext, useContext, useEffect, useReducer, useState } from 'react';

/**
 * CartContext provides global cart state and dispatch to all child components.
 * Uses useReducer for predictable state management.
 */
const CartContext = createContext(null);
const CART_STORAGE_KEY = 'tienda_react_cart';

/**
 * Reads persisted cart from localStorage safely.
 * @returns {Array}
 */
function getInitialCart() {
  try {
    const rawCart = localStorage.getItem(CART_STORAGE_KEY);
    return rawCart ? JSON.parse(rawCart) : [];
  } catch {
    return [];
  }
}

/**
 * Reducer that handles all cart actions.
 * @param {Array} state - Current cart items array.
 * @param {{ type: string, payload: object }} action - Dispatched action.
 * @returns {Array} New cart state.
 */
function cartReducer(state, action) {
  switch (action.type) {
    case 'ADD_ITEM': {
      const existing = state.find((item) => item.id === action.payload.id);
      if (existing) {
        return state.map((item) =>
          item.id === action.payload.id
            ? { ...item, quantity: item.quantity + 1 }
            : item
        );
      }
      return [...state, { ...action.payload, quantity: 1 }];
    }
    case 'REMOVE_ITEM':
      return state.filter((item) => item.id !== action.payload.id);
    case 'UPDATE_QUANTITY': {
      if (action.payload.quantity <= 0) {
        return state.filter((item) => item.id !== action.payload.id);
      }
      return state.map((item) =>
        item.id === action.payload.id
          ? { ...item, quantity: action.payload.quantity }
          : item
      );
    }
    case 'CLEAR_CART':
      return [];
    default:
      return state;
  }
}

/**
 * CartProvider wraps the app and provides cart state via Context API.
 * @param {{ children: React.ReactNode }} props
 */
export function CartProvider({ children }) {
  const [cart, dispatch] = useReducer(cartReducer, [], getInitialCart);
  const [toast, setToast] = useState({ message: '', type: 'info' });

  useEffect(() => {
    localStorage.setItem(CART_STORAGE_KEY, JSON.stringify(cart));
  }, [cart]);

  useEffect(() => {
    if (!toast.message) {
      return undefined;
    }

    const timeoutId = setTimeout(() => {
      setToast({ message: '', type: 'info' });
    }, 2500);

    return () => clearTimeout(timeoutId);
  }, [toast]);

  /**
   * Shows a toast message for user feedback.
   * @param {string} message
   * @param {'info' | 'success' | 'error'} type
   */
  const showToast = (message, type = 'info') => {
    setToast({ message, type });
  };

  const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
  const totalPrice = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);

  return (
    <CartContext.Provider value={{ cart, dispatch, totalItems, totalPrice, toast, showToast }}>
      {children}
    </CartContext.Provider>
  );
}

/**
 * Custom hook to consume CartContext.
 * @returns {{ cart: Array, dispatch: Function, totalItems: number, totalPrice: number, toast: { message: string, type: string }, showToast: Function }}
 */
export function useCart() {
  const context = useContext(CartContext);
  if (!context) {
    throw new Error('useCart debe usarse dentro de un CartProvider');
  }
  return context;
}
