// Generated by GitHub Copilot
import { createContext } from 'react';

/**
 * CartItemsContext: Provides cart items array and dispatch function.
 * Focused on cart mutation operations (add, remove, update quantity).
 * Minimal dependencies allow ProductCard and similar to avoid unnecessary re-renders
 * when other cart aspects change (UI feedback, favorites, totals).
 */
export const CartItemsContext = createContext(null);
