// Generated by GitHub Copilot
import { describe, it, expect, beforeEach, vi } from 'vitest';

/**
 * Unit tests for CartContext cart reducer logic.
 * Tests: ADD_ITEM, REMOVE_ITEM, UPDATE_QUANTITY, CLEAR_CART, ADD_ORDER_ITEMS
 * Focuses on core business rules: quantity capping, deduplication, edge cases.
 */

const MAX_ITEM_QUANTITY = 99;

// Mock reducer implementation extracted for testing
function cartReducer(state, action) {
  switch (action.type) {
    case 'ADD_ITEM': {
      const existing = state.find((item) => item.id === action.payload.id);
      if (existing) {
        return state.map((item) =>
          item.id === action.payload.id
            ? { ...item, quantity: Math.min(item.quantity + 1, MAX_ITEM_QUANTITY) }
            : item
        );
      }
      return [...state, { ...action.payload, quantity: 1 }];
    }
    case 'REMOVE_ITEM':
      return state.filter((item) => item.id !== action.payload.id);
    case 'UPDATE_QUANTITY': {
      if (action.payload.quantity <= 0) {
        return state.filter((item) => item.id !== action.payload.id);
      }
      const clampedQty = Math.min(Math.max(1, action.payload.quantity), MAX_ITEM_QUANTITY);
      return state.map((item) =>
        item.id === action.payload.id
          ? { ...item, quantity: clampedQty }
          : item
      );
    }
    case 'CLEAR_CART':
      return [];
    case 'ADD_ORDER_ITEMS': {
      const incomingItems = Array.isArray(action.payload?.items) ? action.payload.items : [];
      if (incomingItems.length === 0) {
        return state;
      }

      const byId = new Map(state.map((item) => [item.id, { ...item }]));

      incomingItems.forEach((item) => {
        if (!item || item.id === undefined || item.id === null) {
          return;
        }

        const quantity = Math.max(1, Number.parseInt(item.quantity, 10) || 1);
        const existing = byId.get(item.id);

        if (existing) {
          byId.set(item.id, { ...existing, quantity: Math.min(existing.quantity + quantity, MAX_ITEM_QUANTITY) });
          return;
        }

        byId.set(item.id, { ...item, quantity });
      });

      return Array.from(byId.values());
    }
    default:
      return state;
  }
}

describe('CartContext Reducer', () => {
  let initialState;

  beforeEach(() => {
    initialState = [];
  });

  describe('ADD_ITEM', () => {
    it('should add a new item to empty cart', () => {
      const product = { id: 1, name: 'Widget', price: 100, category: 'General', description: 'A widget' };
      const result = cartReducer(initialState, { type: 'ADD_ITEM', payload: product });

      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({ ...product, quantity: 1 });
    });

    it('should increment quantity if item already exists', () => {
      const item = { id: 1, name: 'Widget', price: 100, quantity: 2 };
      const product = { id: 1, name: 'Widget', price: 100, category: 'General', description: 'A widget' };
      const result = cartReducer([item], { type: 'ADD_ITEM', payload: product });

      expect(result).toHaveLength(1);
      expect(result[0].quantity).toBe(3);
    });

    it('should cap quantity at MAX_ITEM_QUANTITY', () => {
      const item = { id: 1, name: 'Widget', price: 100, quantity: MAX_ITEM_QUANTITY };
      const product = { id: 1, name: 'Widget', price: 100 };
      const result = cartReducer([item], { type: 'ADD_ITEM', payload: product });

      expect(result[0].quantity).toBe(MAX_ITEM_QUANTITY);
    });

    it('should not lose other items when adding', () => {
      const state = [
        { id: 1, name: 'Widget', price: 100, quantity: 2 },
        { id: 2, name: 'Gadget', price: 200, quantity: 1 },
      ];
      const product = { id: 3, name: 'Gizmo', price: 50 };
      const result = cartReducer(state, { type: 'ADD_ITEM', payload: product });

      expect(result).toHaveLength(3);
      expect(result.find((i) => i.id === 1).quantity).toBe(2);
      expect(result.find((i) => i.id === 2).quantity).toBe(1);
      expect(result.find((i) => i.id === 3).quantity).toBe(1);
    });
  });

  describe('REMOVE_ITEM', () => {
    it('should remove item from cart', () => {
      const state = [
        { id: 1, name: 'Widget', price: 100, quantity: 2 },
        { id: 2, name: 'Gadget', price: 200, quantity: 1 },
      ];
      const result = cartReducer(state, { type: 'REMOVE_ITEM', payload: { id: 1 } });

      expect(result).toHaveLength(1);
      expect(result[0].id).toBe(2);
    });

    it('should handle removing nonexistent item gracefully', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: 2 }];
      const result = cartReducer(state, { type: 'REMOVE_ITEM', payload: { id: 999 } });

      expect(result).toHaveLength(1);
    });

    it('should return empty array if removing last item', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: 2 }];
      const result = cartReducer(state, { type: 'REMOVE_ITEM', payload: { id: 1 } });

      expect(result).toHaveLength(0);
    });
  });

  describe('UPDATE_QUANTITY', () => {
    it('should update quantity to valid value', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: 2 }];
      const result = cartReducer(state, { type: 'UPDATE_QUANTITY', payload: { id: 1, quantity: 5 } });

      expect(result[0].quantity).toBe(5);
    });

    it('should remove item if quantity set to 0', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: 2 }];
      const result = cartReducer(state, { type: 'UPDATE_QUANTITY', payload: { id: 1, quantity: 0 } });

      expect(result).toHaveLength(0);
    });

    it('should remove item if quantity set to negative', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: 2 }];
      const result = cartReducer(state, { type: 'UPDATE_QUANTITY', payload: { id: 1, quantity: -1 } });

      expect(result).toHaveLength(0);
    });

    it('should clamp quantity between 1 and MAX_ITEM_QUANTITY', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: 2 }];
      const result = cartReducer(state, { type: 'UPDATE_QUANTITY', payload: { id: 1, quantity: MAX_ITEM_QUANTITY + 50 } });

      expect(result[0].quantity).toBe(MAX_ITEM_QUANTITY);
    });

    it('should clamp minimum to 1', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: 2 }];
      const result = cartReducer(state, { type: 'UPDATE_QUANTITY', payload: { id: 1, quantity: -100 } });

      expect(result).toHaveLength(0); // negative removes the item
    });
  });

  describe('CLEAR_CART', () => {
    it('should clear all items', () => {
      const state = [
        { id: 1, name: 'Widget', price: 100, quantity: 2 },
        { id: 2, name: 'Gadget', price: 200, quantity: 1 },
      ];
      const result = cartReducer(state, { type: 'CLEAR_CART' });

      expect(result).toHaveLength(0);
    });

    it('should handle clearing empty cart', () => {
      const result = cartReducer([], { type: 'CLEAR_CART' });

      expect(result).toHaveLength(0);
    });
  });

  describe('ADD_ORDER_ITEMS', () => {
    it('should add items from order to cart', () => {
      const orderItems = [
        { id: 1, name: 'Widget', price: 100, quantity: 2 },
        { id: 2, name: 'Gadget', price: 200, quantity: 1 },
      ];
      const result = cartReducer([], { type: 'ADD_ORDER_ITEMS', payload: { items: orderItems } });

      expect(result).toHaveLength(2);
      expect(result[0].quantity).toBe(2);
      expect(result[1].quantity).toBe(1);
    });

    it('should merge with existing cart items', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: 2 }];
      const orderItems = [{ id: 1, name: 'Widget', price: 100, quantity: 3 }];
      const result = cartReducer(state, { type: 'ADD_ORDER_ITEMS', payload: { items: orderItems } });

      expect(result).toHaveLength(1);
      expect(result[0].quantity).toBe(5); // 2 + 3
    });

    it('should cap reordered quantities at MAX_ITEM_QUANTITY', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: MAX_ITEM_QUANTITY - 10 }];
      const orderItems = [{ id: 1, name: 'Widget', price: 100, quantity: 50 }];
      const result = cartReducer(state, { type: 'ADD_ORDER_ITEMS', payload: { items: orderItems } });

      expect(result[0].quantity).toBe(MAX_ITEM_QUANTITY);
    });

    it('should handle empty order items array', () => {
      const state = [{ id: 1, name: 'Widget', price: 100, quantity: 2 }];
      const result = cartReducer(state, { type: 'ADD_ORDER_ITEMS', payload: { items: [] } });

      expect(result).toHaveLength(1);
    });

    it('should skip items with missing id', () => {
      const orderItems = [
        { name: 'Widget', price: 100, quantity: 2 }, // missing id
        { id: 2, name: 'Gadget', price: 200, quantity: 1 },
      ];
      const result = cartReducer([], { type: 'ADD_ORDER_ITEMS', payload: { items: orderItems } });

      expect(result).toHaveLength(1);
      expect(result[0].id).toBe(2);
    });

    it('should handle invalid payload gracefully', () => {
      const result = cartReducer([], { type: 'ADD_ORDER_ITEMS', payload: null });

      expect(result).toHaveLength(0);
    });

    it('should parse string quantities as numbers', () => {
      const orderItems = [{ id: 1, name: 'Widget', price: 100, quantity: '5' }];
      const result = cartReducer([], { type: 'ADD_ORDER_ITEMS', payload: { items: orderItems } });

      expect(result[0].quantity).toBe(5);
    });
  });

  describe('Favorites deduplication', () => {
    it('should remove duplicate IDs when loading favorites', () => {
      const duplicates = [1, 2, 1, 3, 2, 1];
      const unique = Array.from(new Set(duplicates));

      expect(unique).toEqual([1, 2, 3]);
      expect(unique).toHaveLength(3);
    });
  });
});
