// Generated by GitHub Copilot
// Para que sirve: Declara el objeto de contexto de productos (ProductContext).
//   Separado de ProductContext.jsx para estabilizar React Fast Refresh: un módulo que solo
//   exporta createContext() no activa el hot-reload de los componentes que lo consumen.
// Dónde tocar cambios: no hay lógica aquí; toda la lógica del provider está en ProductContext.jsx.
import { createContext } from 'react';

/**
 * Dedicated context object for product catalog state.
 */
export const ProductContext = createContext(null);
