// Generated by GitHub Copilot
import { useMemo, useState } from 'react';
import { ProductContext } from './ProductStateContext';
import { DEFAULT_PRODUCTS, buildCategories } from '../data/products';

const PRODUCTS_STORAGE_KEY = 'tienda_react_products';

/**
 * Reads persisted products from localStorage in a safe way.
 * @returns {Array<{ id: number, name: string, price: number, image: string, category: string, description: string }>}
 */
function getInitialProducts() {
  try {
    const rawProducts = localStorage.getItem(PRODUCTS_STORAGE_KEY);
    if (!rawProducts) {
      return DEFAULT_PRODUCTS;
    }

    const parsed = JSON.parse(rawProducts);
    if (!Array.isArray(parsed)) {
      return DEFAULT_PRODUCTS;
    }

    const normalized = parsed
      .filter((item) => item?.id !== undefined && item?.name)
      .map((item) => ({
        id: Number.parseInt(item.id, 10),
        name: String(item.name).trim(),
        price: Number(item.price),
        image: String(item.image || '').trim(),
        category: String(item.category || '').trim(),
        description: String(item.description || '').trim(),
      }))
      .filter((item) => Number.isInteger(item.id) && item.id > 0 && item.name.length > 1 && Number.isFinite(item.price) && item.price >= 0)
      .map((item) => ({
        ...item,
        image: item.image || 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=400',
        category: item.category || 'General',
        description: item.description || 'Producto sin descripción.',
      }));

    return normalized.length > 0 ? normalized : DEFAULT_PRODUCTS;
  } catch {
    return DEFAULT_PRODUCTS;
  }
}

/**
 * Validates and normalizes product form values.
 * Security note: trims and bounds user input to reduce malformed payloads.
 * @param {{ name: string, price: string|number, image: string, category: string, description: string }} payload
 * @returns {{ ok: true, data: { name: string, price: number, image: string, category: string, description: string } } | { ok: false, error: string }}
 */
function normalizeProductPayload(payload) {
  const name = String(payload?.name || '').trim();
  const category = String(payload?.category || '').trim();
  const description = String(payload?.description || '').trim();
  const image = String(payload?.image || '').trim();
  const price = Number(payload?.price);

  if (name.length < 2 || name.length > 120) {
    return { ok: false, error: 'El nombre debe tener entre 2 y 120 caracteres.' };
  }

  if (!Number.isFinite(price) || price < 0 || price > 1000000) {
    return { ok: false, error: 'El precio debe ser un número válido mayor o igual a 0.' };
  }

  if (category.length < 2 || category.length > 50) {
    return { ok: false, error: 'La categoría debe tener entre 2 y 50 caracteres.' };
  }

  if (description.length < 5 || description.length > 300) {
    return { ok: false, error: 'La descripción debe tener entre 5 y 300 caracteres.' };
  }

  if (image.length > 0 && !/^https?:\/\/[^\s]+$/i.test(image)) {
    return { ok: false, error: 'La imagen debe ser una URL válida (http o https).' };
  }

  return {
    ok: true,
    data: {
      name,
      price,
      image: image || 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=400',
      category,
      description,
    },
  };
}

/**
 * Product provider with in-memory state and local persistence.
 * @param {{ children: React.ReactNode }} props
 */
export function ProductProvider({ children }) {
  const [products, setProducts] = useState(getInitialProducts);

  /**
   * Creates a new product in catalog.
   * @param {{ name: string, price: string|number, image: string, category: string, description: string }} payload
   * @returns {{ ok: boolean, error?: string }}
   */
  const addProduct = (payload) => {
    const result = normalizeProductPayload(payload);
    if (!result.ok) {
      return result;
    }

    setProducts((prev) => {
      const nextId = prev.reduce((maxId, item) => Math.max(maxId, item.id), 0) + 1;
      const updated = [...prev, { id: nextId, ...result.data }];
      localStorage.setItem(PRODUCTS_STORAGE_KEY, JSON.stringify(updated));
      return updated;
    });

    return { ok: true };
  };

  /**
   * Updates an existing product.
   * @param {number} id
   * @param {{ name: string, price: string|number, image: string, category: string, description: string }} payload
   * @returns {{ ok: boolean, error?: string }}
   */
  const updateProduct = (id, payload) => {
    const productId = Number.parseInt(String(id), 10);
    if (!Number.isInteger(productId) || productId <= 0) {
      return { ok: false, error: 'Producto inválido.' };
    }

    const result = normalizeProductPayload(payload);
    if (!result.ok) {
      return result;
    }

    let found = false;
    setProducts((prev) => {
      const updated = prev.map((item) => {
        if (item.id !== productId) {
          return item;
        }
        found = true;
        return { ...item, ...result.data };
      });
      localStorage.setItem(PRODUCTS_STORAGE_KEY, JSON.stringify(updated));
      return updated;
    });

    if (!found) {
      return { ok: false, error: 'No se encontró el producto.' };
    }

    return { ok: true };
  };

  /**
   * Deletes a product from catalog by id.
   * @param {number} id
   * @returns {{ ok: boolean, error?: string }}
   */
  const deleteProduct = (id) => {
    const productId = Number.parseInt(String(id), 10);
    if (!Number.isInteger(productId) || productId <= 0) {
      return { ok: false, error: 'Producto inválido.' };
    }

    let removed = false;
    setProducts((prev) => {
      const updated = prev.filter((item) => {
        const shouldKeep = item.id !== productId;
        if (!shouldKeep) {
          removed = true;
        }
        return shouldKeep;
      });
      localStorage.setItem(PRODUCTS_STORAGE_KEY, JSON.stringify(updated));
      return updated;
    });

    if (!removed) {
      return { ok: false, error: 'No se encontró el producto.' };
    }

    return { ok: true };
  };

  const categories = useMemo(() => buildCategories(products), [products]);

  const value = useMemo(() => ({
    products,
    categories,
    addProduct,
    updateProduct,
    deleteProduct,
  }), [products, categories]);

  return <ProductContext.Provider value={value}>{children}</ProductContext.Provider>;
}
