// Generated by GitHub Copilot
import { useContext } from 'react';
import { AuthContext } from './AuthStateContext';

/**
 * Custom hook to consume AuthContext safely.
 * @returns {{ user: { email: string, name?: string } | null, isAuthenticated: boolean, login: Function, register: Function, resetPassword: Function, logout: Function }}
 */
export default function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth debe usarse dentro de un AuthProvider');
  }

  return context;
}
