// Generated by GitHub Copilot
// Para que sirve: Hook de consumo del contexto de autenticación.
//   Centraliza el acceso a user, isAuthenticated, login, logout, register y resetPassword.
//   Lanza un error claro si se usa fuera de AuthProvider para facilitar el debugging.
// Flujo principal: componentes llaman a useAuth() → obtienen AuthContext.value.
// Dónde tocar cambios: sólo si el contrato de AuthContext.value cambia en AuthContext.jsx.
import { useContext } from 'react';
import { AuthContext } from './AuthStateContext';

/**
 * Custom hook to consume AuthContext safely.
 * @returns {{
 *   user: { email: string, name?: string, role?: string } | null,
 *   isAuthenticated: boolean,
 *   login: (credentials: { email: string, password: string }) => Promise<{ ok: boolean, role?: string, error?: string, lockedUntil?: number, retryAfterMs?: number }>,
 *   register: Function,
 *   resetPassword: Function,
 *   logout: Function
 * }}
 */
export default function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth debe usarse dentro de un AuthProvider');
  }

  return context;
}
