// Generated by GitHub Copilot
// Para que sirve: Hook para consumir el contexto de autenticacion.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useContext } from 'react';
import { AuthContext } from './AuthStateContext';

/**
 * Custom hook to consume AuthContext safely.
 * @returns {{ user: { email: string, name?: string, role?: string } | null, isAuthenticated: boolean, login: Function, register: Function, resetPassword: Function, logout: Function }}
 */
export default function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth debe usarse dentro de un AuthProvider');
  }

  return context;
}
