// Generated by GitHub Copilot
import { useContext } from 'react';
import { CartContext } from './CartStateContext';

/**
 * Custom hook to consume CartContext safely.
 * @returns {{ cart: Array, dispatch: Function, totalItems: number, totalPrice: number, discountAmount: number, finalPrice: number, coupon: object|null, applyCoupon: Function, removeCoupon: Function, favorites: Array<number|string>, favoriteCount: number, isFavorite: Function, toggleFavorite: Function, toast: { message: string, type: string }, showToast: Function }}
 */
export default function useCart() {
  const context = useContext(CartContext);
  if (!context) {
    throw new Error('useCart debe usarse dentro de un CartProvider');
  }
  return context;
}
