// Generated by GitHub Copilot
// Para que sirve: Hook para consumir el contexto de carrito y favoritos.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { useContext } from 'react';
import { CartContext } from './CartStateContext';

/**
 * Custom hook to consume CartContext safely.
 * @returns {{ cart: Array, dispatch: Function, totalItems: number, totalPrice: number, discountAmount: number, finalPrice: number, coupon: object|null, applyCoupon: Function, removeCoupon: Function, favorites: Array<number|string>, favoriteCount: number, isFavorite: Function, toggleFavorite: Function, removeProductReferences: Function, toast: { message: string, type: string }, showToast: Function }}
 */
export default function useCart() {
  const context = useContext(CartContext);
  if (!context) {
    throw new Error('useCart debe usarse dentro de un CartProvider');
  }
  return context;
}
