// Generated by GitHub Copilot
import { useContext } from 'react';
import { ProductContext } from './ProductStateContext';

/**
 * Custom hook to consume ProductContext safely.
 * @returns {{ products: Array, categories: Array<string>, addProduct: Function, updateProduct: Function, deleteProduct: Function }}
 */
export default function useProducts() {
  const context = useContext(ProductContext);
  if (!context) {
    throw new Error('useProducts debe usarse dentro de un ProductProvider');
  }

  return context;
}
