// Generated by GitHub Copilot
// Para que sirve: Hook de consumo del contexto de productos.
//   Centraliza el acceso a products, categories, addProduct, updateProduct y deleteProduct.
//   Lanza un error claro si se usa fuera de ProductProvider para facilitar el debugging.
// Flujo principal: componentes llaman a useProducts() → obtienen ProductContext.value.
// Dónde tocar cambios: sólo si el contrato de ProductContext.value cambia en ProductContext.jsx.
import { useContext } from 'react';
import { ProductContext } from './ProductStateContext';

/**
 * Custom hook to consume ProductContext safely.
 * @returns {{ products: Array, categories: Array<string>, addProduct: Function, updateProduct: Function, deleteProduct: Function }}
 */
export default function useProducts() {
  const context = useContext(ProductContext);
  if (!context) {
    throw new Error('useProducts debe usarse dentro de un ProductProvider');
  }

  return context;
}
