// Generated by GitHub Copilot
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { lazy, Suspense } from 'react';
import { CartProvider } from './context/CartContext';
import { AuthProvider } from './context/AuthContext';
import { ProductProvider } from './context/ProductContext';
import { LanguageProvider } from './context/LanguageContext';
import useAuth from './context/useAuth';
import useLanguage from './context/useLanguage';
import Navbar from './components/Navbar';
import Toast from './components/Toast';
import ErrorBoundary from './components/ErrorBoundary';
import ProductSkeleton from './components/ProductSkeleton';
import RequireAuth from './components/RequireAuth';
import RequireRole from './components/RequireRole';

const Home = lazy(() => import('./pages/Home'));
const Cart = lazy(() => import('./pages/Cart'));
const Checkout = lazy(() => import('./pages/Checkout'));
const Orders = lazy(() => import('./pages/Orders'));
const Favorites = lazy(() => import('./pages/Favorites'));
const AdminProducts = lazy(() => import('./pages/AdminProducts'));
const NotFound = lazy(() => import('./pages/NotFound'));
const ProductDetail = lazy(() => import('./pages/ProductDetail'));
const Login = lazy(() => import('./pages/Login'));
const Register = lazy(() => import('./pages/Register'));
const ForgotPassword = lazy(() => import('./pages/ForgotPassword'));

/** Shared loading fallback for lazy route segments. */
function PageLoader() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 p-8" aria-busy="true">
      {Array.from({ length: 4 }).map((_, i) => <ProductSkeleton key={i} />)}
    </div>
  );
}

/**
 * Internal app shell that can safely consume providers.
 */
function AppShell() {
  const { isAuthenticated } = useAuth();
  const { t } = useLanguage();

  return (
    <div className="min-h-screen bg-gray-50">
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-70 focus:rounded-lg focus:bg-indigo-600 focus:px-4 focus:py-2 focus:font-medium focus:text-white"
      >
        {t('app.skipToContent')}
      </a>

      {isAuthenticated && <Navbar />}

      <div id="main-content" tabIndex="-1" className="outline-none">
        <ErrorBoundary>
          <Suspense fallback={<PageLoader />}>
            <Routes>
              <Route path="/login" element={<Login />} />
              <Route path="/registro" element={<Register />} />
              <Route path="/recuperar" element={<ForgotPassword />} />
              <Route path="/" element={<RequireAuth><Home /></RequireAuth>} />
              <Route path="/admin/productos" element={<RequireRole allowedRoles={['admin']}><AdminProducts /></RequireRole>} />
              <Route path="/carrito" element={<RequireRole allowedRoles={['cliente']}><Cart /></RequireRole>} />
              <Route path="/producto/:id" element={<RequireAuth><ProductDetail /></RequireAuth>} />
              <Route path="/checkout" element={<RequireRole allowedRoles={['cliente']}><Checkout /></RequireRole>} />
              <Route path="/pedidos" element={<RequireRole allowedRoles={['cliente']}><Orders /></RequireRole>} />
              <Route path="/favoritos" element={<RequireRole allowedRoles={['cliente']}><Favorites /></RequireRole>} />
              <Route path="/not-found" element={<NotFound />} />
              <Route path="*" element={<NotFound />} />
            </Routes>
          </Suspense>
        </ErrorBoundary>
      </div>

      <Toast />
    </div>
  );
}

/**
 * App root: sets up routing and global CartProvider.
 */
export default function App() {
  return (
    <BrowserRouter>
      <LanguageProvider>
        <AuthProvider>
          <ProductProvider>
            <CartProvider>
              <AppShell />
            </CartProvider>
          </ProductProvider>
        </AuthProvider>
      </LanguageProvider>
    </BrowserRouter>
  );
}
