// Generated by GitHub Copilot
import '@testing-library/jest-dom/vitest';
import { cleanup, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import App from './App';

const TEST_UI_TIMEOUT = 10000;

/**
 * Logs in with the given credentials and waits for the home heading.
 * @param {import('@testing-library/user-event').UserEvent} user
 * @param {string} email
 * @param {string} password
 */
async function loginAs(user, email, password) {
  const emailInput = await screen.findByLabelText(/Correo electrónico|Email/i, {}, { timeout: TEST_UI_TIMEOUT });
  const passwordInput = await screen.findByLabelText(/Contraseña|Password/i, {}, { timeout: TEST_UI_TIMEOUT });
  const submitBtn = await screen.findByRole('button', { name: /Entrar|Sign in/i }, { timeout: TEST_UI_TIMEOUT });
  await user.type(emailInput, email);
  await user.type(passwordInput, password);
  await user.click(submitBtn);
}

/** Waits for the Home route to finish lazy rendering. */
async function waitForHomeLoaded() {
  await screen.findByRole('heading', { name: /Nuestros Productos|Products/i }, { timeout: TEST_UI_TIMEOUT });
}

/** Waits for the Cart route heading to appear after navigation. */
async function waitForCartLoaded() {
  await screen.findByRole('heading', { name: /Carrito|Cart/i }, { timeout: TEST_UI_TIMEOUT });
}

/** Waits for NotFound route heading when navigating to an unknown path. */
async function waitForNotFoundLoaded() {
  await screen.findByRole('heading', { name: /Página no encontrada|Page not found/i }, { timeout: TEST_UI_TIMEOUT });
}

describe('App integration', () => {
  beforeEach(() => {
    localStorage.clear();
    window.history.pushState({}, '', '/');
  });

  afterEach(() => {
    cleanup();
  });

  it('client: login → add product → cart shows item', async () => {
    const user = userEvent.setup();
    render(<App />);

    await loginAs(user, 'cliente@tienda.com', 'Cliente123');
    await waitForHomeLoaded();

    const addButtons = await screen.findAllByRole('button', { name: /Añadir producto|Agregar producto|Add product/i });
    expect(addButtons.length).toBeGreaterThan(0);

    await user.click(addButtons[0]);
    const primaryNav = screen.getByRole('navigation', { name: /Navegación principal|Primary navigation/i });
    await user.click(within(primaryNav).getByRole('link', { name: /Carrito|Cart/i }));

    await waitForCartLoaded();

    // At least one quantity-control group confirms the cart has item rows.
    expect(screen.getAllByRole('group').length).toBeGreaterThan(0);
  });

  it('admin: login → no cart/buy buttons visible in product grid', async () => {
    const user = userEvent.setup();
    render(<App />);

    await loginAs(user, 'admin@tienda.com', 'Admin123');
    await waitForHomeLoaded();

    // Admin should NOT see add-to-cart or buy buttons.
    expect(screen.queryAllByRole('button', { name: /Añadir producto|Add product/i })).toHaveLength(0);
    expect(screen.queryAllByRole('button', { name: /Comprar|Buy/i })).toHaveLength(0);
    const primaryNav = screen.getByRole('navigation', { name: /Navegación principal|Primary navigation/i });
    expect(within(primaryNav).queryByRole('link', { name: /Carrito|Cart/i })).not.toBeInTheDocument();
  });

  it('client: cart persists after simulated page reload', async () => {
    const user = userEvent.setup();
    const { unmount } = render(<App />);

    await loginAs(user, 'cliente@tienda.com', 'Cliente123');
    await waitForHomeLoaded();

    const addButtons = await screen.findAllByRole('button', { name: /Añadir producto|Agregar producto|Add product/i });
    await user.click(addButtons[0]);

    // Simulate reload: unmount and remount with same localStorage.
    unmount();
    window.history.pushState({}, '', '/');
    render(<App />);

    // After reload user is still authenticated (role in localStorage) and reaches home.
    await waitForHomeLoaded();

    // Navigate to cart and confirm the item is still there.
    const primaryNav = screen.getByRole('navigation', { name: /Navegación principal|Primary navigation/i });
    await user.click(within(primaryNav).getByRole('link', { name: /Carrito|Cart/i }));

    await waitForCartLoaded();

    expect(screen.getAllByRole('group').length).toBeGreaterThan(0);
  });

  it('authenticated: unknown route renders quick category link with canonical href', async () => {
    localStorage.setItem('tienda_react_auth_user', JSON.stringify({
      email: 'cliente@tienda.com',
      name: 'Cliente Demo',
      role: 'cliente',
    }));
    window.history.pushState({}, '', '/ruta-desconocida');

    render(<App />);

    await waitForNotFoundLoaded();

    const electronicsQuickLink = screen
      .getAllByRole('link')
      .find((link) => link.getAttribute('href') === '/?categoria=electronics');

    expect(electronicsQuickLink).toBeTruthy();
    expect(window.location.pathname).toBe('/ruta-desconocida');
  });

  it('authenticated: canonical filtered home → product detail → breadcrumb category link returns to canonical filter', async () => {
    const user = userEvent.setup();
    localStorage.setItem('tienda_react_auth_user', JSON.stringify({
      email: 'cliente@tienda.com',
      name: 'Cliente Demo',
      role: 'cliente',
    }));
    window.history.pushState({}, '', '/?categoria=electronics');

    render(<App />);

    await waitForHomeLoaded();
    const homeHeading = screen.getByRole('heading', { name: /Nuestros Productos|Products/i });
    expect(homeHeading).toBeInTheDocument();

    const productName = await screen.findByText(/Auriculares Bluetooth/i);
    const productCard = productName.closest('article');
    expect(productCard).not.toBeNull();

    await user.click(within(productCard).getByRole('button', { name: /Ver|View/i }));

    await waitFor(() => {
      expect(screen.getByRole('heading', { level: 1, name: /Auriculares Bluetooth/i })).toBeInTheDocument();
    });

    const breadcrumb = screen.getByRole('navigation', { name: /Ruta de navegación|Breadcrumb/i });
    const breadcrumbLinks = within(breadcrumb).getAllByRole('link');
    await user.click(breadcrumbLinks[1]);

    await waitFor(() => {
      expect(screen.getByRole('heading', { name: /Nuestros Productos|Products/i })).toBeInTheDocument();
    });

    expect(window.location.pathname).toBe('/');
    expect(window.location.search).toContain('categoria=electronics');
  });
});
