// Generated by GitHub Copilot
// Para que sirve: Componente raiz que define rutas y estructura principal de la aplicacion.
// Entradas: Props, hooks de contexto y/o estado local segun el archivo.
// Flujo principal: Lee estado, aplica reglas de UI/negocio y renderiza la vista.
// Donde tocar cambios: Ajusta este archivo para modificar su comportamiento principal.
import { lazy, Suspense, useEffect } from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { CartProvider } from './context/CartContext';
import { AuthProvider } from './context/AuthContext';
import { ProductProvider } from './context/ProductContext';
import useAuth from './context/useAuth';
import useCart from './context/useCart';
import Navbar from './components/Navbar';
import Toast from './components/Toast';
import Footer from './components/Footer';
import ConfirmDialog from './components/ConfirmDialog';
import ErrorBoundary from './components/ErrorBoundary';
import RequireAuth from './components/RequireAuth';
import RequireRole from './components/RequireRole';
import ScrollToTop from './components/ScrollToTop';

// Generated by GitHub Copilot
// Lazy-loaded pages: each page is split into its own chunk loaded on demand,
// reducing the initial JS bundle size and improving first-paint performance.
const Home = lazy(() => import('./pages/Home'));
const Cart = lazy(() => import('./pages/Cart'));
const Checkout = lazy(() => import('./pages/Checkout'));
const Orders = lazy(() => import('./pages/Orders'));
const Favorites = lazy(() => import('./pages/Favorites'));
const AdminProducts = lazy(() => import('./pages/AdminProducts'));
const NotFound = lazy(() => import('./pages/NotFound'));
const ProductDetail = lazy(() => import('./pages/ProductDetail'));
const Login = lazy(() => import('./pages/Login'));
const Register = lazy(() => import('./pages/Register'));
const ForgotPassword = lazy(() => import('./pages/ForgotPassword'));

/** Minimal full-screen loading indicator shown while a lazy page chunk loads. */
function PageLoader() {
  return (
    <div
      className="min-h-screen flex items-center justify-center bg-gray-50"
      role="status"
      aria-label="Cargando página"
    >
      <div className="w-10 h-10 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin" aria-hidden="true" />
    </div>
  );
}

/**
 * Internal app shell that can safely consume providers.
 */
function AppShell() {
  const {
    isAuthenticated,
    authNotice,
    clearAuthNotice,
    showSessionExpiryWarning,
    sessionExpiryRemainingSeconds,
    extendSession,
    logout,
  } = useAuth();
  const { showToast } = useCart();

  const countdownText = sessionExpiryRemainingSeconds >= 60
    ? `${Math.floor(sessionExpiryRemainingSeconds / 60)}:${String(sessionExpiryRemainingSeconds % 60).padStart(2, '0')}`
    : `${sessionExpiryRemainingSeconds}s`;

  useEffect(() => {
    if (!authNotice) {
      return;
    }

    showToast(authNotice.message, authNotice.type || 'info');
    clearAuthNotice();
  }, [authNotice, clearAuthNotice, showToast]);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Skip-to-content link: visible only on keyboard focus (WCAG 2.4.1). z-[9999] keeps it above the sticky Navbar. */}
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-9999 focus:rounded-lg focus:bg-indigo-600 focus:px-4 focus:py-2 focus:font-medium focus:text-white"
      >
        Saltar al contenido
      </a>

      {isAuthenticated && <Navbar />}

      <div id="main-content" tabIndex="-1" className="outline-none">
        <ErrorBoundary>
          <Suspense fallback={<PageLoader />}>
            <Routes>
              <Route path="/login" element={<Login />} />
          <Route path="/registro" element={<Register />} />
          <Route path="/recuperar" element={<ForgotPassword />} />
          <Route path="/" element={<RequireAuth><Home /></RequireAuth>} />
          <Route path="/admin/productos" element={<RequireRole allowedRoles={['admin']}><AdminProducts /></RequireRole>} />
          <Route path="/carrito" element={<RequireRole allowedRoles={['cliente']}><Cart /></RequireRole>} />
          <Route path="/producto/:id" element={<RequireAuth><ProductDetail /></RequireAuth>} />
          <Route path="/checkout" element={<RequireRole allowedRoles={['cliente']}><Checkout /></RequireRole>} />
          <Route path="/pedidos" element={<RequireRole allowedRoles={['cliente']}><Orders /></RequireRole>} />
          <Route path="/favoritos" element={<RequireRole allowedRoles={['cliente']}><Favorites /></RequireRole>} />
              <Route path="/not-found" element={<NotFound />} />
              <Route path="*" element={<NotFound />} />
            </Routes>
          </Suspense>
        </ErrorBoundary>
      </div>

      {isAuthenticated && <Footer />}

      <ConfirmDialog
        open={isAuthenticated && showSessionExpiryWarning}
        title="Tu sesion esta por expirar"
        message={`Detectamos inactividad. Tu sesion expirara en ${countdownText}. Si quieres mantenerla activa, pulsa Seguir conectado.`}
        confirmLabel="Seguir conectado"
        cancelLabel="Cerrar sesion"
        onConfirm={extendSession}
        onCancel={logout}
      />

      <ScrollToTop />
      <Toast />
    </div>
  );
}

/**
 * App root: sets up routing and global CartProvider.
 */
export default function App() {
  return (
    <BrowserRouter>
      <AuthProvider>
        <ProductProvider>
          <CartProvider>
            <AppShell />
          </CartProvider>
        </ProductProvider>
      </AuthProvider>
    </BrowserRouter>
  );
}
